### ISSUE TITLE
不能启动，在系统日志里没显示错误

### ISSUE THREAD

**Issue by zlf179** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#100]
运行unm-debug命令的结果在下面的链接中
https://transfer.sh/NiCCh8/unm-debugging-output.txt

**Comment by 1715173329** [comment]
Ping @QiuSimons

**Comment by QiuSimons** [comment]
> Ping @QiuSimons

我这边一切正常啊~

**Comment by zlf179** [comment]
> > Ping @QiuSimons
> 
> 我这边一切正常啊~

那为啥我这不正常啊

**Comment by zlf179** [comment]
我在404大佬的以前版本OpenWrt 21.02 r15879-3b6c93298c / LuCI openwrt-21.02 branch git-21.066.23354-988a896 这个版本里装了2.12版本的unblockneteasemusic它也是启动不了
https://transfer.sh/NQMY97/unm-debugging-output.txt

**Comment by 1715173329** [comment]
Fixed.
