### ISSUE TITLE
Current release ipk doesn't install yt-dlp dependency 

### ISSUE THREAD

**Issue by hikariri123** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#105]
log: You must install "yt-dlp" before using the "ytdlp" source.

I have to manually install python3-pip and yt-dlp.

**Comment by 1715173329** [comment]
ytdlp is huge IMHO.
Don't use default value for sources.

**Comment by hikariri123** [comment]
I am outside China and use default settings in luci. Currently the program uses bili as the first pick and it will fall back to yt-dlp. yt-dlp seems to be the only way to unlock region contents and vip-only contents.

**Comment by 1715173329** [comment]
Well, kuwo should also work fine in your area.

As I mentioned above, Python is huge, and yt-dlp isn't a part of official OpenWrt.
