### ISSUE TITLE
基于Lienol / openwrt的19.07固件中无法下载内核

### ISSUE THREAD

**Issue by smmya** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#108]
点击下载直接返回【当前已是最新版本】，但是实际上并没有下载成功，请问下因为剩余空间不足（5.6m）吗？
不过在我的n1 docker openwrt可以正常运行

**Comment by 1715173329** [comment]
检查下网络，另外使用 `unm-debug` 打印调试报告。

**Comment by smmya** [comment]
> 下检查网络，另外使用`unm-debug`打印调试报告。

你好，路由器网络是正常的，不能使用的设备为新路由器3，自编译固件，目前剩余rom只有5m，ipk不能unm-debug吧

**Comment by smmya** [comment]
> 检查下网络，另外使用 `unm-debug` 打印调试报告。

Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07-SNAPSHOT'
DISTRIB_TARGET='ramips/mt7621'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_TAINTS='no-all'
DISTRIB_REVISION='19.07-SNAPSHOT'
DISTRIB_DESCRIPTION='OpenWrt '


uclient-fetch info:
Package: uclient-fetch
Version: 2020-06-17-51e16ebf-1
Depends: libc, libuclient
Provides: wget
Status: install user installed
Architecture: mipsel_24kc
Installed-Time: 1638351297

uclient-fetch: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
Failed to parse json data: unexpected end of data
Failed to connect to GitHub with uclient-fetch.


Node.js info:
Node.js is placed at Not Found
Node.js version: Not Found


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-1
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1641290215

-rw-------    1 root     root         255 Jan  4 18:23 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Nov  4 17:50 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
-rwxr-xr-x    1 root     root        4.4K Nov  4 17:50 debugging.sh
-rwxr-xr-x    1 root     root         348 Nov  4 17:50 log_check.sh
-rwxr-xr-x    1 root     root        3.0K Nov  4 17:50 update.sh

config unblockneteasemusic 'config'
        option enable_flac '0'
        option replace_music_source 'dont_replace'
        option use_custom_cookie '0'
        option advanced_mode '0'
        option music_source 'kuwo'
        option enable '0'
        option local_vip '0'
        option auto_update '0'



UnblockNeteaseMusic Node.js info:
Git HEAD version: Not Found
Core version: Not Found


Netease networking info:
< Location: http://m10.music.126.net/20220104193301/e5e9d2858bc81e406fb6c59f189995b7/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.160.195","59.111.19.33","118.24.63.156","39.105.175.128","47.100.127.239","39.105.63.80","182.92.170.253","193.112.159.225"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}},"msg":"OK"}

Running info:
/etc/rc.common: line 173: _procd_status: not found
PROCD running status: 


curl: (52) Empty reply from server


Log is available at:

https://transfer.sh/CQXFFB/unm-debugging-output.txt

**Comment by 1715173329** [comment]
缺少必需依赖：libustream-openssl 和 nodejs (>= 12.x)

**Comment by smmya** [comment]
> 缺少必需依赖：libustream-openssl 和 nodejs (>= 12.x)

请问一下内核文件大小是多大呢，
超过rom剩余空间我就去重新编译去掉lean的网易云解锁来保留空间，目前来说lean的网易云解锁已经不适用网易云新版本了

**Comment by 1715173329** [comment]
10 MB+

**Comment by smmya** [comment]
> 

略大，我试试能不能把固件缩到17mb以内，或者说大佬可以添加下载内核位置于外置usb空间内的功能吗？另外好像我记得mips架构的node.js没那么大吧
