### ISSUE TITLE
编译进大雕的固件以后,发现每次重启路由器之后都需要手动开启,

### ISSUE THREAD

**Issue by pikachullk** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#11]
RT,感觉每次启动好像都会重新下载一次核心版本,不知道是不是我设置问题,需要提供什么信息吗大佬

**Comment by 1715173329** [comment]
@pikachullk 请提供插件日志和相关系统日志

**Comment by pikachullk** [comment]
{ Error: connect EHOSTUNREACH 59.111.181.35:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '59.111.181.35',
  port: 443 }

**Comment by pikachullk** [comment]
刚刚才想起来这个日志....哈哈

**Comment by pikachullk** [comment]
这个会不会是因为开机启动后网络没有连上,然后插件没办法连上网易服务器导致的.
是不是加个延迟启动的选项能解决...
不太懂这个,希望大佬多多包涵

**Comment by 1715173329** [comment]
@pikachullk 这个属于网络问题。。。
拉高插件的启动时间试试。。

**Comment by pikachullk** [comment]
应该怎么设置啊您说这个....不太懂....希望大佬教教...谢谢大佬

**Comment by 1715173329** [comment]
@pikachullk 位于 /etc/init.d/unblockneteasemusic
将 START=90 中的90改为更高的数字试试

**Comment by pikachullk** [comment]
收到...谢谢大佬~我close了~太丢脸了这个~哈哈

**Comment by 1715173329** [comment]
@pikachullk 这个可能确实算是个bug
我可以加个进程守护选项。。

**Comment by pikachullk** [comment]
刚刚改了下init.d的脚本好像不行...改到150都是失败
只能暂时在rc.local加个sleep后再start吧~临时解决方案~

**Comment by 1715173329** [comment]
@pikachullk 嘛。。那我回家做一个进程守护方案。。

**Comment by 1715173329** [comment]
Fixed at 1eb93c1fc0ce0c1dd01d44e24fa55dce839c75b8.
