### ISSUE TITLE
更新内核成功，但是显示UnblockNeteaseMusic未在运行

### ISSUE THREAD

**Issue by joysboss** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#113]
unm-debug信息:

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_TARGET='armvirt/64'
DISTRIB_ARCH='aarch64_cortex-a53'
DISTRIB_TAINTS='no-all'
DISTRIB_REVISION='R22.1.1'
DISTRIB_DESCRIPTION='OpenWrt '

uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_cortex-a53
Size: 8238
Filename: uclient-fetch_2021-05-14-6a6011df-1_aarch64_cortex-a53.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1640884079

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libwolfssl4.8.1.5fb91bea
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5247
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-1_aarch64_cortex-a53.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5668
Filename: libustream-openssl20201210_2022-01-16-868fd881-1_aarch64_cortex-a53.ipk
Description: ustream SSL Library (openssl)

Package: libustream-openssl20201210
Version: 2020-12-10-68d09243-2
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: aarch64_cortex-a53
Installed-Time: 1640884079

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5505
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_aarch64_cortex-a53.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 20.205.243.168:443
Writing to stdout

Download completed (129380 bytes)
69f48174baf41a40253bec19c66916aafe6479bd

Node.js info:
Package: node
Version: v14.18.2-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libatomic1
Status: install user installed
Section: lang
Architecture: aarch64_cortex-a53
Size: 10433921
Filename: node_v14.18.2-1_aarch64_cortex-a53.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 6.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1640884079

Node.js is placed at /usr/bin/node
Node.js version: v14.18.2

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-2
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1642952710

-rwxrwxrwx    1 root     root         257 Jan 24 00:07 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Jan  6 13:19 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Jan 24 00:06 core
-rw-r--r--    1 root     root          41 Jan 24 00:06 core_local_ver
-rwxr-xr-x    1 root     root        4.7K Jan  6 13:19 debugging.sh
-rwxr-xr-x    1 root     root         348 Jan  6 13:19 log_check.sh
-rwxr-xr-x    1 root     root         532 Jan 24 00:02 unblock.sh
-rwxr-xr-x    1 root     root       39.1M Jan 23 23:53 unblockneteasemusic
-rwxr-xr-x    1 root     root       39.1M Jan 23 23:52 unblockneteasemusic-linux-arm64
-rwxr-xr-x    1 root     root        2.9K Jan  6 13:19 update.sh

config unblockneteasemusic 'config'
        option replace_music_source 'dont_replace'
        option use_custom_cookie '0'
        option local_vip '1'
        option enable_flac '1'
        option auto_update '0'
        option advanced_mode '0'
        option enable '1'
        option music_source 'pyncmd'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 69f48174baf41a40253bec19c66916aafe6479bd
Core version: v0.27.0-rc.4
-rw-r--r--    1 root     root      464.1K Jan 24 00:06 app.js
-rw-r--r--    1 root     root      407.7K Jan 24 00:06 bridge.js
-rw-r--r--    1 root     root         802 Jan 24 00:06 ca.crt
-rw-r--r--    1 root     root         847 Jan 24 00:06 server.crt
-rw-r--r--    1 root     root         359 Jan 24 00:06 server.key

Netease networking info:
< Location: http://m10.music.126.net/20220124003601/7a855b5806b51241081034db730fceb3/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.19.33","59.111.160.195","39.105.63.80","47.100.127.239","118.24.63.156","193.112.159.225","39.105.175.128","182.92.170.253"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}},"msg":"OK"}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      3638/microsocks_2e4
No instance found on port 5201.

Running info:
PROCD running status: running
Thread is not found.

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination        
RETURN     all  --  anywhere             0.0.0.0/8          
RETURN     all  --  anywhere             10.0.0.0/8         
RETURN     all  --  anywhere             127.0.0.0/8        
RETURN     all  --  anywhere             169.254.0.0/16     
RETURN     all  --  anywhere             172.16.0.0/12      
RETURN     all  --  anywhere             192.168.0.0/16     
RETURN     all  --  anywhere             base-address.mcast.net/4
RETURN     all  --  anywhere             240.0.0.0/4        
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 1040
References: 1
Members:
223.252.199.66
59.111.181.35
115.236.118.35
59.111.160.195
39.105.63.80
115.236.118.33
193.112.159.225
59.111.181.38
59.111.181.60
223.252.199.67
182.92.170.253
59.111.19.33
115.236.121.4
115.236.121.1
59.111.160.197
115.236.118.34
39.105.175.128
47.100.127.239
118.24.63.156

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 128
References: 1
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 128
References: 1
Members:

dhcp-option=252,http://192.168.123.3:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0}],"code":200}
curl: (56) Proxy CONNECT aborted

curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

Log is available at:

https://transfer.sh/CK6Bg2/unm-debugging-output.txt
root@OpenWrt

**Comment by 1715173329** [comment]
端口 5200 被 microsocks 占用了。

**Comment by joysboss** [comment]
太感谢了。祝虎年行大运
