### ISSUE TITLE
大佬们新年好，无法更新local核心求指教？

### ISSUE THREAD

**Issue by batmancar** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#114]
Local version: NOT FOUND, latest version: 69f48174baf41a40253bec19c66916aafe6479bd.
Updating core...
Failed to download app.js.

**Comment by 1715173329** [comment]
你网烂了。

**Comment by isDaKai** [comment]
一样的问题
把DHCP中 禁止解析 IPv6 DNS 记录 勾选 即可解决
