### ISSUE TITLE
全新安装2.12-2 更新内核无法启动 19.07.7 官方

### ISSUE THREAD

**Issue by beeperman** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#115]
https://litter.catbox.moe/mh57z6.txt
unm-debug

root@OpenWrt:~# unm-debug 
Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.7'
DISTRIB_REVISION='r11306-c4a6851c72'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 19.07.7 r11306-c4a6851c72'
DISTRIB_TAINTS=''

uclient-fetch info:
Package: uclient-fetch
Version: 2020-06-17-51e16ebf-1
Depends: libc, libuclient20160123
Provides: wget
Status: install user installed
Section: net
Architecture: x86_64
Size: 7764
Filename: uclient-fetch_2020-06-17-51e16ebf-1_x86_64.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1613402557

Package: libustream-openssl20201210
Version: 2020-12-10-68d09243-2
Depends: libc, libubox20210819, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1630007002

Package: libustream-wolfssl20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libwolfssl24
Provides: libustream-wolfssl
Status: install user not-installed
Section: libs
Architecture: x86_64
Size: 4610
Filename: libustream-wolfssl20150806_2020-03-13-40b563b1-1_x86_64.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5218
Filename: libustream-openssl20150806_2020-03-13-40b563b1-1_x86_64.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libmbedtls12
Provides: libustream-mbedtls
Status: install user not-installed
Section: libs
Architecture: x86_64
Size: 4835
Filename: libustream-mbedtls20150806_2020-03-13-40b563b1-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 192.30.255.116:443
Writing to stdout

Download completed (129380 bytes)
69f48174baf41a40253bec19c66916aafe6479bd

Node.js info:
Package: node
Version: v8.16.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libhttp-parser
Status: install ok installed
Section: lang
Architecture: x86_64
Size: 5152678
Filename: node_v8.16.1-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
Installed-Time: 1614379904

Node.js is placed at /usr/bin/node
Node.js version: v8.16.1

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-2
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1643914667

-rw-------    1 root     root         650 Feb  3 19:16 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Feb  3 19:08 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Feb  3 19:01 core
-rw-r--r--    1 root     root          41 Feb  3 19:01 core_local_ver
-rwxr-xr-x    1 root     root        4.7K Jan  6 05:19 debugging.sh
-rwxr-xr-x    1 root     root         348 Jan  6 05:19 log_check.sh
-rwxr-xr-x    1 root     root        2.9K Jan  6 05:19 update.sh

config unblockneteasemusic
	option replace_music_source 'dont_replace'
	option daemon_enable '1'
	option advanced_mode '1'
	option http_port '5200'
	option https_port '5201'
	option hijack_ways 'use_ipset'
	option use_custom_cookie '0'
	option keep_core_when_upgrade '0'
	option strict_mode '0'
	option auto_update '0'
	option enable_flac '0'
	option use_remote_qq_server '0'
	option endpoint_url 'http://music.163.com'
	option local_vip '0'
	option enable '1'
	option music_source 'default'
	option pub_access '0'
	option proxy_server_ip 'set'

config acl_rule
	option filter_mode 'disable_all'
	option ip_addr '192.168.90.0/31'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 69f48174baf41a40253bec19c66916aafe6479bd
Core version: Not Found
-rw-r--r--    1 root     root      464.1K Feb  3 19:01 app.js
-rw-r--r--    1 root     root      407.7K Feb  3 19:01 bridge.js
-rw-r--r--    1 root     root         802 Feb  3 19:01 ca.crt
-rw-r--r--    1 root     root         847 Feb  3 19:01 server.crt
-rw-r--r--    1 root     root         359 Feb  3 19:01 server.key

Netease networking info:
< Location: http://music.163.com/404
{"code":200,"data":{"music.163.com":{"ip":["103.126.92.133","103.126.92.132","59.111.160.195","59.111.19.33"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}},"msg":"OK"}

Port status:
No instance found on port 5200.
No instance found on port 5201.

Running info:
PROCD running status: Syntax: /etc/init.d/unblockneteasemusic [command]

Available commands:
	start	Start the service
	stop	Stop the service
	restart	Restart the service
	reload	Reload configuration files (or restart if service does not implement reload)
	enable	Enable service autostart
	disable	Disable service autostart

cat: can't open '/tmp/unblockneteasemusic.log': No such file or directory

Log is available at:
https://litter.catbox.moe/mh57z6.txt
https://transfer.sh/gbc8J8/unm-debugging-output.txt

**Comment by 1715173329** [comment]
需要 Node.js 12.x LTS 及以上版本。

**Comment by beeperman** [comment]
更新到v14后似乎还是显示没有启动。
https://litter.catbox.moe/entrr4.txt
https://transfer.sh/cQkY6a/unm-debugging-output.txt

**Comment by 1715173329** [comment]
手动重启一下

**Comment by beeperman** [comment]
全删掉再装就能跑了。谢谢！
