### ISSUE TITLE
听着听着登录信息没了，并且不能签到

### ISSUE THREAD

**Issue by isDaKai** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#122]
![屏幕截图 2022-02-18 162619](https://user-images.githubusercontent.com/18066490/154645985-2fcf34b3-146e-4249-b1cf-388e93863f1a.png)
![屏幕截图 2022-02-18 162819](https://user-images.githubusercontent.com/18066490/154646251-843efa96-e091-4528-975f-1fa07d19f129.png)

**Comment by 1715173329** [comment]
1. 不要做毫无意义的追新
2. 信任 CA 根证书

**Comment by isDaKai** [comment]
> 1. 不要做毫无意义的追新
> 2. 信任 CA 根证书

抱歉，打扰了，找到问题了，passwall导致的，换成ssrp后正常了
