### ISSUE TITLE
无法运行帮忙看看谢谢大佬

### ISSUE THREAD

**Issue by lisankai93** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#138]
自己在github action编译的openwrt里面本来有一个，无法使用，我就删除然后再您release里面重新下ipk使用，结果发现无法运行，请帮忙看看，谢谢！说是没有核心？

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_TAINTS='no-all override'
DISTRIB_REVISION='R22.3.13'
DISTRIB_DESCRIPTION='OpenWrt '

uclient-fetch info:
Package: uclient-fetch
Version: 2020-06-17-51e16ebf-1
Depends: libc, libuclient20160123
Provides: wget
Status: unknown ok not-installed
Section: net
Architecture: x86_64
Size: 7765
Filename: uclient-fetch_2020-06-17-51e16ebf-1_x86_64.ipk
Description: Tiny wget replacement using libuclient

Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1648258599

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1648258599

Package: libustream-wolfssl20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libwolfssl30
Provides: libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 4642
Filename: libustream-wolfssl20150806_2020-03-13-40b563b1-1_x86_64.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libopenssl1.1
Provides: libustream-openssl
Status: install ok installed
Section: libs
Architecture: x86_64
Size: 5218
Filename: libustream-openssl20150806_2020-03-13-40b563b1-1_x86_64.ipk
Description: ustream SSL Library (openssl)
Installed-Time: 1648958366

Package: libustream-mbedtls20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libmbedtls12
Provides: libustream-mbedtls
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 4830
Filename: libustream-mbedtls20150806_2020-03-13-40b563b1-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 20.205.243.168:443
HTTP error 403
Failed to parse json data: unexpected end of data
Failed to connect to GitHub with uclient-fetch.

Node.js info:
Package: node
Version: v8.16.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libhttp-parser
Status: install user installed
Section: lang
Architecture: x86_64
Size: 5153037
Filename: node_v8.16.1-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
Installed-Time: 1648958821

Node.js is placed at /usr/bin/node
Node.js version: Not Found

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-3
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1648960915

-rw-r--r--    1 root     root         282 Apr  3 12:43 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.7K Mar 13 13:21 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
-rwxr-xr-x    1 root     root        4.7K Mar 13 13:21 debugging.sh
-rwxr-xr-x    1 root     root         348 Mar 13 13:21 log_check.sh
drwxr-xr-x    2 root     root        3.4K Apr  3 12:41 rules
-rwxr-xr-x    1 root     root        2.9K Mar 13 13:21 update.sh

config unblockneteasemusic 'config'
	option music_source 'default'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option auto_update '1'
	option update_time '3'
	option advanced_mode '0'
	option enable '1'
	option local_vip '0'
	option enable_flac '0'

UnblockNeteaseMusic Node.js info:
Git HEAD version: Not Found
Core version: Not Found

Netease networking info:
< Location: http://m10.music.126.net/20220403130916/58486b620094dd195507b1a896a8648e/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.19.33","59.111.160.195","182.92.170.253","118.24.63.156","47.100.127.239","193.112.159.225","39.105.175.128","39.105.63.80"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}},"msg":"OK"}

Port status:
No instance found on port 5200.
No instance found on port 5201.

Running info:
PROCD running status: inactive

Failed to check latest core version, please try again later.
Core Not Found, please[ download ]it before starting.

**Comment by lisankai93** [comment]
openwrt输入node，一堆报错。。。
所以重新编译的话如何解决node问题呢？谢谢

`root@OpenWrt:~# node
Error relocating /usr/bin/node: _ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4_: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcPKcS7_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLERKS4_: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmRKS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLEPKc: symbol not found
Error relocating /usr/bin/node: _ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKcm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strEv: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEPKc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEm: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4copyEPcmm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmPKc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEPKcm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEOS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13_S_copy_charsEPcS5_S5_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructEmc: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findERKS4_m: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9_PcSA_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEmc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendERKS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEED1Ev: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EOS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmRKS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6insertEmmc: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6substrEmm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strERKNS_12basic_stringIcS2_S3_EE: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEc: symbol not found
Error relocating /usr/bin/node: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9push_backEc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEPKc: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4swapERS4_: symbol not found
Error relocating /usr/bin/node: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode: symbol not found`

**Comment by msylgj** [comment]
Failed to connect to GitHub with uclient-fetch.

Core Not Found, please[ download ]it before starting.

调试信息已经告诉你了

**Comment by 1715173329** [comment]
自行拉取本仓库源码，从源码编译。
你的网络亦有问题，无法与 github api 通讯。

**Comment by lisankai93** [comment]
谢谢，已经在编译的时候选了node，而且拉了仓库。重新在action编译了。网络我是有梯子的，应该没问题
