### ISSUE TITLE
日志依赖都无问题，也可以运行但是无法播放灰色歌曲，谢谢啦

### ISSUE THREAD

**Issue by lisankai93** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#139]
日志依赖都无问题，也可以运行但是无法播放灰色歌曲

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_TAINTS='no-all override'
DISTRIB_REVISION='R22.4.1'
DISTRIB_DESCRIPTION='OpenWrt '

uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: x86_64
Size: 7941
Filename: uclient-fetch_2021-05-14-6a6011df-1_x86_64.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1648964095

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libwolfssl5.1.1.5fb91bea
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5064
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (wolfssl)
Installed-Time: 1649064758

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5521
Filename: libustream-openssl20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (openssl)
Installed-Time: 1648964095

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5338
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)
Installed-Time: 1649064794

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 20.205.243.168:443
Writing to stdout

-                    100% |*******************************|   123k  0:00:00 ETA
Download completed (126362 bytes)
55c53cf9e5ac176e8cd171b0ca0b3a0b50d614f6

Node.js info:
Package: node
Version: v14.18.3-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libatomic1
Status: install user installed
Section: lang
Architecture: x86_64
Size: 10507859
Filename: node_v14.18.3-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 6.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1648964095

Node.js is placed at /usr/bin/node
Node.js version: v14.18.3

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-3
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Installed-Time: 1648964095

-rw-r--r--    1 root     root         282 Apr  4 17:34 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.7K Apr  3 13:34 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        3.4K Apr  4 11:20 core
-rw-r--r--    1 root     root          41 Apr  4 11:20 core_local_ver
-rwxr-xr-x    1 root     root        4.7K Apr  3 13:34 debugging.sh
-rwxr-xr-x    1 root     root         348 Apr  3 13:34 log_check.sh
drwxr-xr-x    2 root     root          63 Apr  3 13:34 rules
-rwxr-xr-x    1 root     root        2.9K Apr  3 13:34 update.sh

config unblockneteasemusic 'config'
	option music_source 'default'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option auto_update '1'
	option update_time '3'
	option advanced_mode '0'
	option enable '1'
	option enable_flac '1'
	option local_vip '1'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 55c53cf9e5ac176e8cd171b0ca0b3a0b50d614f6
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      472.5K Apr  4 11:20 app.js
-rw-r--r--    1 root     root      416.1K Apr  4 11:20 bridge.js
-rw-r--r--    1 root     root         802 Apr  4 11:20 ca.crt
-rw-r--r--    1 root     root         847 Apr  4 11:20 server.crt
-rw-r--r--    1 root     root         359 Apr  4 11:20 server.key

Netease networking info:
< Location: http://m10.music.126.net/20220404180123/b6931f2750c54a790f3a93de0f8d01d6/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.160.195","59.111.19.33","118.24.63.156","182.92.170.253","47.100.127.239","39.105.63.80","193.112.159.225","39.105.175.128"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}},"msg":"OK"}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      13159/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      13159/node

Running info:
PROCD running status: running
13159 root      244m S    node /usr/share/unblockneteasemusic/core/app.js -a 0.0.0.0 -p 5200:5201 -e https://music.163.com

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x4a067121
Size in memory: 1360
References: 1
Number of entries: 29
Members:
59.111.160.195
115.236.118.33
59.37.80.225
223.252.199.66
59.37.80.224
118.24.63.156
14.215.93.19
59.111.181.60
59.111.160.197
59.111.181.35
223.252.199.67
182.92.170.253
59.37.80.229
59.37.80.230
115.236.118.35
47.100.127.239
59.37.80.227
59.37.80.231
115.236.121.1
59.111.181.38
39.105.175.128
39.105.63.80
115.236.121.4
115.236.118.34
193.112.159.225
113.96.179.19
59.37.80.228
59.37.80.226
59.111.19.33

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0xc5e444f9
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x92829742
Size in memory: 200
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.1.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL3Vwb3Mtc3otbWlycm9yY29zLmJpbGl2aWRlby5jb20vdWdheGNvZGUvbTE5MDgwNndzMjZnMTdnMnNjZHR3azIyYjk3c2FrMDAtMTkyay5tNGE_ZT1pZzhldXhaTTJyTmNOYmRsaG9Odk5DOEJxSkl6TmJmcVhCdkVxeFRFdG84QlRyTnZOMEd2VDkwVzVKWk1rWF9ZTjBNdlhnOGdORVY0TkM4eE5FVjROMDNlTjBCNXRabHFOeFRFdG84QlRyTnZOZVpWdUoxMEtqX2cyVUIwMkowbU4wQjV0WmxxTkNORXRvOEJUck52TkM3TVRYNTAyQzhmMmptTVFKNm1xRjJma2ExbXF4NmdxajBlTjBCNTk5TT0mdWlwaz01Jm5icz0xJmRlYWRsaW5lPTE2NDkwNzIxODQmZ2VuPXBsYXl1cmx2MiZvcz1jb3NidiZvaT0xNzM0NDYxNTUxJnRyaWQ9YTI1OGJiYWQ1OGYxNDg2ZWE2YTBkYzRkZGE2YTcxN2VCJnBsYXRmb3JtPXBjJnVwc2lnPTgyYTRmNWIwYjljZjUzNGMxMGY3MmYwOTQzOWJiZmFmJnVwYXJhbXM9ZSx1aXBrLG5icyxkZWFkbGluZSxnZW4sb3Msb2ksdHJpZCxwbGF0Zm9ybSZtaWQ9MCZidmM9dm9kJm5ldHR5cGU9MCZvcmRlcmlkPTAsMSZsb2dvPTAwMDAwMDAw/33190502.mp3","br":128000,"size":6351104,"md5":"1a63ccc9f0e44b03b458ec79308ab96c","code":200,"expi":1200,"type":"mp3","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0}],"code":200}
{"level":50,"time":1649064984574,"pid":13159,"hostname":"OpenWrt","scope":"provider/yt-dlp","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:3094:45)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async search (/usr/share/unblockneteasemusic/core/app.js:3099:21)\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:130:32)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:2428:23)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":50,"time":1649064984606,"pid":13159,"hostname":"OpenWrt","scope":"provider/match","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:3094:45)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async search (/usr/share/unblockneteasemusic/core/app.js:3099:21)\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:130:32)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:2428:23)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":30,"time":1649064985166,"pid":13159,"hostname":"OpenWrt","scope":"provider/match","audioId":33190502,"songName":"君のままで","url":"http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m190806ws26g17g2scdtwk22b97sak00-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1649072184&gen=playurlv2&os=cosbv&oi=1734461551&trid=a258bbad58f1486ea6a0dc4dda6a717eB&platform=pc&upsig=82a4f5b0b9cf534c10f72f09439bbfaf&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&logo=00000000","msg":"Replaced: [33190502] 君のままで"}

**Comment by 1715173329** [comment]
什么客户端？证书信任了吗？

**Comment by lisankai93** [comment]
就是ios网易云音乐客户端
不用证书，以前用其他人编译的固件是可以不用证书直接局域网打开app听歌的，谢谢

**Comment by Lebo-Wang** [comment]
VIP也不太行，只能播放开口，iOS，不知道漏了什么，pc可以

**Comment by 1715173329** [comment]
不信任证书是无法正常使用的。

**Comment by Lebo-Wang** [comment]
> 不信任证书是无法正常使用的。

已经用了ca证书了，难道要自己重签证书么？谢谢

**Comment by Lebo-Wang** [comment]
好像可以了，谢谢

**Comment by lisankai93** [comment]
> 好像可以了，谢谢

请问如何使用？我用了ca证书（github下载/插件内下载）都还是不可以，灰色，无版权，谢谢！

**Comment by lisankai93** [comment]
我还是把日志贴上来，希望大佬们帮忙看看到底咋回事

Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_TAINTS='no-all override'
DISTRIB_REVISION='R22.4.1'
DISTRIB_DESCRIPTION='OpenWrt '


uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1648964095

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libwolfssl5.1.1.5fb91bea
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1649064758

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1648964095

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20211120, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1649064794

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 13.230.158.120:443
Writing to stdout

Download completed (125581 bytes)
5fdfda6e606550d0dbfda12142f638235a3bd3ef


Node.js info:
Package: node
Version: v14.18.3-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libatomic1
Status: install user installed
Architecture: x86_64
Installed-Time: 1648964095

Node.js is placed at /usr/bin/node
Node.js version: v14.18.3


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-3
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Installed-Time: 1648964095

-rw-r--r--    1 root     root         282 May 11 00:07 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.7K Apr  3 13:34 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        3.4K May 11 03:00 core
-rw-r--r--    1 root     root          41 May 11 03:00 core_local_ver
-rwxr-xr-x    1 root     root        4.7K Apr  3 13:34 debugging.sh
-rwxr-xr-x    1 root     root         348 Apr  3 13:34 log_check.sh
drwxr-xr-x    2 root     root          63 Apr  3 13:34 rules
-rwxr-xr-x    1 root     root        2.9K Apr  3 13:34 update.sh

config unblockneteasemusic 'config'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option auto_update '1'
	option update_time '3'
	option music_source 'default'
	option enable_flac '1'
	option advanced_mode '0'
	option enable '1'
	option local_vip '0'



UnblockNeteaseMusic Node.js info:
Git HEAD version: 5fdfda6e606550d0dbfda12142f638235a3bd3ef
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      472.8K May 11 03:00 app.js
-rw-r--r--    1 root     root      416.2K May 11 03:00 bridge.js
-rw-r--r--    1 root     root         790 May 11 03:00 ca.crt
-rw-r--r--    1 root     root         843 May 11 03:00 server.crt
-rw-r--r--    1 root     root         359 May 11 03:00 server.key


Netease networking info:
< Location: http://m10.music.126.net/20220511101319/f625bb8b8a9a746231e134eb3cb56244/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["103.126.92.132","103.126.92.133","59.111.19.33","59.111.160.195"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      2493/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      2493/node


Running info:
PROCD running status: running
 2493 root      303m S    node /usr/share/unblockneteasemusic/core/app.js -a 0


Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x9b61391a
Size in memory: 960
References: 1
Number of entries: 19
Members:
118.24.63.156
39.105.63.80
59.111.181.38
115.236.121.4
47.100.127.239
39.105.175.128
59.111.160.197
115.236.118.34
193.112.159.225
59.111.181.35
59.111.19.33
115.236.118.35
223.252.199.67
223.252.199.66
115.236.118.33
115.236.121.1
182.92.170.253
59.111.181.60
59.111.160.195

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x6cb536d7
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x016f87b4
Size in memory: 200
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.1.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic


Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2ZyZWV0eXN0Lm5mLm1pZ3UuY24vcHVibGljL3Byb2R1Y3Q1dGgvcHJvZHVjdDM1LzIwMTkvMTAvMDMxMS8yMDE5JUU1JUI5JUI0MDglRTYlOUMlODgyMSVFNiU5NyVBNTExJUU3JTgyJUI5MzUlRTUlODglODYlRTYlODklQjklRTklODclOEYlRTklQTElQjklRTclOUIlQUVBVkVYMTAwJUU5JUE2JTk2LTMvJUU2JUFEJThDJUU2JTlCJUIyJUU0JUI4JThCJUU4JUJEJUJEL2ZsYWMvNjk5MzExMTU3OTcuZmxhYw==/33190502.flac","br":999000,"size":46523504,"md5":"dd713ad59f47f12479a752e46105d438","code":200,"expi":1200,"type":"flac","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0}],"code":200}
{"level":50,"time":1652233700920,"pid":2493,"hostname":"OpenWrt","scope":"provider/yt-dlp","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:3073:45)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async search (/usr/share/unblockneteasemusic/core/app.js:3078:21)\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:130:32)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:2426:23)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":50,"time":1652233700921,"pid":2493,"hostname":"OpenWrt","scope":"provider/match","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:3073:45)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async search (/usr/share/unblockneteasemusic/core/app.js:3078:21)\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:130:32)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:2426:23)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":30,"time":1652233701301,"pid":2493,"hostname":"OpenWrt","scope":"provider/match","audioId":33190502,"songName":"君のままで","url":"http://freetyst.nf.migu.cn/public/product5th/product35/2019/10/0311/2019%E5%B9%B408%E6%9C%8821%E6%97%A511%E7%82%B935%E5%88%86%E6%89%B9%E9%87%8F%E9%A1%B9%E7%9B%AEAVEX100%E9%A6%96-3/%E6%AD%8C%E6%9B%B2%E4%B8%8B%E8%BD%BD/flac/69931115797.flac","msg":"Replaced: [33190502] 君のままで"}

**Comment by lisankai93** [comment]
ps: ios已安装ca证书了
