### ISSUE TITLE
uwp要如何设置

### ISSUE THREAD

**Issue by Jieoz** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#140]
使用默认设置貌似并不可以解锁uwp的版权音乐

**Comment by 1715173329** [comment]
命令行输入 unm-debug 打印调试日志。

**Comment by Jieoz** [comment]
> 命令行输入 unm-debug 打印调试日志。

https://transfer.sh/rlB6un/unm-debugging-output.txt
求大佬帮忙分析，像是没有配置文件吗
