### ISSUE TITLE
windows端正常使用，安卓端无效

### ISSUE THREAD

**Issue by mirrorb** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#149]
安卓端已经安装ca证书，版本是7.30

**Comment by 1715173329** [comment]
https://github.com/nining377/dolby_beta
推荐使用

**Comment by mirrorb** [comment]
我之前在用这个项目的α版，用的时候不会有冲突吗，需要设置例外客户端吗

**Comment by Beginner-Go** [comment]
![image](https://user-images.githubusercontent.com/70857188/168461755-95aa8483-e9a6-495b-b653-4995ff74fd10.png)

**Comment by 1715173329** [comment]
α版和 β版开一个就行了，使用的时候可以自行切换。
