### ISSUE TITLE
运行一段时间后会停止工作

### ISSUE THREAD

**Issue by zzz6839** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#152]
每次正常运行一段时间后会未在运行，删除核心后更新核心重新正常运行。

debug日志：
https://transfer.sh/PIzMjh/unm-debugging-output.txt

尝试node app.js：
`root@OpenWrt:/usr/share/unblockneteasemusic/core# node app.js
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/share/unblockneteasemusic/server.key'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.3375 (/usr/share/unblockneteasemusic/core/app.js:3272:13)
    at __webpack_require__ (/usr/share/unblockneteasemusic/core/app.js:16046:41)
    at /usr/share/unblockneteasemusic/core/app.js:16166:16
    at /usr/share/unblockneteasemusic/core/app.js:16219:3
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:16221:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/share/unblockneteasemusic/server.key'`

**Comment by 1715173329** [comment]
procd 会自动拉起进程，除非在 2 小时内持续崩溃 5 次。
建议查看系统日志检索是否有相关信息。

**Comment by zzz6839** [comment]
报了很多这个，不知道是不是问题
Wed Jun  1 05:01:52 2022 daemon.info procd: - init complete -
Wed Jun  1 05:05:00 2022 cron.err crond[9641]: USER root pid 10984 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:10:00 2022 cron.err crond[9641]: USER root pid 12379 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:15:00 2022 cron.err crond[9641]: USER root pid 13757 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:20:00 2022 cron.err crond[9641]: USER root pid 15142 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:25:00 2022 cron.err crond[9641]: USER root pid 16521 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:30:00 2022 cron.err crond[9641]: USER root pid 17910 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:35:00 2022 cron.err crond[9641]: USER root pid 19288 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:40:00 2022 cron.err crond[9641]: USER root pid 20679 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:45:00 2022 cron.err crond[9641]: USER root pid 22044 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:50:00 2022 cron.err crond[9641]: USER root pid 23441 cmd /usr/share/unblockneteasemusic/log_check.sh
Wed Jun  1 05:55:00 2022 cron.err crond[9641]: USER root pid 24817 cmd /usr/share/unblockneteasemusic/log_check.sh

**Comment by 1715173329** [comment]
crond 只是常规计划任务执行输出。
需要寻找 `crashes` 字眼。

**Comment by zzz6839** [comment]
> crond 只是常规计划任务执行输出。 需要寻找 `crashes` 字眼。

sorry，没有搜索到相关的记录
[New Text Document.txt](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/files/8811875/New.Text.Document.txt)

**Comment by 1715173329** [comment]
Can't reproduce.
