### ISSUE TITLE
无法运行 提示找不到核心 更新提示已是最新

### ISSUE THREAD

**Issue by hqwlcm** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#153]
Failed to check latest core version, please try again later.
Core Not Found, please download it before starting.

**Comment by 1715173329** [comment]
你网烂了。

**Comment by hqwlcm** [comment]
> 你网烂了。

北京移动的宽带 只开passwd和AdGuardHome 要不给个地址 我都加白名单看看
