### ISSUE TITLE
运行后找不到原有的 server.key，请求帮助

### ISSUE THREAD

**Issue by Akanezero** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#157]
Error: ENOENT: no such file or directory, open '/usr/share/unblockneteasemusic/server.key'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.3375 (/usr/share/unblockneteasemusic/core/app.js:3272:13)
    at __webpack_require__ (/usr/share/unblockneteasemusic/core/app.js:16046:41)
    at /usr/share/unblockneteasemusic/core/app.js:16166:16
    at /usr/share/unblockneteasemusic/core/app.js:16219:3
    at Object.<anonymous> (/usr/share/unblockneteasemusic/core/app.js:16221:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/share/unblockneteasemusic/server.key'

**Comment by 1715173329** [comment]
删除核心重新下载。

**Comment by Akanezero** [comment]
还是不行，unm-debug如下，大佬有空时回复就好，非常感激！
OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.2'
DISTRIB_REVISION='2022061017'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION='OpenWrt 21.02.2 2022061017'
DISTRIB_TAINTS='no-all busybox'


uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_generic
Size: 8424
Filename: uclient-fetch_2021-05-14-6a6011df-1_aarch64_generic.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1654833483

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libwolfssl5.2.0.99a5b54a
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 5286
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-1_aarch64_generic.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Section: libs
Architecture: aarch64_generic
Size: 5657
Filename: libustream-openssl20201210_2022-01-16-868fd881-1_aarch64_generic.ipk
Description: ustream SSL Library (openssl)
Installed-Time: 1654833483

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 5533
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_aarch64_generic.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 198.18.2.60:443
Writing to stdout

Download completed (125442 bytes)
34946a70a75ce4b6fc49f6977ea84b79c2ce6b91


Node.js info:
Package: node
Version: v14.19.3-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install user installed
Section: lang
Architecture: aarch64_generic
Size: 10571414
Filename: node_v14.19.3-1_aarch64_generic.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 6.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1655579290

Node.js is placed at /usr/bin/node
Node.js version: v14.19.3


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-4
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1655620737

-rw-r--r--    1 root     root        1.5K Jun 19 22:16 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.6K Apr 25 08:21 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Jun 19 21:14 core
-rw-r--r--    1 root     root          41 Jun 19 21:14 core_local_ver
-rwxr-xr-x    1 root     root        5.5K Apr 25 08:21 debugging.sh
-rwxr-xr-x    1 root     root         348 Apr 25 08:21 log_check.sh
drwxr-xr-x    2 root     root        4.0K Jun 19 14:38 rules
-rwxr-xr-x    1 root     root        2.9K Apr 25 08:21 update.sh

config unblockneteasemusic 'config'
	option replace_music_source 'dont_replace'
	option auto_update '1'
	option update_time '3'
	option music_source 'default'
	option local_vip '1'
	option enable_flac '1'
	option use_custom_cookie '1'
	option enable '1'
	option joox_cookie 'set'
	option qq_cookie 'set'
	option advanced_mode '1'
	option http_port '5200'
	option https_port '5201'
	option endpoint_url 'https://music.163.com'
	option hijack_ways 'use_ipset'
	option keep_core_when_upgrade '1'
	option pub_access '1'
	option strict_mode '1'



UnblockNeteaseMusic Node.js info:
Git HEAD version: 34946a70a75ce4b6fc49f6977ea84b79c2ce6b91
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      471.5K Jun 19 21:14 app.js
-rw-r--r--    1 root     root      416.2K Jun 19 21:14 bridge.js
-rw-r--r--    1 root     root         790 Jun 19 21:14 ca.crt
-rw-r--r--    1 root     root         843 Jun 19 21:14 server.crt
-rw-r--r--    1 root     root         359 Jun 19 21:14 server.key


Netease networking info:
< Location: http://m10.music.126.net/20220619233850/37a4e9f604e010d36537bd81b699f020/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["45.254.48.1","101.71.154.241","59.111.160.195","59.111.19.33","39.105.175.128","182.92.170.253","193.112.159.225","39.105.63.80","47.100.127.239","118.24.63.156"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
No instance found on port 5200.
No instance found on port 5201.


Running info:
PROCD running status: inactive


cat: can't open '/tmp/unblockneteasemusic.log': No such file or directory

**Comment by Akanezero** [comment]
两个缺失依赖均安装，但还是未能启动
