### ISSUE TITLE
核心已更新，但显示UnblockNeteaseMusic 未在运行

### ISSUE THREAD

**Issue by sArtzeey** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#162]
OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.2'
DISTRIB_REVISION='2022062120'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 21.02.2 2022062120'
DISTRIB_TAINTS='no-all busybox'

uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1655803461

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1655803461

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 20.205.243.168:443
Writing to stdout

Download completed (125442 bytes)
92045f7a4876cac2d1cd19e134a7d2c613bb7c11

Node.js info:
Package: node
Version: v14.19.3-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install user installed
Architecture: x86_64
Installed-Time: 1656517527

Node.js is placed at /usr/bin/node
Node.js version: v14.19.3

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-4
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1656411506

-rw-r--r--    1 root     root         282 Jun 28 22:58 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.6K Apr 25 08:21 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Jun 30 00:33 core
-rw-r--r--    1 root     root          41 Jun 30 00:33 core_local_ver
-rwxr-xr-x    1 root     root        5.5K Apr 25 08:21 debugging.sh
-rwxr-xr-x    1 root     root         348 Apr 25 08:21 log_check.sh
drwxr-xr-x    2 root     root        4.0K Jun 28 18:18 rules
-rwxr-xr-x    1 root     root        2.9K Apr 25 08:21 update.sh

config unblockneteasemusic 'config'
        option music_source 'default'
        option replace_music_source 'dont_replace'
        option use_custom_cookie '0'
        option auto_update '1'
        option update_time '3'
        option enable '1'
        option local_vip '1'
        option enable_flac '1'
        option advanced_mode '0'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 92045f7a4876cac2d1cd19e134a7d2c613bb7c11
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      470.7K Jun 30 00:33 app.js
-rw-r--r--    1 root     root      415.4K Jun 30 00:33 bridge.js
-rw-r--r--    1 root     root         790 Jun 30 00:33 ca.crt
-rw-r--r--    1 root     root         843 Jun 30 00:33 server.crt
-rw-r--r--    1 root     root         359 Jun 30 00:33 server.key

Netease networking info:
< Location: http://m10.music.126.net/20220630010123/c60f73e6833cf25cf74365ba49fb4069/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.19.33","59.111.160.195","39.105.175.128","193.112.159.225","39.105.63.80","182.92.170.253","47.100.127.239","118.24.63.156"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      11263/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      11263/node

Running info:
PROCD running status: running
Thread is not found.

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 1112
References: 1
Number of entries: 19
Members:
115.236.121.1
193.112.159.225
118.24.63.156
39.105.63.80
115.236.118.33
115.236.118.34
59.111.181.60
59.111.19.33
182.92.170.253
47.100.127.239
223.252.199.67
59.111.181.35
115.236.121.4
223.252.199.66
59.111.181.38
59.111.160.195
39.105.175.128
59.111.160.197
115.236.118.35

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 200
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 200
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.1.25/24:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0}],"code":200}
curl: (7) Failed to connect to 192.168.1.25 port 1080 after 0 ms: Connection refused

curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

**Comment by ximencx** [comment]
同样的问题,在istore os x86遇到的

**Comment by 1715173329** [comment]
`dhcp-option=252,http://192.168.1.25/24:5200/proxy.pac`

uh what? 旁路由？

**Comment by sArtzeey** [comment]
> `dhcp-option=252,http://192.168.1.25/24:5200/proxy.pac`
> 
> uh what? 旁路由？

是的，旁路由不能用吗？

**Comment by 1715173329** [comment]
> 是的，旁路由不能用吗？

旁路由请自求多福。

btw 核心正常运行中。
