### ISSUE TITLE
openwrt + macOS 无法正常使用

### ISSUE THREAD

**Issue by showyoulove1990** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#164]
更新了最新的核心，也在macos上装了证书，但是还是无法使用，都是灰色的

**Comment by 1715173329** [comment]
1. 日志，网易云音乐版本
2. 路由器执行 unm-debug 打印调试报告

**Comment by showyoulove1990** [comment]
@1715173329 
Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
DISTRIB_ID='1004'
DISTRIB_RELEASE='22.03.0-rc4'
DISTRIB_REVISION='06.18.2022'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION="OpenWrt 06.18.2022 by Kiddin'"
DISTRIB_TAINTS='busybox override'


uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: x86_64
Size: 7944
Filename: uclient-fetch_2021-05-14-6a6011df-1_x86_64.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1655016250

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20220515, libwolfssl5.3.0.ee39414e
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5020
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (wolfssl)
Installed-Time: 1655016250

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20220515, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5530
Filename: libustream-openssl20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20220515, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5341
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 52.69.239.207:443
Writing to stdout

-                      122k --:--:-- ETA
Download completed (125303 bytes)
3cf72aa19e3363c9d3cffb4436acee39462c5893


Node.js info:
Package: node
Version: v16.15.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: x86_64
Size: 11512561
Filename: node_v16.15.1-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1656938081

Node.js is placed at /usr/bin/node
Node.js version: v16.15.1


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: git-22.172.44972-9551f83
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch, ucode
Status: install user installed
Section: luci
Architecture: all
Size: 13155
Filename: luci-app-unblockneteasemusic_git-22.172.44972-9551f83_all.ipk
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Description: LuCI support for UnblockNeteaseMusic
Installed-Time: 1656938082

-rw-r--r--    1 root     root         282 Jul  4 20:46 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Jun 21 20:29 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        3.4K Jul  4 20:45 core
-rw-r--r--    1 root     root          41 Jul  4 20:45 core_local_ver
-rwxr-xr-x    1 root     root        5.0K Jun 21 20:29 debugging.sh
-rwxr-xr-x    1 root     root         348 Jun 21 20:29 log_check.sh
drwxr-xr-x    2 root     root        3.4K Jul  4 20:34 rules
-rwxr-xr-x    1 root     root        2.9K Jun 21 20:29 update.sh

config unblockneteasemusic 'config'
	option enable_flac '0'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option auto_update '1'
	option update_time '3'
	option advanced_mode '0'
	option local_vip '1'
	option enable '1'
	option music_source 'default'



UnblockNeteaseMusic Node.js info:
Git HEAD version: 3cf72aa19e3363c9d3cffb4436acee39462c5893
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      470.9K Jul  4 20:45 app.js
-rw-r--r--    1 root     root      415.5K Jul  4 20:45 bridge.js
-rw-r--r--    1 root     root         790 Jul  4 20:45 ca.crt
-rw-r--r--    1 root     root         843 Jul  4 20:45 server.crt
-rw-r--r--    1 root     root         359 Jul  4 20:45 server.key


Netease networking info:
< Location: http://m10.music.126.net/20220704212733/694792023c4b5132ccd2bb7cb2e284b8/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.121.4","115.236.118.34","59.111.19.33","59.111.160.195","39.105.175.128","182.92.170.253","47.100.127.239","39.105.63.80","118.24.63.156","193.112.159.225"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      25037/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      25037/node


Running info:
PROCD running status: running
25037 root      261m S    node /usr/share/unblockneteasemusic/core/app.js -a 0.0.0.0 -p 5200:5201 -e https://music.163.com


Firewall info:
netease_cloud_music nft rule file not found.

/usr/share/unblockneteasemusic/debugging.sh: line 68: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 70: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 72: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 74: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 76: nft: not found
Http Port pub access rule not found.

/usr/share/unblockneteasemusic/debugging.sh: line 78: nft: not found
Https Port pub access rule not found.

/usr/share/unblockneteasemusic/debugging.sh: line 80: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 82: nft: not found

dhcp-option=252,http://10.10.10.2:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic


Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2ZyZWV0eXN0Lm5mLm1pZ3UuY24vcHVibGljL3Byb2R1Y3Q5dGgvcHJvZHVjdDQ1LzIwMjIvMDUvMDcxNi8yMDA5JUU1JUI5JUI0MDYlRTYlOUMlODgyNiVFNiU5NyVBNSVFNSU4RCU5QSVFNSVCMCU5NCVFNiU5OSVBRSVFNiU5NiVBRi8lRTYlQTAlODclRTYlQjglODUlRTklQUIlOTglRTYlQjglODUvTVAzXzMyMF8xNl9TdGVyby82MDA1NDcwMTk2NDE2NTQ1Mi5tcDM=/33190502.mp3","br":320000,"size":8402236,"md5":"83f156776595d6a771c8b564a14ac312","code":200,"expi":1200,"type":"mp3","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0}],"code":200}
{"level":50,"time":1656939753499,"pid":25037,"hostname":"OPENWRT","scope":"provider/yt-dlp","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:2906:45)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async search (/usr/share/unblockneteasemusic/core/app.js:2911:21)\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:132:32)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:2307:23)\n    at async Promise.any (index 4)\n    at async match (/usr/share/unblockneteasemusic/core/app.js:2322:23)\n    at async Promise.all (index 0)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":50,"time":1656939753499,"pid":25037,"hostname":"OPENWRT","scope":"provider/match","name":"YtDlpNotInstalled","stack":"YtDlpNotInstalled: You must install \"yt-dlp\" before using the \"ytdlp\" source.\n    at getUrl (/usr/share/unblockneteasemusic/core/app.js:2906:45)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async search (/usr/share/unblockneteasemusic/core/app.js:2911:21)\n    at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:132:32)\n    at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:2307:23)\n    at async Promise.any (index 4)\n    at async match (/usr/share/unblockneteasemusic/core/app.js:2322:23)\n    at async Promise.all (index 0)","type":"Error","msg":"You must install \"yt-dlp\" before using the \"ytdlp\" source."}
{"level":30,"time":1656939753545,"pid":25037,"hostname":"OPENWRT","scope":"provider/match","audioId":33190502,"songName":"君のままで","url":"http://freetyst.nf.migu.cn/public/product9th/product45/2022/05/0716/2009%E5%B9%B406%E6%9C%8826%E6%97%A5%E5%8D%9A%E5%B0%94%E6%99%AE%E6%96%AF/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_320_16_Stero/60054701964165452.mp3","msg":"Replaced: [33190502] 君のままで"}

**Comment by showyoulove1990** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/29604166/177161087-90f46b67-f8e1-4b76-8a56-524b09a1dda3.png">

**Comment by 1715173329** [comment]
嗯哼？所以你的路由器安装了 firewall4 却没有 nftables？建议换个固件。

**Comment by showyoulove1990** [comment]
好的 我试试重装一下apk，一直使用的都是这个固件，之前可以正常使用，然后我更新了固件的内核之后，更新了unblock的核心，结果就成这样了

**Comment by showyoulove1990** [comment]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/29604166/177164459-6940a945-824d-4e8d-ab69-b7cff1f07b46.png">
版本貌似就是最新的

**Comment by showyoulove1990** [comment]
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/29604166/177294533-d3df4145-838c-4bd9-b306-b8c3ea710f8b.png">
试了一些，用这个版本是可以的，不能升级到git-22.172.44972-9551f83这个版本，只要升级就会提示fw4那个错误

**Comment by Xunflash** [comment]
同样的问题，kiddin9的固件，N1和树莓派4b都是和这个一样的报错，至今未修复。很奇怪
Firewall info:
netease_cloud_music nft rule file not found.

/usr/share/unblockneteasemusic/debugging.sh: line 77: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 79: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 81: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 83: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 85: nft: not found
Http Port pub access rule not found.

/usr/share/unblockneteasemusic/debugging.sh: line 87: nft: not found
Https Port pub access rule not found.

/usr/share/unblockneteasemusic/debugging.sh: line 89: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 91: nft: not found


Log is available at:
https://litter.catbox.moe/8c7j4s.txt
https://transfer.sh/bMgaLS/unm-debugging-output.txt
