### ISSUE TITLE
插件显示未启用

### ISSUE THREAD

**Issue by niepanshutian** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#167]
![Xnip2022-07-09_11-36-00](https://user-images.githubusercontent.com/52288156/178090058-2c7f60c7-45df-4f20-9e90-59ad18aaaa6d.jpg)
![Xnip2022-07-09_11-36-10](https://user-images.githubusercontent.com/52288156/178090060-016d3fa6-a9e0-4c08-ad29-db2213ff6a4e.jpg)

**Comment by 1715173329** [comment]
你还同时开两个插件？命令行输入 unm-debug 打印调试报告。

**Comment by niepanshutian** [comment]
我全部卸载重新安装一下试试吧，上面那个插件是固件集成的

**Comment by niepanshutian** [comment]
Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
{
	"kernel": "5.10.66",
	"hostname": "OpenWrt",
	"system": "ARMv8 Processor rev 0",
	"model": "FriendlyElec NanoPi R5S",
	"board_name": "friendlyelec,nanopi-r5s",
	"release": {
		"distribution": "1004",
		"version": "22.03.0-rc4",
		"revision": "06.28.2022",
		"target": "rockchip/armv8",
		"description": "OpenWrt 定制版 06.28.2022 by BDD"
	}
}


uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_generic
Size: 8257
Filename: uclient-fetch_2021-05-14-6a6011df-1_aarch64_generic.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1655093990

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20220515, libwolfssl5.3.0.ee39414e
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: install user installed
Section: libs
Architecture: aarch64_generic
Size: 5165
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-1_aarch64_generic.ipk
Description: ustream SSL Library (wolfssl)
Installed-Time: 1655093990

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20220515, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 5675
Filename: libustream-openssl20201210_2022-01-16-868fd881-1_aarch64_generic.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20220515, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 5491
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-1_aarch64_generic.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 198.18.5.70:443
Writing to stdout

Download completed (125303 bytes)
3cf72aa19e3363c9d3cffb4436acee39462c5893


Node.js info:
Package: node
Version: v16.15.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: aarch64_generic
Size: 11432572
Filename: node_v16.15.1-1_aarch64_generic.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1657339298

Node.js is placed at /usr/bin/node
Node.js version: v16.15.1


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: git-22.188.54892-d835ca0
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, UnblockNeteaseMusic, uclient-fetch, ucode
Status: install user installed
Section: luci
Architecture: all
Size: 13138
Filename: luci-app-unblockneteasemusic_git-22.188.54892-d835ca0_all.ipk
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Description: LuCI support for UnblockNeteaseMusic
Installed-Time: 1657339303

-rw-r--r--    1 root     root         383 Jul  9 11:33 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.1K Jul  7 23:14 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Jul  9 12:02 core
-rw-r--r--    1 root     root          41 Jul  9 12:02 core_local_ver
-rwxr-xr-x    1 root     root        5.0K Jul  7 23:14 debugging.sh
-rwxr-xr-x    1 root     root         348 Jul  7 23:14 log_check.sh
drwxr-xr-x    2 root     root        4.0K Jul  9 12:01 rules
-rwxr-xr-x    1 root     root        2.9K Jul  7 23:14 update.sh

config unblockneteasemusic
	option music_source 'default'
	option daemon_enable '1'
	option search_limit '1'
	option endpoint_enable '1'
	option force_best_quality '1'
	option auto_update '1'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option update_time '3'
	option advanced_mode '0'
	option enable '1'
	option local_vip '1'
	option enable_flac '1'



UnblockNeteaseMusic Node.js info:
Git HEAD version: 3cf72aa19e3363c9d3cffb4436acee39462c5893
Core version: 0.27.0-rc.6
-rw-r--r--    1 root     root      470.9K Jul  9 12:02 app.js
-rw-r--r--    1 root     root      415.5K Jul  9 12:02 bridge.js
-rw-r--r--    1 root     root         790 Jul  9 12:02 ca.crt
-rw-r--r--    1 root     root         843 Jul  9 12:02 server.crt
-rw-r--r--    1 root     root         359 Jul  9 12:02 server.key


Netease networking info:
< Location: http://m10.music.126.net/20220709122823/61f91c5c3077e947627e519d58731971/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["101.71.154.241","45.254.48.1","59.111.19.33","59.111.160.195","118.24.63.156","39.105.63.80","182.92.170.253","39.105.175.128","47.100.127.239","193.112.159.225"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
No instance found on port 5200.
No instance found on port 5201.


PROCD running info:
{
	
}


Succeeded in updating core.
Current core version: 3cf72aa19e3363c9d3cffb4436acee39462c5893.

**Comment by niepanshutian** [comment]
现在还是无法启动
插件

**Comment by 1715173329** [comment]
删除 `/etc/config/unblockneteasemusic` 文件，然后去 release 下载最新版本装上。

**Comment by niepanshutian** [comment]
是卸载重装吗？我是新手，不是很会。就是去系统，软件包里面卸载插件，然后重新安装吗？

**Comment by OpenWaygate** [comment]
> 是卸载重装吗？我是新手，不是很会。就是去系统，软件包里面卸载插件，然后重新安装吗？

`/etc/config/unblockneteasemusic` 是配置文件，我按照他说的删了后发现在 openwrt>服务 里找不到’解除网易云音乐播放限制‘，然后又下载 [luci-app-unblockneteasemusic_2.13-1_all.ipk](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/releases/download/v2.13-1/luci-app-unblockneteasemusic_2.13-1_all.ipk)，在 openwrt>系统>软件包>上传软件包 安装ipk，然而 openwrt>服务 还是没有’解除网易云音乐播放限制‘，虽然在 openwrt>系统>软件包>已安装 里有。

虽然我对他说的解决方法一脸蒙蔽，但我还是解决了，首先重装这个插件，然后
```
>>> cd /usr/share/unblockneteasemusic/core
>>> git clone https://github.com/UnblockNeteaseMusic/server.git .
>>> /etc/init.d/unblockneteasemusic start
```
如果openwrt不能装git，只要把那个repo里所有文件放到`/usr/share/unblockneteasemusic/core`下面就好了
