### ISSUE TITLE
劫持了错误的url

### ISSUE THREAD

**Issue by Haocen2004** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#170]
rt *.mihoyo.com貌似都劫持掉了 但只有游戏（启动器）会异常 用Chrome访问url查看证书正常
图为某mihoyo游戏用fiddle抓包报错
![image](https://user-images.githubusercontent.com/25221696/179238480-e01572ef-5692-4d79-a0a3-0939c48f3cf9.png)

**Comment by 1715173329** [comment]
这是由于他们同属一个 CDN，这种情况下无法解决，您可以选择关掉劫持并自行设定代理。

**Comment by gqbre** [comment]
同遇到了这个问题，iOS 新浪微博 APP 中的图片来自 https://wx3.sinaimg.cn/ 无法加载，通过浏览器访问提示如上证书问题。
