### ISSUE TITLE
Failed to download app.js

### ISSUE THREAD

**Issue by rineikou** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#172]
![image](https://user-images.githubusercontent.com/80826622/181050646-b13ce676-5418-4763-808e-a7492381bb29.png)

Local version: NOT FOUND, latest version: 7cbc0acff167f78748f69709894dd6a0747ccdbc.
Updating core...
Failed to download app.js.
Core Not Found, please download it before starting.

**Comment by 1715173329** [comment]
你网烂了，多试几次。
