### ISSUE TITLE
luci-app-unblockneteasemusic_3.0-3_javascript_all.ipk安装问题

### ISSUE THREAD

**Issue by chris6868** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#181]
luci-app-unblockneteasemusic_3.0-3_javascript_all.ipk安装后服务下面没有入口

**Comment by chris6868** [comment]
安装2.x版本都有入口显示，只有3.x没有

**Comment by chris6868** [comment]
OpenWrt R22.6.16

**Comment by 1715173329** [comment]
This is only for OpenWrt 19.07 or later __ONLY__.
