### ISSUE TITLE
解灰失败

### ISSUE THREAD

**Issue by superwong777** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#183]
核心和插件都是最新的
音乐客户端mac 2.8.9
调试报告：https://transfer.sh/VCMw9W/unm-debugging-output.txt

**Comment by 1715173329** [comment]
咪咕音源需要指定你自己的 cookie 才能使用。

**Comment by superwong777** [comment]
> 咪咕音源需要指定你自己的 cookie 才能使用。

我选了默认的也是一样的问题

**Comment by superwong777** [comment]
> 咪咕音源需要指定你自己的 cookie 才能使用。

这里是选了默认后的日志https://transfer.sh/GWAjlH/unm-debugging-output.txt
