### ISSUE TITLE
已安装证书 解灰失败 报错You must install "yt-dlp" before using the "ytdlp" source.

### ISSUE THREAD

**Issue by seven4x** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#187]
关键LOG：
Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL3Vwb3Mtc3otbWlycm9yY29zLmJpbGl2aWRlby5jb20vdWdheGNvZGUvbTE5MDgwNndzMjZnMTdnMnNjZHR3azIyYjk3c2FrMDAtMTkyay5tNGE_ZT1pZzhldXhaTTJyTmNOYmRsaG9Odk5DOEJxSkl6TmJmcVhCdkVxeFRFdG84QlRyTnZOMEd2VDkwVzVKWk1rWF9ZTjBNdlhnOGdORVY0TkM4eE5FVjROMDNlTjBCNXRabHFOeFRFdG84QlRyTnZOZVpWdUoxMEtqX2cyVUIwMkowbU4wQjV0WmxxTkNORXRvOEJUck52TkM3TVRYNTAyQzhmMmptTVFKNm1xRjJma2ExbXF4NmdxajBlTjBCNTk5TT0mdWlwaz01Jm5icz0xJmRlYWRsaW5lPTE2NjEzMTY2MDQmZ2VuPXBsYXl1cmx2MiZvcz1jb3NidiZvaT0zNzQ1NjcyMzgyJnRyaWQ9NDhmMDY3Y2ZhZGE5NDkwNmFkOTE1ZTk1ZDE4NTQ1ZGNCJm1pZD0wJnBsYXRmb3JtPXBjJnVwc2lnPTc4MDJiNWZiNDRlZGIzZmFhMDJlMDYzZGIxZjNkYWY1JnVwYXJhbXM9ZSx1aXBrLG5icyxkZWFkbGluZSxnZW4sb3Msb2ksdHJpZCxtaWQscGxhdGZvcm0mYnZjPXZvZCZuZXR0eXBlPTAmb3JkZXJpZD0wLDEmbG9nbz0wMDAwMDAwMA==/33190502.mp3","br":128000,"size":6351104,"md5":"32df659c0d7cf37d294c4e013bcd2e0b","code":200,"expi":1200,"type":"mp3","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at getUrl (/usr/share/unblockneteasemusic/core/app.js:269:81)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /usr/share/unblockneteasemusic/core/app.js:272:72
        at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)
        at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:201:17)
        at async Promise.any (index 4)
        at async module.exports (/usr/share/unblockneteasemusic/core/app.js:221:234)
        at async Promise.all (index 0)
ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at getUrl (/usr/share/unblockneteasemusic/core/app.js:269:81)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /usr/share/unblockneteasemusic/core/app.js:272:72
        at async CacheStorage.cache (/usr/share/unblockneteasemusic/core/app.js:13:22)
        at async getAudioFromSource (/usr/share/unblockneteasemusic/core/app.js:201:17)
        at async Promise.any (index 4)
        at async module.exports (/usr/share/unblockneteasemusic/core/app.js:221:234)
        at async Promise.all (index 0)
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m190806ws26g17g2scdtwk22b97sak00-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1661316604&gen=playurlv2&os=cosbv&oi=3745672382&trid=48f067cfada94906ad915e95d18545dcB&mid=0&platform=pc&upsig=7802b5fb44edb3faa02e063db1f3daf5&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000"

Log is available at:
https://litter.catbox.moe/h90odp.txt
https://transfer.sh/lewfiK/unm-debugging-output.txt

**Comment by seven4x** [comment]
手动安装 ytdlp 正常了

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":404,"expi":1200,"type":null,"gain":0.0,"fee":0,"uf":null,"payed":0,"flag":257,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2VwLnN5Y2RuLmt1d28uY24vY2NjOGVmZjdhNDBkNWRjMmE3OWM0NWQ2Y2NlYTU4N2QvNjMwNTk0NWEvcmVzb3VyY2UvczMvMC84NS8zMjcxMTI0MTY3LmZsYWM=/33190502.flac","br":999000,"size":30395622,"md5":"b416b2482c8adc65ba6ab01d98d5758d","code":200,"expi":1200,"type":"flac","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
INFO: (spawn) running yt-dlp -f 140 --dump-json ytsearch1:君のままで - azusa
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://ep.sycdn.kuwo.cn/ccc8eff7a40d5dc2a79c45d6ccea587d/6305945a/resource/s3/0/85/3271124167.flac"


Log is available at:
https://litter.catbox.moe/2wr4f9.txt
https://transfer.sh/7ht4HB/unm-debugging-output.txt

**Comment by seven4x** [comment]
只是周杰伦的歌 不知道为什么还是解锁不了
![image](https://user-images.githubusercontent.com/1982168/186311147-30956912-d1f3-406d-96f8-6c4d95981fe9.png)

**Comment by 1715173329** [comment]
不支持最新版本。

**Comment by 1715173329** [comment]
pull the latest version and it should works now

**Comment by seven4x** [comment]
大佬是指不支持网易云客户端最新版吗？ 支持什么版本我回退一下
当前版本是：Version 2.3.9 (882)

**Comment by seven4x** [comment]
但是web版本也不行 
![image](https://user-images.githubusercontent.com/1982168/186337832-315e7b7e-3e3e-4d95-b6ba-2752c552bed8.png)

**Comment by seven4x** [comment]
![image](https://user-images.githubusercontent.com/1982168/186340113-93147818-00a3-44af-aaab-70797173c813.png)
web后台更新失败

**Comment by seven4x** [comment]
然后这个 .lock 文件就得手动删掉 
![image](https://user-images.githubusercontent.com/1982168/186340366-993d085b-0ec2-4fe3-ab82-879dfce614b1.png)

**Comment by seven4x** [comment]
更新server之后还是灰的
https://litter.catbox.moe/xw18ui.txt
https://transfer.sh/XyrYD7/unm-debugging-output.txt

**Comment by 1715173329** [comment]
您安装的 ipk 文件并非由我们项目提供，请直接从本项目 releases 中下载最新版本安装。

**Comment by seven4x** [comment]
重新从release下载ipk安装完重启还是灰的，起来怪了，大佬有没有wiki设计文档，可以一起看下
Log is available at:
https://litter.catbox.moe/5ao2jr.txt
https://transfer.sh/yI6hjd/unm-debugging-output.txt

**Comment by 1715173329** [comment]
日志没有问题，降级客户端。

**Comment by seven4x** [comment]
找不到老的客户端，最后用了第三方客户端 https://github.com/trazyn/ieaseMusic 可以听灰歌曲了
