### ISSUE TITLE
成功编译进lede后没有luci界面，软件包显示有内核，编译也没有报错

### ISSUE THREAD

**Issue by chris7395328** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#188]
![image](https://user-images.githubusercontent.com/42464407/186563612-6768f2ef-00c4-4a56-b652-4579dd994b44.png)
![image](https://user-images.githubusercontent.com/42464407/186563951-5b24df6a-af23-409f-8baf-77ed4bcb02bd.png)

很奇怪，就是没有luci界面，make menuconfig的时候确实选择到了，也把大雕原本的网易插件取消选择了。

**Comment by 1715173329** [comment]
名字是小写不是大写。本项目只需要 luci 不需要安装所谓“核心”。lean 的 luci 不可使用 js 分支。
