### ISSUE TITLE
IOS端无法正常使用

### ISSUE THREAD

**Issue by RELemon** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#192]
情况：openwrt上部署无误，且电脑端使用软路由局域网ip和5200端口代理成功，PC端网易云音乐正常使用。

IPAD与IPHONE上安装CRT证书后仍然无效，后到设置——wifi——配置代理，设置后能成功启用。

灰色歌曲能够正常解锁替换音源，但是无法加载歌词，且无法正常使用网易云的搜索功能。

尝试过回退网易云音乐和网易云音乐HD的旧版本，还是一样。

Log is available at:
https://litter.catbox.moe/kfgu8q.txt
https://transfer.sh/SpT9bT/unm-debugging-output.txt

**Comment by 1715173329** [comment]
unblockneteasemusic/server#845

**Comment by RELemon** [comment]
我的操作：

①根据[https://github.com/UnblockNeteaseMusic/server/commit/710888321df5d4d5d88600305699ea6c765ec77c](url)，我用winscp修改了/usr/share/UnblockNeteaseMusic/precompiled/app.js里面的配置。
②在系统——启动项里重启了unblockneteasemusic。
③终端同样进行配置代理：软路由ip：5200

问题仍然存在：所有歌曲无法加载歌词、歌手页面无法加载专辑内容

**Comment by llllcccjjj** [comment]
win正常，我的也是iphone不行了

**Comment by haohaoget** [comment]
我的iPadOS也是这样，Android端我用的7.x的修改版也是用代理就会报网络错误，但是可以解锁歌单的灰色歌曲，无法搜索和显示歌手专辑及mv

**Comment by haohaoget** [comment]
> 我的iPadOS也是这样，Android端我用的7.x的修改版也是用代理就会报网络错误，但是可以解锁歌单的灰色歌曲，无法搜索和显示歌手专辑及mv

对了歌词也无法显示

**Comment by lvmingye523** [comment]
和你一样的问题，我是一开始可以用的，然后过几天突然变成你这样，也很迷。。。

**Comment by jackey-jiang** [comment]
同样的问题,可以已解锁歌单的灰色歌曲,无法搜索和显示歌手专辑以及歌词

**Comment by msylgj** [comment]
尝试按照https://github.com/UnblockNeteaseMusic/server/pull/840的变更修改本地app.js后再测试看下，测试情况请在此反馈。

**Comment by haohaoget** [comment]
> 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。

谢谢大佬指点修改后已经可以正常使用了

**Comment by lvmingye523** [comment]
> 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。

我的核心就是9e71a77版，本身已经加过这段代码了。目前还是不行

**Comment by jackey-jiang** [comment]
> 试情况请在

大佬，那对于使用docker的用户应该如何处理呢？

**Comment by msylgj** [comment]
> > 试情况请在
> 
> 
> 
> 大佬，那对于使用docker的用户应该如何处理呢？

自己fork出镜像吧

**Comment by jackey-jiang** [comment]
> 

小哥,我跟你同样的问题,但目前仍旧没能解决,你是用的surge?

**Comment by jackey-jiang** [comment]
> > > 试情况请在
> > 
> > 
> > 大佬，那对于使用docker的用户应该如何处理呢？
> 
> 自己fork出镜像吧

嗯,今早自己出了镜像试了下,还是不得,后来发现你们dockerhub 更新了,也尝试了下,还是不得



<img width="1034" alt="image" src="https://user-images.githubusercontent.com/10288803/191884710-59e30965-5729-4d4c-93af-9fc578e77ddc.png">

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/10288803/191884753-37f76a95-c930-489d-8d60-e96b18e8cc58.png">

**Comment by jackey-jiang** [comment]
> 

修改后,iOS可以了? 我今早试了下 还是不可以, 你是用的surge么?  mac完美,但iOS 歌词和搜索都不行
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/10288803/191884949-627489e8-2f1c-40d3-8b7e-2dd473883560.png">

**Comment by jackey-jiang** [comment]
> > 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。
> 
> 谢谢大佬指点修改后已经可以正常使用了

修改后,iOS可以了? 我今早试了下 还是不可以, 你是用的surge么?  mac完美,但iOS 歌词和搜索都不行
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/10288803/191884949-627489e8-2f1c-40d3-8b7e-2dd473883560.png">

**Comment by haohaoget** [comment]
> > > 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。
> > 
> > 
> > 谢谢大佬指点修改后已经可以正常使用了
> 
> 修改后,iOS可以了? 我今早试了下 还是不可以, 你是用的surge么? mac完美,但iOS 歌词和搜索都不行 <img alt="image" width="1017" src="https://user-images.githubusercontent.com/10288803/191884949-627489e8-2f1c-40d3-8b7e-2dd473883560.png">

这个pr并没有被使用，请你自己修改Accept-Encoding为gzip, deflate

**Comment by jackey-jiang** [comment]
> > > > 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。
> > > 
> > > 
> > > 谢谢大佬指点修改后已经可以正常使用了
> > 
> > 
> > 修改后,iOS可以了? 我今早试了下 还是不可以, 你是用的surge么? mac完美,但iOS 歌词和搜索都不行 <img alt="image" width="1017" src="https://user-images.githubusercontent.com/10288803/191884949-627489e8-2f1c-40d3-8b7e-2dd473883560.png">
> 
> 这个pr并没有被使用，请你自己修改Accept-Encoding为gzip, deflate

因为今早使用的是最新的代码 进行构建的镜像,以下代码已经有了,所以,现在不知道哪里的问题
<img width="739" alt="image" src="https://user-images.githubusercontent.com/10288803/191887008-4a6820c1-448a-4d12-99c3-83b542b70fce.png">

**Comment by RELemon** [comment]
> 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。

是在src/hook.js中，增加gzip吗？

我修改后问题仍然存在。

![image](https://user-images.githubusercontent.com/112569977/191958210-afb2146d-9950-4705-a501-87f5c2bc5c71.png)

**Comment by 1715173329** [comment]
fixed.

**Comment by RELemon** [comment]
> > 尝试按照 [UnblockNeteaseMusic/server#840](https://github.com/UnblockNeteaseMusic/server/pull/840) 的变更修改本地app.js后再测试看下，测试情况请在此反馈。
> 
> 是在src/hook.js中，增加gzip吗？
> 
> 我修改后问题仍然存在。
> 
> ![image](https://user-images.githubusercontent.com/112569977/191958210-afb2146d-9950-4705-a501-87f5c2bc5c71.png)

又尝试了一下，按照这样更改，已经可以正常使用了。
