### ISSUE TITLE
macos失效。macOS版本12.5，音乐app版本2.3.9

### ISSUE THREAD

**Issue by lvmingye523** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#193]
iPhone上添加完证书完美使用，但是macos添加完证书只能进专辑页面双击播放提示无法播放。
<img width="843" alt="截屏2022-09-18 15 50 49" src="https://user-images.githubusercontent.com/42700007/190891806-c83acd75-64a1-44ec-b362-1dcb93e7cbb1.png">

**Comment by Haleclipse** [comment]
https://github.com/UnblockNeteaseMusic/server/issues/823#issuecomment-1243896418

**Comment by 1715173329** [comment]
Fixed
