### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by linxiaolulu** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#196]
Collected errors:
 * opkg_download: Failed to download https://openwrt.proxy.ustclug.org/snapshots/targets/ar71xx/nand/packages/Packages.gz, wget returned 8.
 * 
![image](https://user-images.githubusercontent.com/88550402/195974905-fdd7dbbe-3e7a-44d0-a691-a85d55266e2c.png)

**Comment by 1715173329** [comment]
本项目已不再支持您的架构与设备。

**Comment by linxiaolulu** [comment]
请问以往版本可以支持嘛
