### ISSUE TITLE
安卓版本客户端为什么不支持8.0.20以后？

### ISSUE THREAD

**Issue by feilongproject** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#197]
readme里面指出，在安卓上的网易云音乐客户端不能超过8.0.20，我想问下这是因为什么原因？是否是因为之后版本不支持用户证书？root了之后使用系统证书可以支持8.0.20以后版本么？

**Comment by 1715173329** [comment]
支持了。

**Comment by A-Cepheus** [comment]
安卓在什么操作的情况下支持呢，最新的8.8.50提示“资源不存在”

**Comment by 1715173329** [comment]
信任证书。
