### ISSUE TITLE
开启lean固件中的flow offloading功能会和解锁网易冲突

### ISSUE THREAD

**Issue by lvmingye523** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#200]
同时开启时，app端首页会有很大机率专辑空白，动态中的头像也会显示不出，但是不影响解锁歌曲。以前小包性能提升的sfe，现在lean改成flow offloading了

**Comment by 1715173329** [comment]
确定是 flow offloading 而不是 mtknat 或者 sfe？本人没有遇到这种问题，也无法对 lean 的主线固件提供任何保证。

**Comment by lvmingye523** [comment]
> 确定是 flow offloading 而不是 mtknat 或者 sfe？本人没有遇到这种问题，也无法对 lean 的主线固件提供任何保证。

my fault

**Comment by 1715173329** [comment]
flow offloading 就目前而言没什么问题，但可能与其他某些插件冲突。btw 请务必信任证书。
