### ISSUE TITLE
收集数据。。

### ISSUE THREAD

**Issue by lvmingye523** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#202]
把启动按钮关了，显示收集数据，点开启动按钮，显示插件未启动，log日志里显示Failed to check latest core version, please try again later.Core Not Found, please download it before starting.手动删除核心，在手动更新后提示已经升级到最新核心。已把lean固件里的其他功能全部关闭。
<img width="991" alt="截屏2022-10-28 23 07 27" src="https://user-images.githubusercontent.com/42700007/198673017-8fa319b2-544a-410a-ba1e-1145cebe4c27.png">
<img width="839" alt="截屏2022-10-28 23 16 33" src="https://user-images.githubusercontent.com/42700007/198673025-0081a09a-8a4e-4cbb-a560-81d6eff03a65.png">

**Comment by lvmingye523** [comment]
系统日志：
Fri Oct 28 23:27:02 2022 daemon.err uhttpd[1105]: Failed to parse json data: unexpected end of data
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: /usr/lib/lua/luci/dispatcher.lua:474: Failed to execute call dispatcher target for entry '/admin/services/unblockneteasemusic/status'.
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: The called action terminated with an exception:
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: /usr/lib/lua/luci/controller/unblockneteasemusic.lua:27: attempt to index field 'instances' (a nil value)
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: stack traceback:
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: 	[C]: in function 'assert'
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: 	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
Fri Oct 28 23:27:04 2022 daemon.err uhttpd[1105]: 	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: /usr/lib/lua/luci/dispatcher.lua:474: Failed to execute call dispatcher target for entry '/admin/services/unblockneteasemusic/status'.
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: The called action terminated with an exception:
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: /usr/lib/lua/luci/controller/unblockneteasemusic.lua:27: attempt to index field 'instances' (a nil value)
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: stack traceback:
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: 	[C]: in function 'assert'
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: 	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
Fri Oct 28 23:27:08 2022 daemon.err uhttpd[1105]: 	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>
Fri Oct 28 23:27:11 2022 daemon.err uhttpd[1105]: /usr/lib/lua/luci/dispatcher.lua:474: Failed to execute call dispatcher target for entry '/admin/services/unblockneteasemusic/status'.
Fri Oct 28 23:27:11 2022 daemon.err uhttpd[1105]: The called action terminated with an exception:
Fri Oct 28 23:27:11 2022 daemon.err uhttpd[1105]: /usr/lib/lua/luci/controller/unblockneteasemusic.lua:27: attempt to index field 'instances' (a nil value)

**Comment by 1715173329** [comment]
网烂了，获取不到最新版本，luci 的显示有 bug。
需要更换梯子
