### ISSUE TITLE
ios端图片加载有问题。

### ISSUE THREAD

**Issue by lvmingye523** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#203]
插件运行前2个小时左右，ios和mac端都正常，2个小时后后ios端大部分带图片的都显示不出但依旧能解锁，重新运行插件后一切都正常，过一段时间又图片加载不出，log日志无异常，mac端使用正常无以上情况。

**Comment by lvmingye523** [comment]
![IMG_66DBDAB552E2-1](https://user-images.githubusercontent.com/42700007/198818873-7afd26ed-4258-4fbc-bad2-b170c68f049f.jpeg)
![IMG_32F4E283C9BC-1](https://user-images.githubusercontent.com/42700007/198818879-f82d5c52-553f-4e4d-af62-ca29df217de7.jpeg)

**Comment by cclucky1** [comment]
我也出现了这个问题请问你解决了嘛

**Comment by 1715173329** [comment]
可能图片资源被 unm 代理了，但是目前 unm 不能很好处理不属于自己的请求。
