### ISSUE TITLE
网络连接失败请重试

### ISSUE THREAD

**Issue by allen-wong** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#204]
日志：

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.10.146",
	"hostname": "OpenWrt",
	"system": "Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz",
	"model": "QEMU Standard PC (Q35 + ICH9, 2009)",
	"board_name": "qemu-standard-pc-q35-ich9-2009",
	"rootfs_type": "ext4",
	"release": {
		"distribution": "OpenWrt",
		"version": "22.03.2",
		"revision": "r19803-9a599fee93",
		"target": "x86/64",
		"description": "OpenWrt 22.03.2 r19803-9a599fee93"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: x86_64
Size: 7944
Filename: uclient-fetch_2021-05-14-6a6011df-1_x86_64.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1665185696

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-2
Depends: libc, libubox20220515, libwolfssl5.5.1.ee39414e
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5020
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-2_x86_64.ipk
Description: ustream SSL Library (wolfssl)
Installed-Time: 1665185696

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-2
Depends: libc, libubox20220515, libopenssl1.1
Provides: libustream-openssl
Status: install user not-installed
Section: libs
Architecture: x86_64
Size: 5533
Filename: libustream-openssl20201210_2022-01-16-868fd881-2_x86_64.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-2
Depends: libc, libubox20220515, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5335
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-2_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 192.30.255.117:443
Writing to stdout

Download completed (124373 bytes)
d8c4c9175a3d50d4b2a29d1c415f5cf1fdf51d84

Node.js info:
Package: node
Version: v16.18.0-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: x86_64
Size: 11577469
Filename: node_v16.18.0-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1667282984

Node.js is placed at /usr/bin/node
Node.js version: v16.18.0

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: git-23.303.44828-ba42a9a
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch, ucode, UnblockNeteaseMusic
Status: install user installed
Section: luci
Architecture: all
Size: 14318
Filename: luci-app-unblockneteasemusic_git-23.303.44828-ba42a9a_all.ipk
Conffiles:
 /etc/config/unblockneteasemusic ce81d716cb16ef5b4716939d69666644d6a8fcdd7f48d454b099bef546c51486
Description: LuCI support for UnblockNeteaseMusic (JavaScript)
Installed-Time: 1667282986

-rw-r--r--    1 root     root         335 Nov  1 15:24 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.4K Oct 30 20:27 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Nov  1 14:29 core
-rw-------    1 root     root          41 Nov  1 14:29 core_local_ver
-rwxr-xr-x    1 root     root        5.1K Oct 30 20:27 debugging.sh
-rwxr-xr-x    1 root     root         348 Oct 30 20:27 log_check.sh
drwxr-xr-x    2 root     root        4.0K Nov  1 14:09 rules
-rwxr-xr-x    1 root     root        3.2K Oct 30 20:27 update.sh

config unblockneteasemusic 'config'
	option follow_source_order '0'
	option local_vip '0'
	option disable_upgrade_check '1'
	option replace_music_source 'dont_replace'
	option auto_update '1'
	option update_time '3'
	option advanced_mode '0'
	option enable '1'
	option enable_flac '1'
	option music_source 'kugou kuwo migu bilibili'

UnblockNeteaseMusic Node.js info:
Git HEAD version: d8c4c9175a3d50d4b2a29d1c415f5cf1fdf51d84
Core version: 0.27.0
-rw-------    1 root     root      322.4K Nov  1 14:29 app.js
-rw-------    1 root     root          85 Nov  1 14:29 app.js.LICENSE.txt
-rw-------    1 root     root      270.8K Nov  1 14:29 bridge.js
-rw-------    1 root     root          85 Nov  1 14:29 bridge.js.LICENSE.txt
-rw-------    1 root     root         790 Nov  1 14:29 ca.crt
-rw-------    1 root     root         843 Nov  1 14:29 server.crt
-rw-------    1 root     root         359 Nov  1 14:29 server.key

Netease networking info:
< Location: http://m10.music.126.net/20221101160053/18afc6472e918ac49a4b4ca823b79acc/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.121.4","115.236.118.34","59.111.160.195","59.111.19.33","39.105.63.80","47.100.127.239","193.112.159.225","182.92.170.253","118.24.63.156","39.105.175.128"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      17510/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      17510/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"unblockneteasemusic": {
				"running": true,
				"pid": 17510,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"0.0.0.0",
					"-p",
					"5200:5201",
					"-o",
					"kugou",
					"kuwo",
					"migu",
					"bilibili",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"DISABLE_UPGRADE_CHECK": "true",
					"ENABLE_FLAC": "true",
					"LOG_FILE": "/tmp/unblockneteasemusic.log",
					"LOG_LEVEL": "info",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:

table inet fw4 {
	set acl_neteasemusic_http {
		type ipv4_addr
		flags interval
	}
}

table inet fw4 {
	set acl_neteasemusic_https {
		type ipv4_addr
		flags interval
	}
}

table inet fw4 {
	set local_addr {
		type ipv4_addr
		flags interval
		elements = { 0.0.0.0/8, 10.0.0.0/8,
			     100.64.0.0/10, 127.0.0.0/8,
			     169.254.0.0/16, 172.16.0.0/12,
			     192.0.0.0/24, 192.0.2.0/24,
			     192.31.196.0/24, 192.52.193.0/24,
			     192.88.99.0/24, 192.168.0.0/16,
			     192.175.48.0/24, 198.18.0.0/15,
			     198.51.100.0/24, 203.0.113.0/24,
			     224.0.0.0/4, 240.0.0.0-255.255.255.255 }
	}
}

table inet fw4 {
	set neteasemusic {
		type ipv4_addr
		flags interval
		elements = { 39.105.63.80, 39.105.175.128,
			     47.100.127.239, 59.111.19.33,
			     59.111.160.195, 59.111.160.197,
			     59.111.181.35, 59.111.181.38,
			     59.111.181.60, 61.136.232.151,
			     61.136.232.152, 61.136.232.153,
			     61.136.232.155, 115.236.118.33,
			     115.236.118.34, 115.236.121.1,
			     115.236.121.4, 118.24.63.156,
			     182.92.170.253, 193.112.159.225,
			     223.252.199.66, 223.252.199.67 }
	}
}

Http Port pub access rule not found.

Https Port pub access rule not found.

table inet fw4 {
	chain netease_cloud_music {
		type nat hook prerouting priority filter - 1; policy accept;
		meta l4proto tcp ip daddr @neteasemusic jump netease_cloud_music_redir
	}
}

table inet fw4 {
	chain netease_cloud_music_redir {
		ip daddr @local_addr return
		ip saddr @acl_neteasemusic_http accept
		ip saddr @acl_neteasemusic_https accept
		tcp dport 80 counter packets 29 bytes 1508 redirect to :5200
		tcp dport 443 counter packets 192 bytes 9984 redirect to :5201
	}
}

dhcp-option=252,http://192.168.1.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL3Vwb3Mtc3otbWlycm9yY29zLmJpbGl2aWRlby5jb20vdWdheGNvZGUvbTE5MDgwNndzMjZnMTdnMnNjZHR3azIyYjk3c2FrMDAtMTkyay5tNGE_ZT1pZzhldXhaTTJyTmNOYmRsaG9Odk5DOEJxSkl6TmJmcVhCdkVxeFRFdG84QlRyTnZOMEd2VDkwVzVKWk1rWF9ZTjBNdlhnOGdORVY0TkM4eE5FVjROMDNlTjBCNXRabHFOeFRFdG84QlRyTnZOZVpWdUoxMEtqX2cyVUIwMkowbU4wQjV0WmxxTkNORXRvOEJUck52TkM3TVRYNTAyQzhmMmptTVFKNm1xRjJma2ExbXF4NmdxajBlTjBCNTk5TT0mdWlwaz01Jm5icz0xJmRlYWRsaW5lPTE2NjcyOTUzNTMmZ2VuPXBsYXl1cmx2MiZvcz1jb3NidiZvaT0xODczNzcyOTI1JnRyaWQ9OWY5ZDhjY2VjZjRlNGM3ZjhmMzFhMmNiZTFjOGJiNmVCJm1pZD0wJnBsYXRmb3JtPXBjJnVwc2lnPWRhNTY3MjQzYTQ5ZjQ3NDg3NjFiNDcxNjZmZDhjNDcyJnVwYXJhbXM9ZSx1aXBrLG5icyxkZWFkbGluZSxnZW4sb3Msb2ksdHJpZCxtaWQscGxhdGZvcm0mYnZjPXZvZCZuZXR0eXBlPTAmb3JkZXJpZD0wLDEmbG9nbz0wMDAwMDAwMA==/33190502.mp3","br":128000,"size":6351104,"md5":"dccbd9e5bcad8afc204347e74c29781c","code":200,"expi":1200,"type":"mp3","gain":0,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m190806ws26g17g2scdtwk22b97sak00-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1667295353&gen=playurlv2&os=cosbv&oi=1873772925&trid=9f9d8ccecf4e4c7f8f31a2cbe1c8bb6eB&mid=0&platform=pc&upsig=da567243a49f4748761b47166fd8c472&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,1&logo=00000000"

Log is available at:
https://litter.catbox.moe/jg0lsk.txt
https://transfer.sh/KzPdJD/unm-debugging-output.txt

云音乐客户端版本：2.10.5（Build:200451）(Patch:1:bc9f526)

异常描述：客户端启动后弹出提示

**Comment by 1715173329** [comment]
1. 安装这个版本 https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/suites/8810098026/artifacts/400841329
2. 请确保已经信任根证书
3. 最新版 PC 网易云音乐可能存在 bug，请卸载后重新安装

**Comment by allen-wong** [comment]
重装上述luci-app问题依旧；
根证书导入windows问题依旧；
重新PC客户端问题解决；

**Comment by allen-wong** [comment]
关闭客户端并重启，问题依旧；
重装PC客户端第一次启动也会弹出提示但不影响使用。

**Comment by superwong777** [comment]
INFO: (app) HTTP Server running @ http://0.0.0.0:5200/
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201/

我这里也是提示 0.0.0.0

**Comment by allen-wong** [comment]
<img width="1130" alt="2022-11-12_110658" src="https://user-images.githubusercontent.com/9129228/201453799-e4aa0b28-e063-44fc-b4dc-01c2e6538d32.png">
