### ISSUE TITLE
插件过段时间会变成未运行状态，还有编译进去的插件，从2.13升级到3.几版本之后，服务里面选项会直接消失

### ISSUE THREAD

**Issue by RubiksCubei** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#206]
插件过段时间会变成未运行状态，还有编译进去的插件，从2.13升级到3.几版本之后，服务里面选项会直接消失

**Comment by 1715173329** [comment]
未运行可能是爆内存了，3.x 是给 js luci 用的

**Comment by yuehongcheng** [comment]
> 未运行可能是爆内存了，3.x 是给 js luci 用的

好吧。设备内存是比较小，只有2GB，但插件果断时间会变成未运行怎么办呢？  还有今天点任何歌都无法播放，一直无法加载。

**Comment by 1715173329** [comment]
2G RAM 已然足够，或许是你 host 上存在其它问题 kill 了 node 进程，无法算命。
workaround 是更改 init 第 162 行，respawn 后追加参数 300 5 0，允许无限次重启。

**Comment by yuehongcheng** [comment]
> 2G RAM 已然足够，或许是你 host 上存在其它问题 kill 了 node 进程，无法算命。 workaround 是更改 init 第 162 行，respawn 后追加参数 300 5 0，允许无限次重启。

请问是修改这个地方吗？
![屏幕截图 2022-11-04 090618](https://user-images.githubusercontent.com/48173817/199863401-8037d08d-8072-4cde-8bb3-8eb12c08bdc4.jpg)
我已经修改过了。不过今天早上起来看了一眼，发现插件还是自动未运行了。
![屏幕截图 2022-11-04 090220](https://user-images.githubusercontent.com/48173817/199863456-84d9681c-785a-4b3d-9d76-c7691f7dc6ea.jpg)

**Comment by 1715173329** [comment]
看看系统日志

**Comment by Saxon-Sun** [comment]
昨晚停电 早上来电后发现UnblockNeteaseMusic起不来了 同样情况     好像dnsmasq和UnblockNeteaseMusic冲突了  导致dnsmasq无法启动，整个局域网里dns都无法解析了 关了UnblockNeteaseMusic才正常 等dnsmasq起来了再开UnblockNeteaseMusic就正常了    
[syslog.txt](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/files/10118652/syslog.txt)

**Comment by saltedfisholdxu** [comment]
想了解一下是不是必须通网才能正常启动？
我也是无限重启 虚拟机内存4G 用的2.13版本 以NodeJS启动

**Comment by 1715173329** [comment]
> 想了解一下是不是必须通网才能正常启动？我只是在此做测试环境，并没有计划通网 我也是无限重启 虚拟机内存4G 用的2.13版本 以NodeJS启动

必须通网，启动的时候会查 DNS。

**Comment by a393310872** [comment]
以前遇到过类似问题.后来把自动更新关闭就好了.大概率是无法正常更新内核.导致的.把那个升级失败保留内核勾上

**Comment by RubiksCubei** [comment]
> 看看系统日志

最近重新编译了新版系统，插件还是会变成未运行状态。
系统日志：[syslog.txt](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/files/12024173/syslog.txt)

**Comment by 1715173329** [comment]
网络问题，无解。
