### ISSUE TITLE
与dnsmasq造成冲突导致dnsmasq不运行

### ISSUE THREAD

**Issue by sheip9** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#210]
![NVUI3XH93EYHADOO40S_)`3](https://user-images.githubusercontent.com/53911290/204136243-39377fbf-e902-4dd0-bd76-8d92c0da98bb.png)

**Comment by sheip9** [comment]
系统日志里边dnsmasq相关的日志只有图中那两行反复刷

**Comment by 1715173329** [comment]
unm-debug
输入上面的命令，把最后的链接发出来

**Comment by sheip9** [comment]
https://transfer.sh/UtTBF3/unm-debugging-output.txt

**Comment by 1715173329** [comment]
a small typo error but breaks everything ;(
