### ISSUE TITLE
似乎还是会导致dnsmasq出现问题

### ISSUE THREAD

**Issue by ssrubsd** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#211]
![屏幕截图 2022-12-06 201308](https://user-images.githubusercontent.com/59917319/205910111-85f02d69-6b05-432f-83c4-90a95396e385.png)

https://transfer.sh/qqRXbQ/unm-debugging-output.txt

**Comment by 1715173329** [comment]
下载我们官方提供的 ipk 包安装。
