### ISSUE TITLE
用了插件之后，还是有一一些问题

### ISSUE THREAD

**Issue by xulin988** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#214]
用了插件之后，还是有一一些问题：
1. 有些歌曲还是无法下载，提示：该资源仅限音乐包用户下载，点击开通；
2. 有些歌曲还是无法下载，提示：下载失败，无损音质需付费下载；
3. 有些歌曲还是无法下载，提示：该资源需付费下载；
4. 有些歌曲还是无法下载，提示：下载失败，网络异常；
5. 有些歌曲，原先只能试听，现在虽然没了VIP标识和试听标识，但是直接提示：“播放失败，网络不给力，无法继续播放。”

**Comment by 1715173329** [comment]
信任证书了吗？

**Comment by xulin988** [comment]
> 信任证书了吗？

证书就是安装吧？安装过了，我进去看了一下，好像没有让我点信任的地方。

现在好像都不行了，我两个礼拜前提问的时候，还是有很多原本不能下载的歌曲可以下载的，比如这届世界杯的那首主题神曲，后面重装了openwrt，灰色歌曲还是灰的，下载更别说了，原先以为是IPV6的原因（IPV6我已经用了一两年了），因为ping music.163.com得到的是IPV6的地址，强制用ping -4 music.163.com得到IPV4的地址112.13.122.4，ping 112.13.122.4也能ping的通，但是网页输入112.13.122.4直接访问，访问不了，提示403 forbidden，后面我重装openwrt，不添加IPV6的接口，但是还是这样，就相当于没有任何作用，我以为是最新的3.1-3版本有问题，装回3.1-2，还是一样，没有任何作用。

还有个奇怪的现象，在openwrt的插件里面，点下载证书，直接下载到是一个文件，不会提示下载的是一个描述文件，我是在github这边下载的证书安装的。

![WeChat Image_20221227205143](https://user-images.githubusercontent.com/44314392/209669460-1e4a0985-93de-4d41-95ca-fa378d71e59b.jpg)

**Comment by xulin988** [comment]
补充一句，刚刚windws电脑端试了一下，是可用的，至少tukoh taka和wellerman是可以下载的，IOS手机上不行，最新IOS16.2系统

**Comment by xulin988** [comment]
在设置——通用——关于本机——证书信任设置，找到信任证书的地方了，也已经信任证书了，但是搜周杰伦，点单曲，下面的歌曲还是灰的，当然下载什么的就更没有了

**Comment by xulin988** [comment]
刚刚用一台三星的S9+手机测试，也是不行的，周杰伦，单曲，下面好多歌都还是灰色的

**Comment by xianren78** [comment]
/etc/init.d/unblockneteasemusic
1，uclient-fetch改成wget，两处
2，大约296-298三行注释掉 ipset destroy
3，/etc/init.d/unblockneteasemusic restart 执行5次以上
4，再次测试

另外提供点op双栈开启ipv6，如何使用这个解锁的思路，环境: op+openclash+smartdns
使用smartdns禁用网易云音乐域名的ipv6解析
address /music.163.com/#6
address /.music.163.com/#6
address /music.httpdns.c.163.com/#6
address /mam.netease.com/#6
address /.netease.com/#6

插件主体功能是没问题的，最重要的是给ipset neteasemusic里添加合适的ip。
我遇到的解锁失败一般都是本地有两个以上的ip，随机解析。
如果主路由开启ipv6后，会用v6地址，插件不能劫持，也会失败。

**Comment by 1715173329** [comment]
iptables 版无法处理 v6 请求，之前的一些兼容性问题应该已在最新版本得到修复。
