### ISSUE TITLE
openwrt系统日志中一直报错，iOS中无法解锁

### ISSUE THREAD

**Issue by MIAOBUSI** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#220]
openwrt系统日志：
Sun Dec 25 20:49:45 2022 daemon.info netdata[10568]: RRDSET: chart name 'net_mtu.utun' on host 'MIAOHOME' already exists.
Sun Dec 25 20:49:45 2022 daemon.info netdata[10568]: RRDSET: chart name 'net_packets.utun' on host 'MIAOHOME' already exists.
Sun Dec 25 20:50:00 2022 cron.err crond[14118]: USER root pid 16252 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 20:55:00 2022 cron.err crond[14118]: USER root pid 30987 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:00:00 2022 cron.err crond[14118]: USER root pid 8945 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:05:00 2022 cron.err crond[14118]: USER root pid 22149 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:10:00 2022 cron.err crond[14118]: USER root pid 31150 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:15:00 2022 cron.err crond[14118]: USER root pid 6229 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:20:00 2022 cron.err crond[14118]: USER root pid 13945 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:25:00 2022 cron.err crond[14118]: USER root pid 21447 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:30:00 2022 cron.err crond[14118]: USER root pid 28964 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:31:05 2022 daemon.info netdata[10568]: Deleting chart 'net_drops.utun' ('net_drops.utun') from disk...
Sun Dec 25 21:31:05 2022 daemon.info netdata[10568]: Deleting chart header file '/var/cache/netdata/net_drops.utun/main.db'.
Sun Dec 25 21:31:05 2022 daemon.info netdata[10568]: Deleting dimension file '/var/cache/netdata/net_drops.utun/inbound.db'.
Sun Dec 25 21:31:05 2022 daemon.info netdata[10568]: Deleting dimension file '/var/cache/netdata/net_drops.utun/outbound.db'.
Sun Dec 25 21:31:05 2022 daemon.info netdata[10568]: Deleting empty directory '/var/cache/netdata/net_drops.utun'
Sun Dec 25 21:35:00 2022 cron.err crond[14118]: USER root pid 6159 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:40:00 2022 cron.err crond[14118]: USER root pid 18778 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:45:00 2022 cron.err crond[14118]: USER root pid 26128 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:50:00 2022 kern.notice kernel: [92567.031311] EXT4-fs (sda1): error count since last fsck: 25
Sun Dec 25 21:50:00 2022 kern.notice kernel: [92567.031747] EXT4-fs (sda1): initial error at time 1671535594: htree_dirblock_to_tree:1072: inode 2: block 1
Sun Dec 25 21:50:00 2022 kern.notice kernel: [92567.032413] EXT4-fs (sda1): last error at time 1671536482: htree_dirblock_to_tree:1072: inode 2: block 1
Sun Dec 25 21:50:00 2022 cron.err crond[14118]: USER root pid 1214 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 21:55:00 2022 cron.err crond[14118]: USER root pid 8724 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:00:00 2022 cron.err crond[14118]: USER root pid 23376 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:05:00 2022 cron.err crond[14118]: USER root pid 31264 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:10:00 2022 cron.err crond[14118]: USER root pid 13246 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:15:00 2022 cron.err crond[14118]: USER root pid 20785 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:20:00 2022 cron.err crond[14118]: USER root pid 28290 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:22:34 2022 cron.err crond[2012]: crond (busybox 1.35.0) started, log level 8
Sun Dec 25 22:25:00 2022 cron.err crond[2012]: USER root pid 3143 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:26:51 2022 cron.err crond[4629]: crond (busybox 1.35.0) started, log level 8
Sun Dec 25 22:27:06 2022 daemon.info avahi-daemon[3200]: Interface utun.IPv6 no longer relevant for mDNS.
Sun Dec 25 22:27:06 2022 daemon.info avahi-daemon[3200]: Leaving mDNS multicast group on interface utun.IPv6 with address fe80::a9c4:69af:74a6:3c0d.
Sun Dec 25 22:27:06 2022 daemon.info avahi-daemon[3200]: Interface utun.IPv4 no longer relevant for mDNS.
Sun Dec 25 22:27:06 2022 daemon.info avahi-daemon[3200]: Leaving mDNS multicast group on interface utun.IPv4 with address 198.18.0.1.
Sun Dec 25 22:27:06 2022 daemon.info avahi-daemon[3200]: Withdrawing address record for fe80::a9c4:69af:74a6:3c0d on utun.
Sun Dec 25 22:27:06 2022 daemon.info avahi-daemon[3200]: Withdrawing address record for 198.18.0.1 on utun.
Sun Dec 25 22:27:07 2022 daemon.err netdata[10568]: Cannot refresh interface utun carrier state by reading '/sys/class/net/utun/carrier'. Stop updating it.
Sun Dec 25 22:27:10 2022 cron.err crond[6614]: crond (busybox 1.35.0) started, log level 8
Sun Dec 25 22:27:17 2022 daemon.info avahi-daemon[3200]: Joining mDNS multicast group on interface utun.IPv4 with address 198.18.0.1.
Sun Dec 25 22:27:17 2022 daemon.info avahi-daemon[3200]: New relevant interface utun.IPv4 for mDNS.
Sun Dec 25 22:27:17 2022 daemon.info avahi-daemon[3200]: Registering new address record for 198.18.0.1 on utun.IPv4.
Sun Dec 25 22:27:17 2022 daemon.info avahi-daemon[3200]: Joining mDNS multicast group on interface utun.IPv6 with address fe80::7110:15a1:e354:f7f4.
Sun Dec 25 22:27:17 2022 daemon.info avahi-daemon[3200]: New relevant interface utun.IPv6 for mDNS.
Sun Dec 25 22:27:17 2022 daemon.info avahi-daemon[3200]: Registering new address record for fe80::7110:15a1:e354:f7f4 on utun.*.
Sun Dec 25 22:30:00 2022 cron.err crond[6614]: USER root pid 16076 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:35:00 2022 cron.err crond[6614]: USER root pid 30040 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:40:00 2022 cron.err crond[6614]: USER root pid 12627 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:43:37 2022 daemon.info netdata[10568]: Initializing file /var/cache/netdata/net_drops.utun/main.db.
Sun Dec 25 22:43:37 2022 daemon.info netdata[10568]: Initializing file /var/cache/netdata/net_drops.utun/inbound.db.
Sun Dec 25 22:43:37 2022 daemon.info netdata[10568]: Initializing file /var/cache/netdata/net_drops.utun/outbound.db.
Sun Dec 25 22:45:00 2022 cron.err crond[6614]: USER root pid 25401 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:50:00 2022 cron.err crond[6614]: USER root pid 29227 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 22:55:00 2022 cron.err crond[6614]: USER root pid 3711 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:00:00 2022 cron.err crond[6614]: USER root pid 5874 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:05:00 2022 cron.err crond[6614]: USER root pid 8005 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:06:45 2022 daemon.notice miniupnpd[7257]: remove port mapping 39854 UDP because it has expired
Sun Dec 25 23:10:00 2022 cron.err crond[6614]: USER root pid 10167 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:15:00 2022 cron.err crond[6614]: USER root pid 12307 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:20:00 2022 cron.err crond[6614]: USER root pid 14487 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:25:00 2022 cron.err crond[6614]: USER root pid 16635 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:30:00 2022 cron.err crond[6614]: USER root pid 18756 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:35:00 2022 cron.err crond[6614]: USER root pid 20897 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:40:00 2022 cron.err crond[6614]: USER root pid 23036 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:45:00 2022 cron.err crond[6614]: USER root pid 25594 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:50:00 2022 cron.err crond[6614]: USER root pid 29575 cmd /usr/share/unblockneteasemusic/log_check.sh
Sun Dec 25 23:55:00 2022 cron.err crond[6614]: USER root pid 407 cmd /usr/share/unblockneteasemusic/log_check.sh

unm-debug：
Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.15.85",
	"hostname": "MIAOHOME",
	"system": "Intel(R) Celeron(R) J4125 CPU @ 2.00GHz",
	"model": "Default string - Intel(R) Celeron(R) J4125 CPU @ 2.00GHz : 4 Core 4 Thread",
	"board_name": "default-string",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "OpenWrt",
		"version": "SNAPSHOT",
		"target": "x86/64",
		"revision": "R22.12.1",
		"description": "OpenWrt "
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1671733972

Package: libustream-openssl20201210
Version: 2022-12-08-9217ab46-1
Depends: libc, libubox20220927, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1671733972

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 198.18.1.244:443
Writing to stdout

-                      120k --:--:-- ETA
Download completed (123586 bytes)
182a387700839e03c5486e51d93531e8dbde607a

Node.js info:
Package: node
Version: v18.12.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libcares, libatomic1
Status: install user installed
Architecture: x86_64
Installed-Time: 1671733972

Node.js is placed at /usr/bin/node
Node.js version: v18.12.1

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.13-5
Depends: libc, dnsmasq-full, ipset, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic ff774c19ff31a537c8b3a2f1f9fcc413a4e978e92a74cf8d085f3a22649093d1
Installed-Time: 1671733972

-rw-rw-r--    1 root     root         345 Dec 24 19:58 /etc/config/unblockneteasemusic
-rwxrwxr-x    1 root     root       10.8K Dec 23 02:32 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        3.4K Dec 23 22:16 core
-rw-r--r--    1 root     root          41 Dec 23 22:16 core_local_ver
-rwxrwxr-x    1 root     root        5.6K Dec 23 02:32 debugging.sh
-rwxrwxr-x    1 root     root         348 Dec 23 02:32 log_check.sh
drwxrwxr-x    2 root     root          63 Dec 23 02:32 rules
-rwxrwxr-x    1 root     root        3.0K Dec 23 02:32 update.sh

config unblockneteasemusic 'config'
	option follow_source_order '0'
	option local_vip '0'
	option replace_music_source 'dont_replace'
	option use_custom_cookie '0'
	option auto_update '1'
	option update_time '3'
	option enable_flac '1'
	option disable_upgrade_check '0'
	option music_source 'kuwo'
	option advanced_mode '0'
	option enable '1'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 182a387700839e03c5486e51d93531e8dbde607a
Core version: 0.27.0
-rw-r--r--    1 root     root      322.9K Dec 23 22:16 app.js
-rw-r--r--    1 root     root          85 Dec 23 22:16 app.js.LICENSE.txt
-rw-r--r--    1 root     root      271.1K Dec 23 22:16 bridge.js
-rw-r--r--    1 root     root          85 Dec 23 22:16 bridge.js.LICENSE.txt
-rw-r--r--    1 root     root         790 Dec 23 22:16 ca.crt
-rw-r--r--    1 root     root         843 Dec 23 22:16 server.crt
-rw-r--r--    1 root     root         359 Dec 23 22:16 server.key

Netease networking info:
< Location: http://m10.music.126.net/20221226002305/75b12c735b9afa98208fc73510ef4274/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.19.33","59.111.160.195","193.112.159.225","118.24.63.156","47.100.127.239","39.105.175.128","182.92.170.253","39.105.63.80"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      13494/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      13494/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"unblockneteasemusic": {
				"running": true,
				"pid": 13494,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"0.0.0.0",
					"-p",
					"5200:5201",
					"-o",
					"kuwo",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"ENABLE_FLAC": "true",
					"LOG_FILE": "/tmp/unblockneteasemusic.log",
					"LOG_LEVEL": "info",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x0d505d97
Size in memory: 1088
References: 1
Number of entries: 23
Members:
125.94.42.166
47.100.127.239
125.94.42.163
59.111.160.195
125.94.42.162
118.24.63.156
39.105.175.128
125.94.42.160
125.94.42.161
59.111.19.33
125.94.42.165
115.236.121.1
59.111.181.35
39.105.63.80
115.236.121.4
182.92.170.253
125.94.42.159
183.136.182.18
125.94.42.164
36.25.241.122
115.236.118.34
115.236.118.33
193.112.159.225

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x9207f146
Size in memory: 208
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 5
Header: family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x6980bf55
Size in memory: 208
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://10.0.0.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":1},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2VwLnN5Y2RuLmt1d28uY24vYzJmYTdlYTE0MjNkMGZlYzY3ODIyYjJjZDc2OWQ1ZDkvNjNhODczMGYvcmVzb3VyY2UvczMvMC84NS8zMjcxMTI0MTY3LmZsYWM=/33190502.flac","br":999000,"size":30395622,"md5":"0ae627df4a7188efc15aaec5d639d985","code":200,"expi":1200,"type":"flac","gain":0,"peak":null,"fee":0,"uf":null,"payed":0,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":1},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://ep.sycdn.kuwo.cn/57a2625e5b415085b7d34e2fc7b2591f/63a70229/resource/s3/0/85/3271124167.flac"

Local version: 182a387700839e03c5486e51d93531e8dbde607a, latest version: 182a387700839e03c5486e51d93531e8dbde607a.
You're already using the latest version.
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://ep.sycdn.kuwo.cn/c2fa7ea1423d0fec67822b2cd769d5d9/63a8730f/resource/s3/0/85/3271124167.flac"

macOS跟iOS上都是重启openwrt后可以使用一小会，过后就一直无法使用了，证书已信任，windows下没有任何问题。
![Uploading IMG_6011.PNG…]()

**Comment by MIAOBUSI** [comment]
INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/weapi/v3/song/detail?csrf_token=.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (node:internal/crypto/cipher:193:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:51:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:53:90)
        at /usr/share/unblockneteasemusic/core/app.js:100:164
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH
插件日志中提示

**Comment by 1715173329** [comment]
ssl 错误问题已修复
