### ISSUE TITLE
为何PC可以正常使用，而IOS显示“网络不给力，无法继续播放”？

### ISSUE THREAD

**Issue by whm188400131** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#221]
已安装CA证书

**Comment by weiyideai520** [comment]
IOS 设置全部代理，可以播放解锁灰名单。
但是不设置就不行，已安装CA证书

**Comment by weiyideai520** [comment]
PAC设置了也不行，请教PAC应该怎么写？

**Comment by Aluan1996** [comment]
同样的问题，在ios里配置代理以后才能解锁，不配置还是提示VIP。但是配置了以后会出现很多软件加载慢。

**Comment by 1715173329** [comment]
iOS 支持 option 252，代理设定为自动即可。
iptables 版不支持 ipv6 连接，需自行屏蔽相关应答，或者升级到 fw4。
