### ISSUE TITLE
安装插件后在服务中不显示

### ISSUE THREAD

**Issue by Lyn6969** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#224]
unm-debug如下
`root@OpenWrt:~# unm-debug
Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
        "kernel": "5.15.82",
        "hostname": "OpenWrt",
        "system": "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz",
        "model": "Intel H81U - Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz : 2 Core 4 Thread",
        "board_name": "intel-h81u",
        "rootfs_type": "squashfs",
        "release": {
                "distribution": "OpenWrt",
                "version": "SNAPSHOT",
                "target": "x86/64",
                "revision": "Li [2022]GDQ v4.7 Compiled by Li",
                "description": "OpenWrt "
        }
}

uclient-fetch info:
Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: x86_64
Size: 7937
Filename: uclient-fetch_2021-05-14-6a6011df-1_x86_64.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1670480457

Package: libustream-wolfssl20201210
Version: 2022-12-08-9217ab46-1
Depends: libc, libubox20220927, libwolfssl5.5.3.e624513f
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5032
Filename: libustream-wolfssl20201210_2022-12-08-9217ab46-1_x86_64.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2022-12-08-9217ab46-1
Depends: libc, libubox20220927, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Section: libs
Architecture: x86_64
Size: 5533
Filename: libustream-openssl20201210_2022-12-08-9217ab46-1_x86_64.ipk
Description: ustream SSL Library (openssl)
Installed-Time: 1670480457

Package: libustream-mbedtls20201210
Version: 2022-12-08-9217ab46-1
Depends: libc, libubox20220927, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5337
Filename: libustream-mbedtls20201210_2022-12-08-9217ab46-1_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Downloading 'https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled'
Connecting to 198.18.5.108:443
Writing to stdout

Download completed (123447 bytes)
bd9a533a9619e98eb5468436a60d3d572e01d5f5

Node.js info:
Package: node
Version: v16.19.0-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: unknown ok not-installed
Section: lang
Architecture: x86_64
Size: 11672406
Filename: node_v16.19.0-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib

Package: node
Version: v16.18.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libcares, libatomic1
Status: install user installed
Architecture: x86_64
Installed-Time: 1670480457

Node.js is placed at /usr/bin/node
Node.js version: v16.18.1

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.1-3
Depends: libc, dnsmasq-full, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic d29a6951d8a7c19b6a800ca2914cace0667fbd33f0e50eb40a1d80616a2a482d
Installed-Time: 1672303521

-rw-r--r--    1 root     root         310 Dec 10 12:00 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.8K Dec 10 12:00 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
-rwxr-xr-x    1 root     root        5.6K Dec 10 12:00 debugging.sh
-rwxr-xr-x    1 root     root         348 Dec 10 12:00 log_check.sh
drwxr-xr-x    2 root     root        3.4K Dec 29 16:45 rules
-rwxr-xr-x    1 root     root        3.2K Dec 10 12:00 update.sh

config unblockneteasemusic 'config'
        option enable '0'
        option music_source ''
        option follow_source_order '0'
        option local_vip '0'
        option enable_flac '0'
        option disable_upgrade_check '1'
        option replace_music_source 'dont_replace'
        option auto_update '1'
        option update_time '3'
        option advanced_mode '0'

UnblockNeteaseMusic Node.js info:
Git HEAD version: Not Found
Core version: Not Found

Netease networking info:
< Location: http://m10.music.126.net/20221229182441/e1fe704754617e1d6b88ec70f601e0ec/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.118.34","115.236.121.4","59.111.160.195","59.111.19.33","193.112.159.225","47.100.127.239","39.105.175.128","182.92.170.253","39.105.63.80","118.24.63.156"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
No instance found on port 5200.
No instance found on port 5201.

PROCD running info:
{
        "unblockneteasemusic": {
                "triggers": [
                        [
                                "config.change",
                                [
                                        "if",
                                        [
                                                "eq",
                                                "package",
                                                "unblockneteasemusic"
                                        ],
                                        [
                                                "run_script",
                                                "/etc/init.d/unblockneteasemusic",
                                                "reload"
                                        ]
                                ],
                                1000
                        ]
                ]
        }
}

Log is not avaiable.

Log is available at:
https://litter.catbox.moe/d9p6m3.txt
https://transfer.sh/yu8F9a/unm-debugging-output.txt`
软件包中显示已经安装
![image](https://user-images.githubusercontent.com/42564665/209935528-c1233380-0098-413d-974f-699f255c80c1.png)
服务中，不显示：
![image](https://user-images.githubusercontent.com/42564665/209935563-d8acc401-ce30-4b12-a853-ba7d382abea6.png)
![image](https://user-images.githubusercontent.com/42564665/209935592-855a948c-2022-46b8-b919-3e65f57dd2d5.png)
是哪里没配置好吗？

**Comment by Lyn6969** [comment]
解锁灰色歌曲因为和openclash有点冲突所以想换用这个，是这两个插件有冲突吗？尝试过清除缓存重启，还是无效

**Comment by 1715173329** [comment]
版本装错了，用 2.x

**Comment by Lyn6969** [comment]
> 版本装错了，用 2.x

好的谢谢！
