### ISSUE TITLE
There was a conflict with dnsmasq during installation

### ISSUE THREAD

**Issue by g0dA** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#228]
### Bug 描述

My openwrt version: `OpenWrt 22.03.2`
ipk version: `luci-app-unblockneteasemusic_3.1-3_javascript_all.ipk`

install this by `Upload Package`

Error occurred：

```
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-unblockneteasemusic.
```

### 调试报告

I try to replace dnsmasq with dnsmasq-full
```
opkg update
opkg remove dnsmasq && opkg install dnsmasq-full
```
This will install the plugin correctly, but I don’t know if there is a problem with dnsmasq-full. 

There will be a problem with my DHCP, which will cause the new device to fail to connect to the Internet.

If you switch back to dnsmasq, the plugin will be uninstalled

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
openwrt 出于大小考虑默认用 dnsmasq，这个没有 nftset 支持。httpdns 不一定包括所有的 cdn ip，可能会造成劫持失败。
dnsmasq-full 在我们的生产环境中工作正常，但是你必须使用默认的配置文件并重新配置。

**Comment by g0dA** [comment]
ok, thanks
