### ISSUE TITLE
用了插件之后频繁发生的问题

### ISSUE THREAD

**Issue by AntoineGao** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#229]

**Comment by 1715173329** [comment]
关于音源错误问题，本项目应该已经说得很清楚，是从其他平台获取替换，自然无法保证获取到的一定正确。你可以根据你自己的听歌习惯指定一些匹配度高的平台。

少部分是哪些部分？hires 歌曲是什么歌曲，本项目不提供音质选项的解锁。

**Comment by AntoineGao** [comment]
> 关于音源错误问题，本项目应该已经说得很清楚，是从其他平台获取替换，自然无法保证获取到的一定正确。你可以根据你自己的听歌习惯指定一些匹配度高的平台。
> 
> 少部分是哪些部分？hires 歌曲是什么歌曲，本项目不提供音质选项的解锁。

就是左下角标有hi-res标志的无损歌曲

**Comment by 1715173329** [comment]
那本质就是 VIP 歌曲。或者普通用户也能播放低音质的话，那就不会走 unm。
什么歌曲不能播放，上链接，还有是什么平台。

**Comment by 1715173329** [comment]
走一下 https://github.com/UnblockNeteaseMusic/server/issues/new?assignees=&labels=bug&template=bug-report.yml 的 issue template 吧，看起来不属于这里的问题。
