### ISSUE TITLE
加入“手动升级核心”或添加备用下载源

### ISSUE THREAD

**Issue by BHLuotianyi** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#230]
### 需求描述

如题。由于国内网络环境，访问github十分困难。插件（2.13-6）默认从github下载核心，这导致插件无法启动（Core Not Found），而点击“更新核心”则又显示“核心已是最新”。
给路由器本机配置代理也十分麻烦（现在主流的富强插件如Passwall等并不能正确地为Openwrt配置代理）。因此，能否加入一个“从本地上传核心”的按钮，或是添加一个备用的下载源（如Gitee）？

### 预期行为

在“更新核心”菜单内加入两个新的按钮：
1.手动上传核心
从访问管理网页的设备上传UnblockNeteaseMusic核心至Openwrt。进行版本校验后替换现有的核心（如果版本号比现有的更低，则给出一个确认提示）
2.从Gitee下载核心
我不知道更新核心的实现方式。如果是用git或curl的话，Gitee能大大提升很多国内用户的使用体验。

### OpenWrt 版本

22.03.2

### 条款

- [X] 我同意作者没有任何义务必须满足我的需求，尤其是高度自定义或特定于个人环境的需求。

**Comment by 1715173329** [comment]
> 如题。由于国内网络环境，访问github十分困难。插件（2.13-6）默认从github下载核心，这导致插件无法启动（Core Not Found），而点击“更新核心”则又显示“核心已是最新”。

这个是旧 lua 插件的 bug，可能原因是从 GitHub 拉 commit hash 也失败了，最后 nil == nil，没研究过。

> 给路由器本机配置代理也十分麻烦（现在主流的富强插件如Passwall等并不能正确地为Openwrt配置代理）。

我印象中是可以的，OpenClash 也可以。

> 或是添加一个备用的下载源（如Gitee）

Gitee 狗看了都摇头。

> ### OpenWrt 版本
> 22.03.2

你的版本既然是 22.03，则应该使用 3.x 版本，是没有版本号检测失败的 bug。

这方面暂时不想处理，有点麻烦。
你可以自己上传文件。
- `/usr/share/unblockneteasemusic/core_local_ver` # 完整 commit hash
- `/usr/share/unblockneteasemusic/core/app.js`
- `/usr/share/unblockneteasemusic/core/ca.crt`
- `/usr/share/unblockneteasemusic/core/server.crt`
- `/usr/share/unblockneteasemusic/core/server.key`

**Comment by BHLuotianyi** [comment]
![F2ACDBC2-3EF3-40D8-AD71-054C269CC5F7](https://user-images.githubusercontent.com/62016462/216073396-7b46bd68-7f5b-46a0-acd0-4fac676b2b8d.png)
是不是github出问题了？我这里直接访问更新脚本中的sha地址返回为空
![14307234-6E54-4332-94B0-D8C7518A504C](https://user-images.githubusercontent.com/62016462/216076133-02f5ada6-8d34-49e3-b74b-c7eb902400ce.png)
后面获取核心文件的链接也失效了。

**Comment by clawCa** [comment]
挂openclash或者passwall也不能下载核心了

**Comment by xianren78** [comment]
uclient-fetch有问题，换成wget就好了
