### ISSUE TITLE
Failed to check latest core version, please try again later.

### ISSUE THREAD

**Issue by clawCa** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#235]
### 需求描述

无法下载核心

### OpenWrt 版本

5.15.86  /OpenWrt 01.10.2023 by Kiddin' / LuCI Master git-3227eb6

### 条款

- [X] 我同意作者没有任何义务必须满足我的需求，尤其是高度自定义或特定于个人环境的需求。

**Comment by 1715173329** [comment]
网络问题。
