### ISSUE TITLE
“网络不给力哦，请检查你的网络设置”，最新的windows版，和较新的安卓版都出现了此问题

### ISSUE THREAD

**Issue by lieternity** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#236]
### Bug 描述

如题，之前还用的好好的，现在就不行了，我感觉应该是新版网易云的问题，如果是的话，哪一个版本可以用？安卓和windows，有新版也可以用的解决办法吗？安卓使用的时候可以打印出歌曲url，但是电脑上就完全啥都没有

### 调试报告

https://transfer.sh/koX0P6/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 13071558875** [comment]
安装证书，设置客户端代理，已解决

**Comment by impl1874** [comment]
也可使用旧版本客户端解决：[2.9.10.200061阿里云盘](https://www.aliyundrive.com/s/yaXFXX5KbHv)
