### ISSUE TITLE
安装期间报错

### ISSUE THREAD

**Issue by liyishuai** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#237]
### Bug 描述

在Release页面下载的`.ipk`文件无法安装。

### 实际行为

```
Unknown package 'luci-app-unblockneteasemusic'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency node for luci-app-unblockneteasemusic
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-unblockneteasemusic found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-unblockneteasemusic.
 ```

### 复现步骤

```shell
opkg install luci-app-unblockneteasemusic_3.1-4_javascript_all.ipk
```

### 调试报告

Haven't managed installed `unm-debug` yet.

### 其他信息

|Field| Value|
|---|---|
| Model | Xiaomi Redmi Router AC2100 |
| Architecture |MediaTek MT7621 ver:1 eco:3 |
| Firmware Version | OpenWrt 21.02.0 r16279-5cc0535800 / LuCI openwrt-21.02 branch git-21.231.26241-422c175|
| Kernel Version | 5.4.143 |

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
nodejs 14 x 以后的版本已经彻底丢弃 mips 架构支持。

**Comment by 865102930** [comment]
> ### Bug 描述
> 在Release页面下载的`.ipk`文件无法安装。
> 
> ### 预期行为
> _No response_
> 
> ### 实际行为
> ```
> Unknown package 'luci-app-unblockneteasemusic'.
> Collected errors:
>  * pkg_hash_check_unresolved: cannot find dependency node for luci-app-unblockneteasemusic
>  * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-unblockneteasemusic found, but incompatible with the architectures configured
>  * opkg_install_cmd: Cannot install package luci-app-unblockneteasemusic.
> ```
> 
> ### 复现步骤
> ```shell
> opkg install luci-app-unblockneteasemusic_3.1-4_javascript_all.ipk
> ```
> 
> ### 调试报告
> Haven't managed installed `unm-debug` yet.
> 
> ### 其他信息
> Field	Value
> Model	Xiaomi Redmi Router AC2100
> Architecture	MediaTek MT7621 ver:1 eco:3
> Firmware Version	OpenWrt 21.02.0 r16279-5cc0535800 / LuCI openwrt-21.02 branch git-21.231.26241-422c175
> Kernel Version	5.4.143
> ### 条款
> * [x]  我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
> * [x]  我确认我已经升级到了最新的插件版本（包括核心和插件）。
> * [x]  我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
> * [x]  我确认我没有混用 iptables 和 nftables 规则。
> * [x]  我确认我已经在对应的客户端正确安装了 CA 证书。
> * [x]  我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

我跟你错误一样的,缺少依赖node,装一下依赖包

**Comment by blngxj** [comment]
> > ### Bug 描述
> > 在Release页面下载的`.ipk`文件无法安装。
> > ### 预期行为
> > _No response_
> > ### 实际行为
> > ```
> > Unknown package 'luci-app-unblockneteasemusic'.
> > Collected errors:
> >  * pkg_hash_check_unresolved: cannot find dependency node for luci-app-unblockneteasemusic
> >  * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-unblockneteasemusic found, but incompatible with the architectures configured
> >  * opkg_install_cmd: Cannot install package luci-app-unblockneteasemusic.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 复现步骤
> > ```shell
> > opkg install luci-app-unblockneteasemusic_3.1-4_javascript_all.ipk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 调试报告
> > Haven't managed installed `unm-debug` yet.
> > ### 其他信息
> > Field	Value
> > Model	Xiaomi Redmi Router AC2100
> > Architecture	MediaTek MT7621 ver:1 eco:3
> > Firmware Version	OpenWrt 21.02.0 r16279-5cc0535800 / LuCI openwrt-21.02 branch git-21.231.26241-422c175
> > Kernel Version	5.4.143
> > ### 条款
> > 
> > * [x]   我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
> > * [x]   我确认我已经升级到了最新的插件版本（包括核心和插件）。
> > * [x]   我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
> > * [x]   我确认我没有混用 iptables 和 nftables 规则。
> > * [x]   我确认我已经在对应的客户端正确安装了 CA 证书。
> > * [x]   我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。
> 
> 我跟你错误一样的,缺少依赖node,装一下依赖包

请问一下 我安装上了node 顺带装了ndoe-npm 安装时仍缺少依赖，还应该安装什么。在看完日志之后我尝试opkg install kmod 确实更新了 但是仍是这个错误

root@OpenWrt:~# opkg install /tmp/tmp/luci-app-unblockneteasemusic_2.14-3_all.ipk
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libatomic1 and libatomic1) providing same name marked HOLD or PREFER. Using latest.
Package luci-app-unblockneteasemusic (2.14-3) installed in root is up to date.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-conntrack-netlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-reject6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-conntrack6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-log
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-log6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-crypto-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-lib-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nft-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.131-1-61d44f65bd1b028e12cc87814825d543) for kmod-ipt-ipset
