### ISSUE TITLE
ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

### ISSUE THREAD

**Issue by superwong777** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#238]
### Bug 描述

升级到iStoreOS 21.02.3 2023021714，发现日志报错：提示：

ERROR: (hook) A error occurred in hook.request.after when hooking https://music.163.com/weapi/song/enhance/player/url/v1?csrf_token=.
    Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
        at Decipheriv.final (internal/crypto/cipher.js:174:29)
        at decrypt (/usr/share/unblockneteasemusic/core/app.js:51:56)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:53:90)
        at /usr/share/unblockneteasemusic/core/app.js:100:163
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
    library: digital envelope routines
    function: EVP_DecryptFinal_ex
    reason: wrong final block length
    code: ERR_OSSL_EVP_WRONG_FINAL_BLOCK_LENGTH

Local version: 7f5e4d55944f4e56b1729a697b7f531561a7954e, latest version: 7f5e4d55944f4e56b1729a697b7f531561a7954e.
You're already using the latest version.

### 调试报告

https://transfer.sh/FFfkWe/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
#234

**Comment by 1715173329** [comment]
已修复
