### ISSUE TITLE
版本2.13-6程序未运行

### ISSUE THREAD

**Issue by gally16** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#239]
### Bug 描述

[img]https://i.328888.xyz/2023/03/05/dWKOQ.png[/img]
[img]https://i.328888.xyz/2023/03/05/dWM1C.jpeg[/img]
版本2.13-6

### 调试报告

版本2.13-6
运行不了
删除核心又重新更新了还是不行

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
- 没有调试报告
- 你网烂了，必须开梯子
