### ISSUE TITLE
uwp客户端没问题，但网页版提示地区错误

### ISSUE THREAD

**Issue by gally16** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#240]
### Bug 描述

[img]https://i.328888.xyz/2023/03/06/hU78N.png[/img]

uwp客户端没问题，但网页版提示地区错误
也装了[NeteaseMusic UI Unlocker

### 调试报告

uwp客户端没问题，但网页版提示地区错误

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
网页不受支持，原脚本也应该失效了。

**Comment by gally16** [comment]
> 网页不受支持，原脚本也应该失效了。

大佬，有别的方法吗QAQ
