### ISSUE TITLE
插件无法启动

### ISSUE THREAD

**Issue by MinanaYaa** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#241]
### Bug 描述

在软路由后台显示（已尝试删除核心并更新核心）
Failed to check latest core version, please try again later.
Core Not Found, please download it before starting.

ssh连接重启显示
iptables v1.8.7 (legacy): Set neteasemusic doesn't exist.

Try `iptables -h' or 'iptables --help' for more information.
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
Command failed: Not found
Failed to parse json data: unexpected end of data

### 调试报告

https://transfer.sh/tQjNpo/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
网烂了，无法从 GitHub API 获取数据。

**Comment by MinanaYaa** [comment]
> 网烂了，无法从 GitHub API 获取数据。

但是我挂了科学，而且是全局的，拉取其它GitHub的库都可以呀

**Comment by MinanaYaa** [comment]
https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/issues/167#issuecomment-1179497363
刷到这个问题的朋友请参考这条
在软件包中安装git-http、libmbedtls,
然后
cd /usr/share/unblockneteasemusic/core
git clone https://github.com/UnblockNeteaseMusic/server.git 
/etc/init.d/unblockneteasemusic start
# git拉取不了就在windows拉取再上传

**Comment by zbceru** [comment]
> 
不用酷狗就可以启动，
![image](https://user-images.githubusercontent.com/93376566/227714192-60f72590-25a3-4990-8023-fc1a4ffc0f13.png)
