### ISSUE TITLE
Failed to check latest core version, please try again later.

### ISSUE THREAD

**Issue by xkcore123** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#242]
### Bug 描述

刚编译的固件更新核心提示：Failed to check latest core version, please try again later.
前两个星期编译的还是正常的。
这是啥问题

### 调试报告

https://litter.catbox.moe/cnm658.txt
https://transfer.sh/U6b5Gk/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
你网烂了，无法连接到 GitHub，就这么回事。
