### ISSUE TITLE
R2S 的解锁经常更新失败 没有程序  不管是手动还是自动都是更新失败

### ISSUE THREAD

**Issue by hhht110** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#243]
### Bug 描述

我在很多版本上面都遇到了 不管是 全局科学还是半局 都是更新不了不知道为什么。。。。

### 预期行为

就更新就更新不了。。删除版本更新也不行。。。

### 实际行为

就更新就更新不了。。删除版本更新也不行。。。

### 复现步骤

就更新就更新不了。。删除版本更新也不行。。。

### 调试报告

就更新就更新不了。。删除版本更新也不行。。。

### 其他信息

就更新就更新不了。。删除版本更新也不行。。。

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
网络问题，要么你机场 ip 太脏

**Comment by hhht110** [comment]
我以为 解锁没人管 挂了呢。。看来还在， 那我  ……这不是天灵小哥哥吗。。哎呦  哈哈哈  那我试着换几个节点试试吧  或者换个机场吧。。我用的西部啊 不应该啊

**Comment by hhht110** [comment]
上一个固件版本没问题 这个固件版本死活更新不了。。我换了N个节点都不行
