### ISSUE TITLE
好像是IPT_RULE_NAME没有定义导致日志报错

### ISSUE THREAD

**Issue by SpeedPartner** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#244]
### Bug 描述

虽然使用上似乎没问题....用的是master分支.

### 调试报告

Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables v1.8.7 (legacy): chain name may not clash with target name
Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic:
Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: Try `iptables -h' or 'iptables --help' for more information.
Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables v1.8.7 (legacy): Invalid target name (too short)
Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: Try `iptables -h' or 'iptables --help' for more information.
Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables: No chain/target/match by that name.
Sun Apr  2 02:36:29 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables: No chain/target/match by that name.

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
$IPT_RULE_NAME 改成 $IPT_INPUT_RULE 康康，这个是把端口暴露到公网的规则

**Comment by SpeedPartner** [comment]
Sun Apr  2 03:14:37 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables v1.8.7 (legacy): chain name `unblockneteasemusic_input_rule' too long (must be under 29 chars)
Sun Apr  2 03:14:37 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: Try `iptables -h' or 'iptables --help' for more information.
Sun Apr  2 03:14:37 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables v1.8.7 (legacy): Invalid target name `unblockneteasemusic_input_rule' (28 chars max)
Sun Apr  2 03:14:37 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: Try `iptables -h' or 'iptables --help' for more information.
Sun Apr  2 03:14:37 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables: No chain/target/match by that name.
Sun Apr  2 03:14:37 2023 daemon.notice procd: /etc/rc.d/S99unblockneteasemusic: iptables: No chain/target/match by that name.

**Comment by SpeedPartner** [comment]
我把名称改小点康康...

**Comment by SpeedPartner** [comment]
好了,名称也改小后不报错了,我把原来防火墙里自己打开的端口删除后,也可以正常在公网访问了(开启"部署到公网"的情况下).
关闭"部署到公网"也马上有效.

**Comment by 1715173329** [comment]
感谢测试，今天修一下
