### ISSUE TITLE
启用后等几秒钟就显示未运行

### ISSUE THREAD

**Issue by xiaoqi2020** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#245]
### Bug 描述

启用后等几秒钟就显示未运行

### 调试报告

https://transfer.sh/8Fr3uJ/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
你的 DNS 有问题，无法解析网易云音乐服务端地址。
此外不建议用 istoreos 这种固件。

**Comment by xiaoqi2020** [comment]
> 你的 DNS 有问题，无法解析网易云音乐服务端地址。 此外不建议用 istoreos 这种固件。
我是爱快虚拟机挂载的istoreos，然后dns是adguardhome
