### ISSUE TITLE
编译报错怎么解决？

### ISSUE THREAD

**Issue by 725216** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#247]
### 需求描述

 -Wdouble-promotion -Wshadow -Wformat=2 -Wmisleading-indentation -fvisibility=hidden -DXML_ENABLE_VISIBILITY=1 -MT xmlparse.lo -MD -MP -MF .deps/xmlparse.Tpo -c -o xmlparse.lo xmlparse.c
../libtool: 1588: ../libtool: preserve_args+= --tag CC: not found
../libtool: 1: eval: base_compile+= gcc: not found
../libtool: 1: eval: base_compile+= -DHAVE_CONFIG_H: not found
../libtool: 1: eval: base_compile+= -I.: not found
../libtool: 1: eval: base_compile+= -I..: not found
../libtool: 1: eval: base_compile+= -I/home/rxy/7621/staging_dir/host/include: not found
../libtool: 1: eval: base_compile+= -I/home/rxy/7621/staging_dir/host/usr/include: not found
../libtool: 1: eval: base_compile+= -I/home/rxy/7621/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/include: not found
../libtool: 1: eval: base_compile+= -DHAVE_EXPAT_CONFIG_H: not found
../libtool: 1: eval: base_compile+= -O2: not found
../libtool: 1: eval: base_compile+= -I/home/rxy/7621/staging_dir/host/include: not found
../libtool: 1: eval: base_compile+= -I/home/rxy/7621/staging_dir/host/usr/include: not found
../libtool: 1: eval: base_compile+= -I/home/rxy/7621/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/include: not found
../libtool: 1: eval: base_compile+= -Wall: not found
../libtool: 1: eval: base_compile+= -Wextra: not found
../libtool: 1: eval: base_compile+= -fexceptions: not found
../libtool: 1: eval: base_compile+= -fno-strict-aliasing: not found
../libtool: 1: eval: base_compile+= -Wmissing-prototypes: not found
../libtool: 1: eval: base_compile+= -Wstrict-prototypes: not found
../libtool: 1: eval: base_compile+= -pedantic: not found
../libtool: 1: eval: base_compile+= -Wduplicated-cond: not found
../libtool: 1: eval: base_compile+= -Wduplicated-branches: not found
../libtool: 1: eval: base_compile+= -Wlogical-op: not found
../libtool: 1: eval: base_compile+= -Wrestrict: not found
../libtool: 1: eval: base_compile+= -Wnull-dereference: not found
../libtool: 1: eval: base_compile+= -Wjump-misses-init: not found
../libtool: 1: eval: base_compile+= -Wdouble-promotion: not found
../libtool: 1: eval: base_compile+= -Wshadow: not found
../libtool: 1: eval: base_compile+= -Wformat=2: not found
../libtool: 1: eval: base_compile+= -Wmisleading-indentation: not found
../libtool: 1: eval: base_compile+= -fvisibility=hidden: not found
../libtool: 1: eval: base_compile+= -DXML_ENABLE_VISIBILITY=1: not found
../libtool: 1: eval: base_compile+= -MT: not found
../libtool: 1: eval: base_compile+= xmlparse.lo: not found
../libtool: 1: eval: base_compile+= -MD: not found
../libtool: 1: eval: base_compile+= -MP: not found
../libtool: 1: eval: base_compile+= -MF: not found
../libtool: 1: eval: base_compile+= .deps/xmlparse.Tpo: not found
../libtool: 1: eval: base_compile+= -c: not found
OpenWrt-libtool: compile: you must specify a compilation command
OpenWrt-libtool: compile: Try `libtool --help --mode=compile' for more information.
Makefile:508: recipe for target 'xmlparse.lo' failed
make[5]: *** [xmlparse.lo] Error 1
make[5]: Leaving directory '/home/rxy/7621/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/expat-2.2.9/lib'
Makefile:548: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1

### OpenWrt 版本

潘多拉18.10sdk

### 条款

- [X] 我同意作者没有任何义务必须满足我的需求，尤其是高度自定义或特定于个人环境的需求。

**Comment by 1715173329** [comment]
你的源码 环境 系统都有问题，本项目不支持 mips。
