### ISSUE TITLE
服务不能启动

### ISSUE THREAD

**Issue by ntrman** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#250]
### Bug 描述

勾选“启用服务”后保存并应用，依旧显示“UnblockNeteaseMusic 未运行”。

### 预期行为

让服务正常启动起来

### 复现步骤

1. 勾选“启用服务”；
2. 保存并应用；
3. 无法启动。

### 调试报告

https://transfer.sh/AtsHnB/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
1. 你的 nodejs 版本太低，至少要 12.x
2. 你的 nodejs 程序有问题，多半是 libc 出了问题
3. 你的固件不属于 openwrt 或 immortalwrt 官方发行，只能询问固件发布者。
