### ISSUE TITLE
本地VIP失效

### ISSUE THREAD

**Issue by Mousehk** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#251]
### Bug 描述

勾选本地VIP后功能失效

### 调试报告

勾选本地VIP后功能失效

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
已修复。

**Comment by Mousehk** [comment]
感谢 测试发现手机端网易云6.0版本 登陆账号后本地VIP已正常 但是只要登陆账号灰音乐就无法白 退出账号就能正常。
安装证书和重启都这种情况。
