### ISSUE TITLE
在pc端使用失败，使用的是

### ISSUE THREAD

**Issue by Nannccyy** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#253]
### Bug 描述

具体是在网易云内设置代理后，不管是ipv4的网关还是ipv6的网关，都无法正常使用，提示网络不给力。
而且不知道这个插件兼不兼容ipv6，它在log文件分配的是：
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
使用的是luci-app-unblockneteasemusic_3.2-2_javascript_all
![image](https://user-images.githubusercontent.com/85016627/232275668-79a985e2-65fa-4342-8a14-e70ecaedc5d7.png)
![image](https://user-images.githubusercontent.com/85016627/232275729-af80901a-7bf7-4b2f-904f-a9b82bd4306c.png)
ipv6的代理也无效，istoreos也安装了openclash，但把openclash关掉也无法使用。

### 调试报告

https://transfer.sh/jEtqvr/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by Nannccyy** [comment]
当把http代理更改成不使用代理后，无法正常使用网易云了

**Comment by Mousehk** [comment]
同样遇到这情况 luci-app-unblockneteasemusic_2.14-2_all.ipk版本    不过我有三台电脑 有一台正常 其他两台就是无网络 卸载重装 代理都不行

**Comment by uynhi** [comment]
+1,我也是同样的问题

**Comment by 1715173329** [comment]
iptables 版不支持 v6 连接。检查下是不是网易云音乐被解析到海外地址了，可以自行在进阶设置里面指定 IP 地址。
