### ISSUE TITLE
unblockneteasemusic不生效

### ISSUE THREAD

**Issue by ssxwcz** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#254]
### Bug 描述

openwrt环境为ImmortalWrt  21.02.5，使用openclash作为代理软件，模式为Redir-Host tun，安卓手机连接WiFi后，在openclash的内核日志中可以查看到该客户端请求日志，但是查看unblockneteasemusic日志发现并没有收到请求，防火墙的规则我看都已经添加上了，解锁变灰歌曲功能未生效。
![image](https://user-images.githubusercontent.com/43665491/232722070-f854d4aa-c6ff-4ab3-b6f5-0d1f0496e08b.png)
![image](https://user-images.githubusercontent.com/43665491/232722062-af7f3a00-f798-4848-84af-0a805e0d7360.png)
![image](https://user-images.githubusercontent.com/43665491/232722386-a248f581-5159-4ea7-ad7a-672785b41d79.png)
![image](https://user-images.githubusercontent.com/43665491/232723042-8396b5ff-7b26-4700-a181-8619825fc0a4.png)

### 预期行为

可以正常解锁变灰歌曲

### 调试报告

https://litter.catbox.moe/d2gf2w.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。
- [X] 我同意作者没有任何义务必须解答我的问题，尤其是缺少恰当的描述和日志。

**Comment by 1715173329** [comment]
1) 必须信任为系统证书，需要 root 操作
2) 本项目未测试也不会在“旁路由”进行测试，如果不能使用也可以认为是预期行为

**Comment by ssxwcz** [comment]
> 1. 必须信任为系统证书，需要 root 操作
> 2. 本项目未测试也不会在“旁路由”进行测试，如果不能使用也可以认为是预期行为

1. 安卓应该不用安装证书吧？
2. 好的

**Comment by 1715173329** [comment]
需要的，必须安装为系统证书，否则无效
