### ISSUE TITLE
音源

### ISSUE THREAD

**Issue by zbceru** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#255]
### Bug 描述

音源加入酷狗就启动不了
![image](https://user-images.githubusercontent.com/93376566/232985037-cfb644f7-d401-411b-90bc-6d7d353f48a7.png)

### 调试报告

![image](https://user-images.githubusercontent.com/93376566/232985224-cc11793c-2abf-415f-980c-35ee160f2843.png)

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by zbceru** [comment]
添加kugo音源核心就启动不了

**Comment by 1715173329** [comment]
那你就按照 issue 的说明去打日志

**Comment by 1715173329** [comment]
kugou 不是 kugo
