### ISSUE TITLE
核心更新报错

### ISSUE THREAD

**Issue by kygsmsc** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#256]
### Bug 描述

[luci-app-unblockneteasemusic v3.2-2 JavaScript]在使用时先要更新核心，但是核心更新失败，使用luci-app-unblockneteasemusic_2.14-2_all.ipk时核心更新就正常。

### 调试报告

Failed to check latest core version, please try again later.

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by kygsmsc** [comment]
Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
{
	"kernel": "5.4.188",
	"hostname": "iStoreOS",
	"system": "Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz",
	"model": "QEMU Standard PC (i440FX + PIIX, 1996)",
	"board_name": "qemu-standard-pc-i440fx-piix-1996",
	"release": {
		"distribution": "iStoreOS",
		"version": "21.02.3",
		"revision": "2023040712",
		"target": "x86/64",
		"description": "iStoreOS 21.02.3 2023040712"
	}
}


uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: unknown ok not-installed
Section: net
Architecture: x86_64
Size: 7939
Filename: uclient-fetch_2023-04-13-007d9454-1_x86_64.ipk
Description: Tiny wget replacement using libuclient

Package: uclient-fetch
Version: 2021-05-14-6a6011df-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1680751891

Package: libustream-wolfssl20201210
Version: 2022-01-16-868fd881-2
Depends: libc, libubox20210516, libwolfssl5.5.3.99a5b54a
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 4981
Filename: libustream-wolfssl20201210_2022-01-16-868fd881-2_x86_64.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-2
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5414
Filename: libustream-openssl20201210_2022-01-16-868fd881-2_x86_64.ipk
Description: ustream SSL Library (openssl)

Package: libustream-openssl20201210
Version: 2022-01-16-868fd881-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1680751891

Package: libustream-mbedtls20201210
Version: 2022-01-16-868fd881-2
Depends: libc, libubox20210516, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: x86_64
Size: 5251
Filename: libustream-mbedtls20201210_2022-01-16-868fd881-2_x86_64.ipk
Description: ustream SSL Library (mbedtls)

Package: wget-ssl
Version: 1.21.1-1
Depends: libc, libpcre, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: unknown ok not-installed
Section: net
Architecture: x86_64
Size: 216988
Filename: wget-ssl_1.21.1-1_x86_64.ipk
Description: Wget is a network utility to retrieve files from the Web using http and ftp, the two most widely used Internet protocols. It works non-interactively, so it will work in the background, after having logged off. The program supports recursive retrieval of web-authoring pages as well as ftp sites -- you can use wget to make mirrors of archives and home pages or to travel the Web like a WWW robot. This package is built with SSL support.

Package: wget-ssl
Version: 1.21.1-2
Depends: libc, libpcre, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1680751891

--2023-04-21 17:03:58--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... failed: Try again.
wget: unable to resolve host address 'api.github.com'
Failed to parse json data: unexpected end of data
Failed to connect to GitHub with uclient-fetch.


Node.js info:
Package: node
Version: v14.21.3-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install user installed
Section: lang
Architecture: x86_64
Size: 10680489
Filename: node_v14.21.3-1_x86_64.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 6.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1682063802

Node.js is placed at /usr/bin/node
Node.js version: v14.21.3


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.2-2
Depends: libc, dnsmasq-full, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1682066242

-rw-r--r--    1 root     root         213 Apr 21 17:00 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.7K Apr 15 02:54 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
-rwxr-xr-x    1 root     root        5.3K Apr 15 02:54 debugging.sh
-rwxr-xr-x    1 root     root         392 Apr 15 02:54 log_check.sh
-rw-r--r--    1 root     root        1.7K Apr 15 02:54 nftables.ut
-rwxr-xr-x    1 root     root        3.0K Apr 15 02:54 update.sh

config unblockneteasemusic 'config'
	option disable_upgrade_check '1'
	option auto_update '1'
	option update_time '3'
	option enable '1'
	list music_source 'bilibili'
	option replace_music_source 'dont_replace'



UnblockNeteaseMusic Node.js info:
Git HEAD version: Not Found
Core version: Not Found


Netease networking info:
< Location: http://m10.music.126.net/20230421172905/cfb549f4345567ed60473f9ba65e23cb/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.236.121.4","115.236.118.34","59.111.160.195","59.111.19.33","39.105.63.80","193.112.159.225","182.92.170.253","47.100.127.239","39.105.175.128","118.24.63.156"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      7423/UnblockNetease
tcp        0      0 :::5201                 :::*                    LISTEN      7423/UnblockNetease


PROCD running info:
{
	
}



Failed to check latest core version, please try again later.


Log is available at:
https://litter.catbox.moe/nw7jod.txt
https://transfer.sh/8CcTf7/unm-debugging-output.txt

**Comment by 1715173329** [comment]
DNS 问题，github 域名都解析不出来。
不建议用这种固件。
