### ISSUE TITLE
插件无法运行

### ISSUE THREAD

**Issue by sheip9** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#257]
### Bug 描述

勾选启用后插件并不会运行
系统日志中有发现
procd: Instance unblockneteasemusic::unblockneteasemusic s in a crash loop 6 crashes, 1 seconds since last crash

### 调试报告

https://transfer.sh/mRgua3/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
node /usr/share/unblockneteasemusic/core/app.js -v
看看输出

**Comment by sheip9** [comment]
root@XiaoQiang:~# node /usr/share/unblockneteasemusic/core/app.js -v
Illegal instruction

**Comment by 1715173329** [comment]
nodejs binary 烂了，可能是你的指令集问题，又或者 nodejs 本身。
