### ISSUE TITLE
新版本无法运行

### ISSUE THREAD

**Issue by MinanaYaa** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#258]
### Bug 描述

一直显示未运行，怎么操作都是未运行

### 调试报告

https://litter.catbox.moe/p7kplm.txt
https://litter.catbox.moe/p7kplm.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by MinanaYaa** [comment]
大佬帮看看

**Comment by 1715173329** [comment]
日志里面没什么有意义的东西，大概率是核心内部终止运行了。
命令行输入 logread 看看

**Comment by MinanaYaa** [comment]
> 日志里面没什么有意义的东西，大概率是核心内部终止运行了。 命令行输入 logread 看看

Wed Apr 26 17:37:04 2023 cron.info crond[19602]: crond (busybox 1.36.0) started, log level 5
Wed Apr 26 17:37:05 2023 daemon.info node[19657]: Error: getaddrinfo ENOTFOUND apm3.music.163.com
Wed Apr 26 17:37:05 2023 daemon.info node[19657]:     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
Wed Apr 26 17:37:05 2023 daemon.info node[19657]:   errno: -3008,
Wed Apr 26 17:37:05 2023 daemon.info node[19657]:   code: 'ENOTFOUND',
Wed Apr 26 17:37:05 2023 daemon.info node[19657]:   syscall: 'getaddrinfo',
Wed Apr 26 17:37:05 2023 daemon.info node[19657]:   hostname: 'apm3.music.163.com'
Wed Apr 26 17:37:05 2023 daemon.info node[19657]: }
Wed Apr 26 17:37:05 2023 daemon.info procd: Instance unblockneteasemusic::unblockneteasemusic s in a crash loop 8 crashes, 1 seconds since last crash
Wed Apr 26 17:37:08 2023 daemon.notice wpa_supplicant[2248]: wlan0: WNM: Preferred List Available
Wed Apr 26 17:37:10 2023 daemon.notice wpa_supplicant[2248]: wlan0: CTRL-EVENT-BEACON-LOSS
Wed Apr 26 17:37:24 2023 cron.info crond[20385]: crond (busybox 1.36.0) started, log level 5
Wed Apr 26 17:37:25 2023 daemon.info node[20440]: Error: getaddrinfo ENOTFOUND apm3.music.163.com
Wed Apr 26 17:37:25 2023 daemon.info node[20440]:     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
Wed Apr 26 17:37:25 2023 daemon.info node[20440]:   errno: -3008,
Wed Apr 26 17:37:25 2023 daemon.info node[20440]:   code: 'ENOTFOUND',
Wed Apr 26 17:37:25 2023 daemon.info node[20440]:   syscall: 'getaddrinfo',
Wed Apr 26 17:37:25 2023 daemon.info node[20440]:   hostname: 'apm3.music.163.com'
Wed Apr 26 17:37:25 2023 daemon.info node[20440]: }
Wed Apr 26 17:37:25 2023 daemon.info procd: Instance unblockneteasemusic::unblockneteasemusic s in a crash loop 9 crashes, 1 seconds since last crash
Wed Apr 26 17:37:36 2023 cron.info crond[20913]: crond (busybox 1.36.0) started, log level 5

**Comment by 1715173329** [comment]
DNS 问题，没解析出网易云音乐域名

**Comment by MinanaYaa** [comment]
> DNS 问题，没解析出网易云音乐域名

要改上游DNS吗，还是直接把dnsmsq给关了

**Comment by 1715173329** [comment]
上游 DNS

**Comment by MinanaYaa** [comment]
> 上游 DNS

谢谢大佬

**Comment by 1715173329** [comment]
不敢，您客气

**Comment by ZZZ-zero** [comment]
佬，上游DNS怎么写啊？
