### ISSUE TITLE
开启这个功能好像跟openclash冲突了。一开断网，一关又好了

### ISSUE THREAD

**Issue by kaiser20106** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#260]
### Bug 描述

开启这个功能好像跟openclash冲突了。一开断网，一关又好了

### 调试报告

Log is available at:
https://litter.catbox.moe/z9ic1j.txt
https://transfer.sh/GYo04W/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
本项目不保证与其他插件的兼容性，更不保证与这种垃圾固件的兼容性。
你安装的插件也不是由本项目直接发行，甚至没有启动。无效日志

**Comment by kaiser20106** [comment]
6,固件都存在鄙视链了？请问作者什么固件才算是正常能用你这个插件的固件
