### ISSUE TITLE
最新版本和ShadowSocksR Plus+ 有冲突，必须关闭

### ISSUE THREAD

**Issue by Rem1x-2019** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#263]
### Bug 描述

luci-app-unblockneteasemusic  版本 2.14-2
ShadowSocksR Plus+  版本  186-7
只要开启了SSR PLUS+  ，解锁就不管用，无论是GFW模式，还是绕过大陆IP
关闭就好了，
unblockneteasemusic 的日志可以看到，成功获取了音源，但是打不开，
不知道是不是被阻止了没有放行，但是我不懂这个。。所以也不知道怎么设置。。

### 调试报告

我这个版本没有调试报告。。。

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
说了命令行输入

**Comment by Rem1x-2019** [comment]
> 说了命命令输入

什么意思朋友。。我不太明白。。稍微说清楚一点，自己动手。。

openclash也是一样，必须加入网易云的规则才能用。。
