### ISSUE TITLE
后台占用

### ISSUE THREAD

**Issue by MinanaYaa** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#264]
### Bug 描述

1 root     R     1312   0%  16% {log_check.sh} /bin/sh /usr/share/unblockneteasemusic/log_check
大佬，之前因为DNS插件一只启动不了，然后最近发现风扇会经常突然起飞，然后发现后台进程里这个插件一直在运行，但是输出的log是空的，把插件都关掉了，这个进程也一直都在，kill都杀不掉

### 调试报告

https://litter.catbox.moe/z5542p.txt
https://transfer.sh/Xok2qA/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
https://downloads.immortalwrt.org/releases/21.02.6/targets/rockchip/armv8/immortalwrt-21.02.6-rockchip-armv8-friendlyarm_nanopi-r4se-squashfs-sysupgrade.img.gz
先换我们的固件试试吧

**Comment by MinanaYaa** [comment]
> https://downloads.immortalwrt.org/releases/21.02.6/targets/rockchip/armv8/immortalwrt-21.02.6-rockchip-armv8-friendlyarm_nanopi-r4se-squashfs-sysupgrade.img.gz 先换我们的固件试试吧

换固件太麻烦了，有很多其它的东西，我直接把那个删掉了发现插件也能启动，就是现在启动要启动好多次才能启动，经常运行几秒一下就挂了，感谢大佬

**Comment by 1715173329** [comment]
log_check.sh 只是一个 shell 后台自动清空日志而已，stop 之后肯定是能结束的。

现在的开发都是基于 openwrt 21.02+ 的环境做的，我不知道你那个固件从哪儿来的，甚至默认配置都有问题。

**Comment by MinanaYaa** [comment]
> log_check.sh 只是一个 shell 后台自动清空日志而已，stop 之后肯定是能结束的。
> 
> 现在的开发都是基于 openwrt 21.02+ 的环境做的，我不知道你那个固件从哪儿来的，甚至默认配置都有问题。

用的骷髅头的配置，R4SE，没办法一开始也不知道哪个固件好就随便用，用得久了弄得东西又太多了懒得换

**Comment by 1715173329** [comment]
我只能建议你换了，否则问题无法解决。
