### ISSUE TITLE
勾选启动后并没启动

### ISSUE THREAD

**Issue by ArsenZh** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#265]
### Bug 描述

在模块的启动项，进行了勾选，但并没有启动，显示unblockneteasemusic未运行

### 预期行为

启动

### 实际行为

未启动

### 调试报告

Log is available at:
https://litter.catbox.moe/zf7034.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
1. 你的 Node.js 版本太老，需要 12.x 以上
2. 你的 Node.js 二进制文件有问题，无法执行（多半是标准库问题）
3. 你的这个固件太烂
