### ISSUE TITLE
把README.md修改一下吧，pc端(windows)也需要安装证书。

### ISSUE THREAD

**Issue by Nannccyy** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#267]
### 需求描述

我之前开过Issue，但是没人解决，刚才谷歌了找到个视频，里面说如果开启插件，但windows端使用代理后仍然是无网络请求的话，也要去windows端安装证书，过程是：
1，下载证书到本地
2，双击打开证书，"选择 当前用户" 或者 "本地计算机" 都可以
3，需要选择第二个选项：将所有的证书都放入下列存储，选择“受信任的根证书颁发机构”
![image](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/assets/85016627/814cd2ca-78ae-4f5f-859c-1b79c12156fa)
然后安装完重启网易云就能在windows正常使用了。

**Comment by bauw2008** [comment]
win11 测试只需要开启代理，这个插件就能正常工作。网易云版本2.7.6，是不需要安装证书的。

**Comment by Nannccyy** [comment]
但我这边确实按我说的那样，win11平台，openwrt是istoreos版本，用的esxi虚拟的软路由，不安装证书无法使用这个插件，可能是个例吧，但是我知道在b站有个视频确实讲的就是我说的，如果使用不了就安装证书，我安装完了就能正常使用了
这个说明，可加可不加吧

**Comment by Paaaanda** [comment]
同样的问题，第一天直接开启代理就正常了，第二天启动网易云就提示无网络请求，安装证书解决，网易云版本2.10.10

**Comment by 1715173329** [comment]
你开 issue 的时候就会提醒你需要安装证书。
