### ISSUE TITLE
调整下libustream-mbedtls||PACKAGE_libustream-openssl||PACKAGE_libustream-wolfssl)排序

### ISSUE THREAD

**Issue by ilxp** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#268]
### 需求描述

大佬，能否将@(PACKAGE_libustream-mbedtls||PACKAGE_libustream-openssl||PACKAGE_libustream-wolfssl)，调整下排序啊。默认会首先安装libustream-mbedtls，然后别的插件要用到 libustream-openssl。就不能安装了，发生冲突了。

**Comment by 1715173329** [comment]
本项目 makefile 为被动依赖，即至少要求你选中其中一个才会显示。
冲突与本插件无关。
