### ISSUE TITLE
部分vip歌曲还是听不了

### ISSUE THREAD

**Issue by lyx32** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#270]
### Bug 描述

有一部分vip歌曲播放不了，鲸云音效也打开不了，打开就跳转付费页面。
我的云音乐是安卓8.6.65
![Screenshot_20230629-181133_NetEase Music](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/assets/7733528/295a66d6-fbb3-4d67-a2b1-cfc40d42e574)

### 预期行为

能够听vip歌曲

### 调试报告

https://litter.catbox.moe/ral317.txt
https://transfer.sh/463jV4zaK1/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
既然你选择了不由插件本身进行劫持，那么生效与否便很大程度上取决于你自己配置的规则。
除此之外，你的 DNS 似乎也有点问题，无法连接到网易云音乐的 HTTPDNS。

**Comment by lyx32** [comment]
目前我的问题是下面这2个吗？
1.没有开启IPSet或者HOST劫持。
2.网易的dns解析貌似有点问题。
是这样对吗？
没开启劫持是因为README.md里面没有说开启劫持。就只说了勾选启用，配好音源，就可以使用了。
感谢你的回答。

**Comment by 1715173329** [comment]
此前 Android 端有一些兼容性问题，现在应该不会出现这种情况了。

**Comment by lyx32** [comment]
> 此前 Android 端有一些兼容性问题，现在应该不会出现这种情况了。

感谢你的回复。我回家更新后试试
