### ISSUE TITLE
You must install "yt-dlp" before using the "ytdlp" source.

### ISSUE THREAD

**Issue by YuChaoM** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#273]
### Bug 描述

运行日志出现这个是正常的吗
“You must install "yt-dlp" before using the "ytdlp" source.”
还有这个“ERROR: (provider/match) Cannot read properties of undefined (reading 'list')”
我使用的是默认的音源，有时替换后的音乐不太对？
音源选择qq音乐后出现
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/usr/share/unblockneteasemusic/core/app.js:3:29270)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)

### 调试报告

使用默认的音源
Log is available at:
https://litter.catbox.moe/h5bb9j.txt
https://transfer.sh/b4be24FkyA/unm-debugging-output.txt
使用qq音乐的音源：
https://litter.catbox.moe/dnguu9.txt
https://transfer.sh/ijuC0eKeP6/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
默认音源包含 yt-dlp，openwrt 默认不提供此包，错误也很正常。部分音源的匹配度可能不高。
要使用 qq 音源必须设置 cookie。

**Comment by YuChaoM** [comment]
我Windows安装证书后谷歌浏览器访问https://music.163.com/还会出现“您的连接不是私密连接”
yt-dlp不安装会不会有太大影响，目前发现有些音乐解锁是正常的。
Migu Cookie是那个音源的。是酷狗的吗，发现切换酷狗，酷我，qq都会解锁失败，
日志报错“ERROR: (provider/match) Cannot read properties of undefined (reading 'list')”
谢谢。

**Comment by YuChaoM** [comment]
是不是有几个音源失效乐，试了好多首音乐发现都是从freetyst.nf.migu.cn这个替换的，经常出现替换的音乐不对的样子，搜索条件 歌曲名 - 歌手 专辑名，音源设置：qq kuwo kugou migu

**Comment by YuChaoM** [comment]
qq kuwo kugou这三个音源都会出现以下错误
ERROR: (provider/match) Cannot read properties of undefined (reading 'list')
    TypeError: Cannot read properties of undefined (reading 'list')
        at /usr/share/unblockneteasemusic/core/app.js:3:27473
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async u.cache (/usr/share/unblockneteasemusic/core/app.js:2:1243)
        at async m (/usr/share/unblockneteasemusic/core/app.js:3:28729)
ERROR (SongNotAvailable): (hook) This song "?" is not available in any source
    SongNotAvailable: This song "?" is not available in any source
        at b (/usr/share/unblockneteasemusic/core/app.js:3:29270)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async Promise.all (index 0)

**Comment by YuChaoM** [comment]
更新核心后返现解决了
