### ISSUE TITLE
请问有编译遇到过这个错误的吗，详见日志（gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'）

### ISSUE THREAD

**Issue by wwppp** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#276]
### 需求描述

Building targets
github.com/cnsilvan/UnblockNeteaseMusic/common
github.com/cnsilvan/UnblockNeteaseMusic/version
runtime/cgo
github.com/cnsilvan/UnblockNeteaseMusic/utils
github.com/cnsilvan/UnblockNeteaseMusic/cache
github.com/cnsilvan/UnblockNeteaseMusic/config
# runtime/cgo
gcc_mipsx.S: Assembler messages:
gcc_mipsx.S:27: Error: invalid operands `sw $18,12($29)'
gcc_mipsx.S:28: Error: invalid operands `sw $19,16($29)'
gcc_mipsx.S:29: Error: invalid operands `sw $20,20($29)'
gcc_mipsx.S:30: Error: invalid operands `sw $21,24($29)'
gcc_mipsx.S:31: Error: invalid operands `sw $22,28($29)'
gcc_mipsx.S:32: Error: invalid operands `sw $23,32($29)'
gcc_mipsx.S:33: Error: invalid operands `sw $30,36($29)'
gcc_mipsx.S:46: Error: invalid operands `jalr $20'
gcc_mipsx.S:50: Error: invalid operands `lw $18,12($29)'
gcc_mipsx.S:51: Error: invalid operands `lw $19,16($29)'
gcc_mipsx.S:52: Error: invalid operands `lw $20,20($29)'
gcc_mipsx.S:53: Error: invalid operands `lw $21,24($29)'
gcc_mipsx.S:54: Error: invalid operands `lw $22,28($29)'
gcc_mipsx.S:55: Error: invalid operands `lw $23,32($29)'
gcc_mipsx.S:56: Error: invalid operands `lw $30,36($29)'
gcc_mipsx.S:65: Error: invalid operands `lw $31,0($29)'

make[2]: *** [Makefile:74: /home/wp/x-wrt/build_dir/target-mipsel_24kc_musl/UnblockNeteaseMusic/.built] Error 1
make[2]: Leaving directory '/home/wp/x-wrt/package/luci-app-unblockneteasemusic/UnblockNeteaseMusic'time: package/luci-app-unblockneteasemusic/UnblockNeteaseMusic/compile#0.77#0.63#3.93
    ERROR: package/luci-app-unblockneteasemusic/UnblockNeteaseMusic failed to build.
make[1]: *** [package/Makefile:120: package/luci-app-unblockneteasemusic/UnblockNeteaseMusic/compile] Error 1
make[1]: Leaving directory '/home/wp/x-wrt'
make: *** [/home/wp/x-wrt/include/toplevel.mk:232：package/luci-app-unblockneteasemusic/compile]  错 误 2

**Comment by 1715173329** [comment]
你的问题与本项目无任何关联。
