### ISSUE TITLE
不能解锁啊。帮忙看一眼，谢谢了

### ISSUE THREAD

**Issue by zxymdaddy** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#284]
### Bug 描述

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
UnblockNetease
	

### 预期行为

插件怎么设置都不生效。

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.9.0-rc7-aml-s812",
	"kernel":5.10.187-1
	"hostname": "OpenWrt",
	"system": "ARMv7 Processor rev 1 (v7l)",
	"model": "BugScaner",
	"board_name": "BugScaner,OneCloud",
	"release": {
		"distribution": "1004",
		"version": "23.05.0-rc2",
		"revision": "07.12.2023",
		"target": "meson/meson8b",
		"description": "OpenWrt 07.12.2023 by Kiddin'"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: arm_cortex-a5_vfpv4
Size: 8392
Filename: uclient-fetch_2023-04-13-007d9454-1_arm_cortex-a5_vfpv4.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1691281018

Package: libustream-wolfssl20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libwolfssl5.6.3.e624513f
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: arm_cortex-a5_vfpv4
Size: 4294
Filename: libustream-wolfssl20201210_2023-02-25-498f6e26-1_arm_cortex-a5_vfpv4.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libopenssl3
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: arm_cortex-a5_vfpv4
Size: 4637
Filename: libustream-openssl20201210_2023-02-25-498f6e26-1_arm_cortex-a5_vfpv4.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: install user installed
Section: libs
Architecture: arm_cortex-a5_vfpv4
Size: 4390
Filename: libustream-mbedtls20201210_2023-02-25-498f6e26-1_arm_cortex-a5_vfpv4.ipk
Description: ustream SSL Library (mbedtls)
Installed-Time: 1691281018

Package: wget-ssl
Version: 1.21.3-3
Depends: libc, libpcre2, zlib, libopenssl3, librt
Provides: gnu-wget, wget
Status: unknown ok not-installed
Section: net
Architecture: arm_cortex-a5_vfpv4
Size: 203541
Filename: wget-ssl_1.21.3-3_arm_cortex-a5_vfpv4.ipk
Description: Wget is a network utility to retrieve files from the Web using http and ftp, the two most widely used Internet protocols. It works non-interactively, so it will work in the background, after having logged off. The program supports recursive retrieval of web-authoring pages as well as ftp sites -- you can use wget to make mirrors of archives and home pages or to travel the Web like a WWW robot. This package is built with SSL support.

Package: wget-ssl
Version: 1.21.3-2
Depends: libc, libpcre, zlib, libopenssl3, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1691281018

--2023-09-08 14:47:41--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 20.205.243.168
Connecting to api.github.com|20.205.243.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... ..........  183K
    50K .......... .......... .......... .......... ..........  169K
   100K .......... .......... ........                          539K=0.6s

2023-09-08 14:47:45 (207 KB/s) - written to stdout [131512]

014b7150b2ab75c4c96c6e942c4a09500ee2d3bd

Node.js info:
Package: node
Version: v18.17.1-1
Depends: libc, libstdcpp6, libopenssl3, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: arm_cortex-a5_vfpv4
Size: 11591351
Filename: node_v18.17.1-1_arm_cortex-a5_vfpv4.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1694143364

Node.js is placed at /usr/bin/node
Node.js version: v18.17.1

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: git-24.231.52046-6266f45
Depends: libc, dnsmasq-full, UnblockNeteaseMusic, node
Status: install user installed
Section: luci
Architecture: all
Size: 14159
Filename: luci-app-unblockneteasemusic_git-24.231.52046-6266f45_all.ipk
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Description: LuCI support for UnblockNeteaseMusic (JavaScript)
Installed-Time: 1694143375

-rw-r--r--    1 root     root         363 Sep  8 14:47 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 1001     ntp         8.5K Aug 19 22:27 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwx------    2 root     root        4.0K Sep  8 09:44 core
-rw-------    1 root     root          41 Sep  8 09:44 core_local_ver
-rwxr-xr-x    1 1001     ntp         4.7K Aug 19 22:27 debugging.sh
-rwxr-xr-x    1 1001     ntp          392 Aug 19 22:27 log_check.sh
-rw-r--r--    1 1001     ntp         1.7K Aug 19 22:27 nftables.ut
-rwxr-xr-x    1 1001     ntp         3.0K Aug 19 22:27 update.sh

config unblockneteasemusic 'config'
	option enable '1'
	option disable_upgrade_check '1'
	option auto_update '1'
	option update_time '3'
	option replace_music_source 'dont_replace'
	option search_album '1'
	option block_ads '1'
	option local_vip 'svip'
	list music_source 'kuwo'
	list music_source 'migu'
	option follow_source_order '1'
	option enable_flac '1'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 014b7150b2ab75c4c96c6e942c4a09500ee2d3bd
Core version: 0.27.4
-rw-------    1 root     root      220.0K Sep  8 09:44 app.js
-rw-------    1 root     root      185.7K Sep  8 09:44 bridge.js
-rw-------    1 root     root         790 Sep  8 09:44 ca.crt
-rw-------    1 root     root         839 Sep  8 09:44 server.crt
-rw-------    1 root     root         359 Sep  8 09:44 server.key

Netease networking info:
< Location: http://m10.music.126.net/20230908151249/c7a2e654d2cc53a8af7924edbab1231a/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["183.136.182.20","115.238.119.69","45.127.129.53","59.111.19.99","193.112.159.225","47.100.127.239","39.105.175.128","118.24.63.156","39.105.63.80","182.92.170.253"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      9295/node
tcp        0      0 :::5201                 :::*                    LISTEN      9295/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 9296,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 9295,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-o",
					"kuwo",
					"migu",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"BLOCK_ADS": "true",
					"DISABLE_UPGRADE_CHECK": "true",
					"ENABLE_FLAC": "true",
					"ENABLE_LOCAL_VIP": "svip",
					"FOLLOW_SOURCE_ORDER": "true",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"SEARCH_ALBUM": "true",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
/usr/share/unblockneteasemusic/debugging.sh: line 75: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 77: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 79: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 81: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 83: nft: not found

dhcp-option=252,http://192.168.1.111:5200/proxy.pac
nftset=/.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":1,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2ZyZWV0eXN0Lm5mLm1pZ3UuY24vcHVibGljL3Byb2R1Y3Q3dGgvcHJvZHVjdEIxMi8yMDIwLzA1LzE2MjAvMjAyMCVFNSVCOSVCNDA1JUU2JTlDJTg4MTYlRTYlOTclQTUwNyVFNyU4MiVCOTQ0JUU1JTg4JTg2JUU2JTg5JUI5JUU5JTg3JThGJUU5JUExJUI5JUU3JTlCJUFFU29ueU9yY2hhcmQ0MTUlRTklQTYlOTYtMS8lRTYlQTAlODclRTYlQjglODUlRTklQUIlOTglRTYlQjglODUvTVAzXzEyOF8xNl9TdGVyby82OTkzODc0VzlVQjIwMzgyMi5tcDM_Y2hhbm5lbGlkPTAyJm1zaXNkbj1iYmZhN2I1YS0xMzNiLTRjNzItYjBjOC05ZjRhNTc3MmEwM2YmVGltPTE2OTQxNTU5NzM5NjMmS2V5PTc2M2ZlZmM4MGIwOWQwNzQ=/33190502.mp3","br":128000,"size":3016872,"md5":"eb4dff20d5b64d2a80a9195e09ac581e","code":200,"expi":1200,"type":"mp3","gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":1,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
ERROR: (provider/match) socket hang up
    Error: socket hang up
        at connResetException (node:internal/errors:720:14)
        at Socket.socketOnEnd (node:_http_client:525:23)
        at Socket.emit (node:events:526:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    code: ECONNRESET
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://freetyst.nf.migu.cn/public/product7th/productB12/2020/05/1620/2020%E5%B9%B405%E6%9C%8816%E6%97%A507%E7%82%B944%E5%88%86%E6%89%B9%E9%87%8F%E9%A1%B9%E7%9B%AESonyOrchard415%E9%A6%96-1/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/6993874W9UB203822.mp3?channelid=02&msisdn=bbfa7b5a-133b-4c72-b0c8-9f4a5772a03f&Tim=1694155973963&Key=763fefc80b09d074"

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
你装的插件根本不是由本项目直接发行的，当然不能用。
自己去 release 重新下即可。

**Comment by zxymdaddy** [comment]
这个不对吗？我在官网下载的
![image](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/assets/35829110/cb449015-b246-477f-a5d7-59051dbe51f3)
