### ISSUE TITLE
PC和安卓均无法使用

### ISSUE THREAD

**Issue by lj0307222** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#286]
### Bug 描述

pc设置代理也无法使用，安卓wifi设置代理可以使用

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.4.255",
	"hostname": "OpenWrt",
	"system": "Intel(R) Celeron(R) CPU  J1900  @ 1.99GHz",
	"model": "To be filled by O.E.M. To be filled by O.E.M.",
	"board_name": "to-be-filled-by-o-e-m-to-be-filled-by-o-e-m",
	"release": {
		"distribution": "ImmortalWrt",
		"version": "21.02-SNAPSHOT",
		"target": "x86/64",
		"description": "  @ OpenWrt "
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1694064929

Package: libustream-openssl20201210
Version: 2022-12-08-9217ab46-1
Depends: libc, libubox20210516, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: x86_64
Installed-Time: 1694064929

Package: wget-ssl
Version: 1.21.1-1
Depends: libc, libpcre, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: x86_64
Installed-Time: 1694064929

--2023-09-16 11:43:51--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 192.30.255.116
Connecting to api.github.com|192.30.255.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... ..........  661K
    50K .......... .......... .......... .......... .......... 1.29M
   100K .......... .......... ........                         12.6M=0.1s

2023-09-16 11:43:53 (1.08 MB/s) - written to stdout [131512]

014b7150b2ab75c4c96c6e942c4a09500ee2d3bd

Node.js info:
Package: node
Version: v16.20.2-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libatomic1
Status: install user installed
Architecture: x86_64
Installed-Time: 1694064929

Node.js is placed at /usr/bin/node
Node.js version: v16.20.2

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.2
Depends: libc, dnsmasq-full, ipset, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1694064929

-rw-r--r--    1 root     root         283 Sep 16 02:28 /etc/config/unblockneteasemusic
-rwxrwxr-x    1 root     root        8.4K Sep  7 13:35 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        3.4K Sep 16 02:09 core
-rw-r--r--    1 root     root          41 Sep 16 02:09 core_local_ver
-rwxrwxr-x    1 root     root        4.8K Sep  7 13:35 debugging.sh
-rwxrwxr-x    1 root     root         392 Sep  7 13:35 log_check.sh
-rwxrwxr-x    1 root     root        3.0K Sep  7 13:35 update.sh

config unblockneteasemusic 'config'
	option disable_upgrade_check '1'
	option auto_update '1'
	option update_time '3'
	option enable '1'
	option replace_music_source 'dont_replace'
	option block_ads '1'
	option local_vip 'svip'
	list music_source 'kuwo'
	list music_source 'kugou'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 014b7150b2ab75c4c96c6e942c4a09500ee2d3bd
Core version: 0.27.4
-rw-r--r--    1 root     root      220.0K Sep 16 02:09 app.js
-rw-r--r--    1 root     root      185.7K Sep 16 02:09 bridge.js
-rw-r--r--    1 root     root         790 Sep 16 02:09 ca.crt
-rw-r--r--    1 root     root         839 Sep 16 02:09 server.crt
-rw-r--r--    1 root     root         359 Sep 16 02:09 server.key

Netease networking info:
< Location: http://m10.music.126.net/20230916120854/1ab8e44c1e2d40017f8e9108e9186d3d/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.238.119.69","183.136.182.20","45.127.129.53","59.111.19.99","39.105.63.80","118.24.63.156","182.92.170.253","39.105.175.128","193.112.159.225","47.100.127.239"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      16378/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      16378/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 16379,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 16378,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"0.0.0.0",
					"-p",
					"5200:5201",
					"-o",
					"kuwo",
					"kugou",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"BLOCK_ADS": "true",
					"DISABLE_UPGRADE_CHECK": "true",
					"ENABLE_LOCAL_VIP": "svip",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 976
References: 1
Number of entries: 17
Members:
118.24.63.156
47.100.127.239
115.238.119.69
59.111.19.33
59.111.160.195
182.92.170.253
115.238.119.68
175.6.29.166
115.238.119.67
59.111.19.99
183.136.182.18
193.112.159.225
39.105.63.80
183.136.182.20
45.127.129.53
183.136.182.19
39.105.175.128

Name: acl_neteasemusic_http
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 208
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 208
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.0.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":1,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2VwLnN5Y2RuLmt1d28uY24vZTVlNjZjYjkwNWRlYzUxMGY3OWQ3NTQwMjI2NWI1MDIvNjUwNTI0N2YvcmVzb3VyY2UvbjEvNzcvMjAvMzQ1MDg3MzgwMS5tcDM_Yml0cmF0ZQ==/33190502.mp3","br":128000,"size":4203542,"md5":"89c70fd145d803aff13626bb3eddc9fa","code":200,"expi":1200,"type":"mp3","gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":1,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0}],"code":200}
INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://ep.sycdn.kuwo.cn/e5e66cb905dec510f79d75402265b502/6505247f/resource/n1/77/20/3450873801.mp3?bitrate"

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
iptables 版不支持劫持 ipv6，需要自行过滤 v6 地址。不会再考虑支持，如有需要切换新版 fw4 即可。
