### ISSUE TITLE
使用音源接口 网易云音乐（pyncmd）听部分歌曲无法解锁

### ISSUE THREAD

**Issue by HOursH** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#287]
### Bug 描述

插件和核心都更新到最新版了，2，3周之前开始pyncmd就无法使用，如果尝试切换成其他音频接口，有些歌播放不正确，比如有些歌在网易云是正常的，但是在酷狗，咪咕，等等里面，都是其他版本的。
如果获取失败，就会报错：
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

### 调试报告

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
INFO: (provider/match) Replaced: [520242286] Can I Get a Witness
    audioId: 520242286
    songName: "Can I Get a Witness"
    url: "http://m7.music.126.net/20230928140839/cd727900c30277c19b474cebc00a9678/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/2870483831/ea72/ffd8/bfe0/c83d986c8a58d199966c5c1e4cd7285e.mp3"
INFO: (provider/match) Replaced: [1307980963] Missin You Crazy
    audioId: 1307980963
    songName: "Missin You Crazy"
    url: "http://m801.music.126.net/20230928140840/385b847f378fef325f522af55e7401d3/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/8977398241/acef/81e6/4ebb/8e45e0bbc481637465c5cf3881ecc7d0.mp3"
INFO: (provider/match) Replaced: [1481047138] Dirty
    audioId: 1481047138
    songName: "Dirty"
    url: "http://m701.music.126.net/20230928140841/025e4ff8eda99f68b8ebdcb8deab40e5/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/17178239022/8811/43c2/7a7b/74cb65f6d007da54c14bfb847fd413b7.mp3"
INFO: (provider/match) Replaced: [2027162554] Moonlight
    audioId: 2027162554
    songName: "Moonlight"
    url: "http://m801.music.126.net/20230928140841/04391d8d799d29b6b6b99f81c205b615/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/25453985530/4135/c297/34dc/57d42e4a684c715e9f6118adcd7706de.mp3"
INFO: (provider/match) Replaced: [2053580372] Sandman
    audioId: 2053580372
    songName: "Sandman"
    url: "http://m701.music.126.net/20230928140850/312cbf3d0fea0fe2710444a5b152e409/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/28531872037/8a50/5238/10bc/f7f14ebf6c8569f6df0e93697b0168ee.mp3"
INFO: (provider/match) Replaced: [1447521944] RAW
    audioId: 1447521944
    songName: "RAW"
    url: "http://m7.music.126.net/20230928140855/db3efc0fd3ddd3b7a0e7f031841a12dd/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/2493512546/ccc8/8d4a/4ad5/39df5929d60fbee19abb4f93ffa8188a.mp3"
INFO: (provider/match) Replaced: [1359710017] Sick Of You
    audioId: 1359710017
    songName: "Sick Of You"
    url: "http://m801.music.126.net/20230928140857/b295d96757ee8742b0be2f308901714d/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/19512041085/4b71/1583/c51d/1f351ae6a9550342b1662bf05a3fa32f.mp3"
INFO: (provider/match) Replaced: [2002753297] 123
    audioId: 2002753297
    songName: "123"
    url: "http://m801.music.126.net/20230928140900/2a2da8d40b288091337cb36519dec936/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/22934876036/a346/c1c9/f1c2/8e55d1dc5f4414bffbdb5c57936ff349.mp3"
INFO: (provider/match) Replaced: [2040474776] Vroom
    audioId: 2040474776
    songName: "Vroom"
    url: "http://m801.music.126.net/20230928140906/ead67c514f32faa0c429d2f60bccbc09/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/26932535506/7cea/ba99/12a2/d5a0b6ac85c408cc878c4228b84e4ada.mp3"
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
INFO: (provider/match) Replaced: [5257138] 屋顶
    audioId: 5257138
    songName: "屋顶"
    url: "http://m701.music.126.net/20230928140954/c59010885367c3f8ff5d9d4fa588de49/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/7150237053/b797/13ed/4ef6/ecc932b8c58ff0c5c76c9c5aaeb78f1e.mp3"
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by ITManCHINA** [comment]
一样的问题，而且pyncmd无法解析flac了

**Comment by 1715173329** [comment]
Fixed
