### ISSUE TITLE
公网访问问题

### ISSUE THREAD

**Issue by shugo-chara** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#289]
### 需求描述

在nas虚拟机里的openwrt上部署了服务一切正常，同一局域网设备访问也正常。
nas做了ddns，可以外网通过ss和ddns的端口连通家里内网环境。

请问如何能让手机在外网直接访问内网openwrt上的网易云解锁服务。
尝试先用ss连接到家里内网，再通过http服务访问openwrt上的网易云解锁但行不通。
openwrt的网易云服务是本地ip：端口，请教下怎么能不通过vps而直接在外网访问它。

**Comment by ITManCHINA** [comment]
可以尝试一下用域名+公网IP+端口转发的方式使用

**Comment by svcvit** [comment]
把openwrt的5200暴露给公网，然后手机代理用socket到这个地址，就可以用。但是太不安全了。

**Comment by ShenKeeeew** [comment]
tailscale跑个内网，然后用exit node模式可以解决

**Comment by 1715173329** [comment]
开进阶模式即可，不推荐直接暴露在公网。
