### ISSUE TITLE
无法正常编译：fatal error: bits/c++config.h: No such file or directory

### ISSUE THREAD

**Issue by AndyLin2020** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#290]
### Bug 描述

ASUS ACRH-17， 内核版本：5.4.240 

### 调试报告

In file included from /usr/include/c++/9/memory:62,
                 from ../deps/icu-small/source/common/unicode/localpointer.h:45,
                 from ../deps/icu-small/source/common/cmemory.h:33,
                 from ../deps/icu-small/source/common/cstring.h:31,
                 from ../deps/icu-small/source/tools/toolutil/flagparser.cpp:11:
/usr/include/c++/9/bits/stl_algobase.h:59:10: fatal error: bits/c++config.h: No such file or directory
   59 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
tools/icu/icutools.host.mk:580: recipe for target '/home/andy/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/node-v16.19.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/flagparser.o' failed
make[5]: *** [/home/andy/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/node-v16.19.1/out/Release/obj.host/icutools/deps/icu-small/source/tools/toolutil/flagparser.o] Error 1
Makefile:113: recipe for target 'node' failed
make[4]: *** [node] Error 2
make[4]: Leaving directory '/home/andy/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/node-v16.19.1'
Makefile:222: recipe for target '/home/andy/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/node-v16.19.1/.built' failed
make[3]: *** [/home/andy/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/node-v16.19.1/.built] Error 2
make[3]: Leaving directory '/home/andy/lede/feeds/packages/lang/node'
time: package/feeds/packages/node/compile#191.16#40.27#228.06
    ERROR: package/feeds/packages/node failed to build.

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
nodejs 依赖问题，无本项目无关。
