### ISSUE TITLE
帮忙看看啥问题，谢谢

### ISSUE THREAD

**Issue by lizhiwei8061** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#293]
### Bug 描述

插件运行成功，但是不生效

### 预期行为

略

### 实际行为

略

### 复现步骤

略

### 调试报告

https://transfer.sh/odRPL6vT1x/unm-debugging-output.txt
https://litter.catbox.moe/n9mr3l.txt

### 其他信息

略

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [x] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
小鸡过河的垃圾固件，免问即可。

**Comment by lizhiwei8061** [comment]
> 小鸡过河的垃圾固件，免问即可。

这样 啊
