### ISSUE TITLE
开启AdGuard home后，插件失效

### ISSUE THREAD

**Issue by Aluan1996** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#295]
### Bug 描述

只要开启了AdGuard Home 去广告插件，解锁灰色歌曲会失效（vip歌曲就没法听了，但正常显示伪装vip图标。）关闭AdGuard home插件后，解锁灰色歌曲就正常使用了。已经把AdGuard Home 里所有广告拦截规则关闭，但是只要开启AdGuard Home插件， 解灰插件就会失效。关闭AdGuard Home ，解灰插件就正常，请问下怎么解决？谢谢

### 调试报告

Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain friendsoftibet.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain cosmic.monar.ch
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain churchinhongkong.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain londonchinese.ca
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain libertytimes.com.tw
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain de-sci.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain discordapp.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain vn.hao123.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain seezone.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain igotmail.com.tw
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain vital247.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain iipdigital.usembassy.gov
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain twittbot.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain ienergy1.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain pornrapidshare.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain business-humanrights.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain xxlmovies.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: more servers are defined but not logged
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: reading /tmp/resolv.conf.d/resolv.conf.auto
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain gmhz.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain archives.gov.tw
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain modernchinastudies.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain proxydns.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain twitter.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain bnrmetal.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain timesofindia.indiatimes.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain internetdefenseleague.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain tuidang.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain taiwandaily.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain sixth.biz
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain savetibet.de
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain springwood.me
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain friendsoftibet.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain cosmic.monar.ch
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain churchinhongkong.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain londonchinese.ca
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain libertytimes.com.tw
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain de-sci.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain discordapp.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain vn.hao123.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain seezone.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain igotmail.com.tw
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain vital247.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain iipdigital.usembassy.gov
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain twittbot.net
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain ienergy1.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain pornrapidshare.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain business-humanrights.org
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using nameserver 127.0.0.1#15353 for domain xxlmovies.com
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: more servers are defined but not logged
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for test
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for onion
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for localhost
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for local
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for invalid
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for bind
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: using only locally-known addresses for lan
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: read /etc/hosts - 12 names
Sun Jan 14 00:21:17 2024 daemon.info dnsmasq[1]: read /tmp/hosts/dhcp.cfg01411c - 4 names
Sun Jan 14 00:21:17 

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by Mousehk** [comment]
同样的问题，不开adg一点问题没有

**Comment by wrb233** [comment]
这几个比较火的插件作者就不能沆瀣一气一下下吗，直接一个ipk搞定，无需任何配置

**Comment by XDreamc** [comment]
解决方案。在adg dns 设置里面提前设置[/music.163.com/]127.0.0.1:5337   5337 为Dnsmasq 设置的端口 默认为53。 这样就可以。当然如果对防火墙规则熟悉的话 也可以手动设置防火墙规则http/https 流量走 5200 和 5201 。

不过作者还有一个小bug 没解决。就是有时候 最后开启网易云插件的话。有时候 防火墙规则会注册不上去。需要手动注册下。这个看下作者能否解决下

**Comment by 1715173329** [comment]
本项目不保证与其他插件兼容性。
