### ISSUE TITLE
启用插件后，客户端提示网络连接失败！

### ISSUE THREAD

**Issue by a569491906** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#296]
### Bug 描述

原先在第三方仓库拉取编译的完全不起作用， 然后来到了这里编译完插件似乎是有用了，但音乐客户端提示网络连接失败。

### 调试报告

https://transfer.sh/RfCcK0GsUH/unm-debugging-output.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by a569491906** [comment]
这是插件首次运行的日志， 网易客户端在第一次启动时有网络，虽然歌曲的vip标识消失，依旧只能播放一小段，网易客户端第二次启动后就连接不到网络了。
Succeeded in updating core.
Current core version: 2dbdab5ca29fde88d81ca8add474131a3fe3e7c3.

INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

**Comment by edwinhuish** [comment]
同样的问题，提示网络连接失败

**Comment by SakomizuKey** [comment]
同样的问题。x86 J1900

**Comment by morytyann** [comment]
证书过期了，自己重新签一个吧

**Comment by edwinhuish** [comment]
@morytyann 请问自签后需要怎么处理呢？尝试过自签证，但之后打开 music.163.com 仍旧提示不安全，证书无效。选择安装证书问题依旧。

操作系统是 win10，浏览器是 edge

**Comment by morytyann** [comment]
@edwinhuish 在插件的配置页勾选`启用进阶设置`，会多出一些设置，最下面`自签发证书公钥位置`和`自签发证书私钥位置`选择`/usr/share/unblockneteasemusic/server.xxx`，就会出现上传公钥和上传私钥的按钮，都上传成功后重启一下服务就可以了

**Comment by edwinhuish** [comment]
按照这个教程 https://github.com/nondanee/UnblockNeteaseMusic/issues/48#issuecomment-477870013 创建了自签证书，上传后还是显示不安全。

请问你的自签证书是怎么签的呢？

**Comment by morytyann** [comment]
我也是这么签的，你看一下`music.163.com`的证书是不是你新签的，你是Edge浏览器，按下面的步骤看看
打开`music.163.com` -> 点击地址栏前面的锁 -> 点击连接安全 -> 点击右上角的证书图标

**Comment by edwinhuish** [comment]
确实是我新签署的，但是无效，不明所以。。。。

![image](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/assets/5207925/06a1b062-ddb9-4824-8360-e8bfc44136ac)

**Comment by morytyann** [comment]
浏览器具体报什么错？
话说你是不是没有删除之前安装的证书？

**Comment by edwinhuish** [comment]
浏览器报错如下:

![image](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/assets/5207925/d86dbf66-bc73-404d-9eb2-a2219c4ea14b)

确实是没有删除之前安装的证书，不过我看它应用的是我最后的证书，时间日期也都对得上。。。。。 现在全删了，一样的问题

**Comment by morytyann** [comment]
装一下新的证书`ca.crt`再试试

**Comment by edwinhuish** [comment]
抱歉，搞了个乌龙，没注意到它这句话，我本机一直装 `server.crt`，而不是 `ca.crt`，搞错了。。。

![image](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/assets/5207925/55355cf4-0a03-4972-9ec5-ff2c964497d1)

**Comment by a569491906** [comment]
> 证书过期了，自己重新签一个吧

按照步骤自签了证书，也就是启用了进阶设置，网易云音乐的网站可以正常打开，但插件对网易云音乐客户端没有任何作用。如果去openwrt证书相关目录删除原先上传的证书，网易云音乐客户端就没有了网络，网站也打不开。。。  你觉得哪里还有问题？没弄过证书自签，只是在openwrt终端按照步骤生成server证书及server.key并放到了指定目录。

**Comment by morytyann** [comment]
高级设置默认不劫持，劫持方法选`使用IPSet`重启再试试（或者在客户端设置代理，地址是路由器IP，端口5200）

**Comment by morytyann** [comment]
还有`ca.crt`证书记得安装

**Comment by a569491906** [comment]
把openwrt里面的server证书及server.key删掉（后面验证了上传文件，开启ipset劫持，并在pc端装证书也可正常使用）然后在pc端装ca证书可以正常使用了。。。。 我想让openwrt直接劫持而pc端什么也不用做，能实现吗？ 目前好像重点是在pc端的ca证书

**Comment by a569491906** [comment]
安卓端的需要安装证书吗？ 还是可以直接用

**Comment by morytyann** [comment]
看其他issue和项目readme，PC端好像可以不装证书（可以降级到http，不过还是推荐装一个），Android应该是要装的

**Comment by a569491906** [comment]
> 看其他issue和项目readme，PC端好像可以不装证书（可以降级到http，不过还是推荐装一个），Android应该是要装的

嗯，感谢耐心回复

**Comment by 553531284** [comment]
同样出现了该问题，后面发现音源接口我手动选了一个导致的。

**Comment by catfishuang** [comment]
问个问题哈，插件我是自己连同openwrt固件一起编译的，启动运行正常，在安卓手机上安装9.0.20版本，第一次启动登录后，可以解锁灰色歌曲。退出后再打开网易云音乐app，登录时显示失败，有时候不显示失败，但是再也无法解锁了，也就是只有安装后的第一次登录可以，这是啥鬼？
