### ISSUE TITLE
开了之后会影响一些需要魔法的网站

### ISSUE THREAD

**Issue by MinanaYaa** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#301]
### Bug 描述

不每天去ping手动填一下DNS的话就会出现一些奇怪的DNS解析问题，一些需要魔法的网站会打不开，不知道这软件的配置文件在哪啊。etc里面没有，写了个每天自动ping DNS的脚本，结果找不到地方更新进去，一定要手动填吗，要不大佬给这插件加这个功能

### 调试报告

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_packages https://archive.openwrt.org/releases/23.05.0/packages/aarch64_generic/packages/). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_base https://archive.openwrt.org/releases/23.05.0/packages/aarch64_generic/base/). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_luci https://archive.openwrt.org/releases/23.05.0/packages/aarch64_generic/luci/). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_routing https://archive.openwrt.org/releases/23.05.0/packages/aarch64_generic/routing/). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_base http://mirrors.cloud.tencent.com/openwrt/releases/23.05.0/packages/aarch64_generic/base). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_luci http://mirrors.cloud.tencent.com/openwrt/releases/23.05.0/packages/aarch64_generic/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_packages http://mirrors.cloud.tencent.com/openwrt/releases/23.05.0/packages/aarch64_generic/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_routing http://mirrors.cloud.tencent.com/openwrt/releases/23.05.0/packages/aarch64_generic/routing). Skipping.
Version: 2.14-3
Depends: libc, dnsmasq-full, ipset, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1693896058

-rw-rw-r--    1 root     root         658 Apr 21 19:58 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Jul 22  2023 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    5 root     root        3.4K Mar 18 16:48 core
-rw-r--r--    1 root     root          41 Mar 18 16:48 core_local_ver
-rwxr-xr-x    1 root     root        4.8K Jul 22  2023 debugging.sh
-rwxr-xr-x    1 root     root         392 Jul 22  2023 log_check.sh
drwxrwxr-x    1 root     root        3.4K Sep  5  2023 rules
-rwxr-xr-x    1 root     root        2.9K Jul 22  2023 update.sh

config unblockneteasemusic 'config'
        option disable_upgrade_check '1'
        option use_custom_cookie '0'
        option search_album '0'
        option auto_update '0'
        option replace_music_source 'lower_than_999kbps'
        option block_ads '1'
        option enable_flac '1'
        option select_max_br '1'
        option enable '1'
        option follow_source_order '0'
        option local_vip 'svip'
        option music_source 'kuwo kugou migu'
        option advanced_mode '1'
        option log_level 'info'
        option endpoint_url 'https://music.163.com'
        option pub_access '0'
        option strict_mode '0'
        option http_port '5200'
        option https_port '5201'
        option hijack_ways 'dont_hijack'
        option netease_server_ip '112.13.119.53'

UnblockNeteaseMusic Node.js info:
Git HEAD version: e6303e0a93bcd8081c82e6fc6042d5674eeabb2b
Core version: 0.27.6
-rw-r--r--    1 root     root      220.2K Mar 18 16:48 app.js
-rw-r--r--    1 root     root      185.4K Mar 18 16:48 bridge.js
-rw-r--r--    1 root     root         790 Mar 18 16:48 ca.crt
-rw-r--r--    1 root     root         932 Mar 18 16:48 server.crt
-rw-r--r--    1 root     root         359 Mar 18 16:48 server.key

Netease networking info:
< Location: http://m10.music.126.net/20240421202730/9967878ac9fd322339379df56df5589e/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["117.147.199.60","112.13.119.53","59.111.19.99","45.127.129.53","118.24.63.156","182.92.170.253","39.105.63.80","47.100.127.239","193.112.159.225","39.105.175.128"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 0.0.0.0:5200            0.0.0.0:*               LISTEN      14646/node
tcp        0      0 0.0.0.0:5201            0.0.0.0:*               LISTEN      14646/node

PROCD running info:
{
        "unblockneteasemusic": {
                "instances": {
                        "log-check": {
                                "running": true,
                                "pid": 14647,
                                "command": [
                                        "/usr/share/unblockneteasemusic/log_check.sh"
                                ],
                                "term_timeout": 5,
                                "respawn": {
                                        "threshold": 3600,
                                        "timeout": 5,
                                        "retry": 5
                                }
                        },
                        "unblockneteasemusic": {
                                "running": true,
                                "pid": 14646,
                                "command": [
                                        "node",
                                        "/usr/share/unblockneteasemusic/core/app.js",
                                        "-a",
                                        "0.0.0.0",
                                        "-p",
                                        "5200:5201",
                                        "-o",
                                        "kuwo",
                                        "kugou",
                                        "migu",
                                        "-e",
                                        "https://music.163.com",
                                        "-f",
                                        "112.13.119.53"
                                ],
                                "term_timeout": 5,
                                "env": {
                                        "BLOCK_ADS": "true",
                                        "DISABLE_UPGRADE_CHECK": "true",
                                        "ENABLE_FLAC": "true",
                                        "ENABLE_LOCAL_VIP": "svip",
                                        "LOG_FILE": "/var/run/unblockneteasemusic/run.log",
                                        "LOG_LEVEL": "info",
                                        "MIN_BR": "600000",
                                        "SELECT_MAX_BR": "true",
                                        "SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
                                        "SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
                                },
                                "respawn": {
                                        "threshold": 3600,
                                        "timeout": 5,
                                        "retry": 5
                                }
                        }
                },
                "triggers": [
                        [
                                "config.change",
                                [
                                        "if",
                                        [
                                                "eq",
                                                "package",
                                                "unblockneteasemusic"
                                        ],
                                        [
                                                "run_script",
                                                "/etc/init.d/unblockneteasemusic",
                                                "reload"
                                        ]
                                ],
                                1000
                        ]
                ]
        }
}

Firewall info:
Chain "netease_cloud_music" not found.

Table "neteasemusic" not found.

Table "acl_neteasemusic_http" not found.

Table "acl_neteasemusic_https" not found.

cat: can't open '/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf': No such file or directory

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2x3LnN5Y2RuLmt1d28uY24vMGRiNzE0ODA5MTNkOWRkOTc0ODM1OTE5MzUwNTJhNTYvNjYyNTAwNTgvcmVzb3VyY2UvMzAxMDYvdHJhY2ttZWRpYS9GMDAwMDA0VXN0RjEzdE1va1cuZmxhYz9iaXRyYXRl/33190502.flac","br":999000,"size":30395200,"md5":"d9e04fa957eaf28533afc79b96adec69","code":200,"expi":1200,"type":"flac","gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null}],"code":200}
INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://lw.sycdn.kuwo.cn/0db71480913d9dd97483591935052a56/66250058/resource/30106/trackmedia/F000004UstF13tMokW.flac?bitrate"

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
既然指定了 dont_hijack，本项目只会启动主进程，不会触碰系统任何设置。
