### ISSUE TITLE
不能用的原因是什么

### ISSUE THREAD

**Issue by nicbest** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#303]
### Bug 描述

电脑和安卓端都无法使用，装了yt-dlp也不行

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "6.1.82",
	"hostname": "OpenWrt",
	"system": "ARMv8 Processor rev 4",
	"model": "TP-Link TL-XDR6088",
	"board_name": "tplink,tl-xdr6088",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "1004",
		"version": "23.05.3",
		"revision": "03.30.2024",
		"target": "mediatek/filogic",
		"description": "OpenWrt 03.30.2024 by Kiddin'"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_cortex-a53
Size: 8331
Filename: uclient-fetch_2023-04-13-007d9454-1_aarch64_cortex-a53.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1711747741

Package: libustream-wolfssl20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libwolfssl5.6.4.e624513f
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5197
Filename: libustream-wolfssl20201210_2023-02-25-498f6e26-1_aarch64_cortex-a53.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libopenssl3
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5649
Filename: libustream-openssl20201210_2023-02-25-498f6e26-1_aarch64_cortex-a53.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: install user installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5544
Filename: libustream-mbedtls20201210_2023-02-25-498f6e26-1_aarch64_cortex-a53.ipk
Description: ustream SSL Library (mbedtls)
Installed-Time: 1711747741

Package: wget-ssl
Version: 1.21.4-1
Depends: libc, libpcre2, zlib, libopenssl3, librt
Provides: gnu-wget, wget
Status: install user installed
Section: net
Architecture: aarch64_cortex-a53
Size: 218813
Filename: wget-ssl_1.21.4-1_aarch64_cortex-a53.ipk
Description: Wget is a network utility to retrieve files from the Web using http and ftp, the two most widely used Internet protocols. It works non-interactively, so it will work in the background, after having logged off. The program supports recursive retrieval of web-authoring pages as well as ftp sites -- you can use wget to make mirrors of archives and home pages or to travel the Web like a WWW robot. This package is built with SSL support.
Installed-Time: 1711747741

--2024-04-28 22:35:30--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 20.205.243.168
Connecting to api.github.com|20.205.243.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... .......... 45.7K
    50K .......... .......... .......... .......... .......... 93.4K
   100K .......... .......... .......... ...                   89.0K=2.0s

2024-04-28 22:35:36 (66.5 KB/s) - written to stdout [136424]

e6303e0a93bcd8081c82e6fc6042d5674eeabb2b

Node.js info:
Package: node
Version: v18.19.1-1
Depends: libc, libstdcpp6, libopenssl3, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: aarch64_cortex-a53
Size: 12533530
Filename: node_v18.19.1-1_aarch64_cortex-a53.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1713259776

Node.js is placed at /usr/bin/node
Node.js version: v18.19.1

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: git-24.231.52046-6266f45
Depends: libc, dnsmasq-full, UnblockNeteaseMusic, node
Status: install user installed
Section: luci
Architecture: all
Size: 14159
Filename: luci-app-unblockneteasemusic_git-24.231.52046-6266f45_all.ipk
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Description: LuCI support for UnblockNeteaseMusic (JavaScript)
Installed-Time: 1713263823

-rw-r--r--    1 root     root         252 Apr 28 22:30 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 1001     ntp         8.5K Aug 19  2023 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwx------    2 root     root        4.0K Apr 28 22:27 core
-rw-------    1 root     root          41 Apr 28 22:27 core_local_ver
-rwxr-xr-x    1 1001     ntp         4.7K Aug 19  2023 debugging.sh
-rwxr-xr-x    1 1001     ntp          392 Aug 19  2023 log_check.sh
-rw-r--r--    1 1001     ntp         1.7K Aug 19  2023 nftables.ut
-rwxr-xr-x    1 1001     ntp         3.0K Aug 19  2023 update.sh

config unblockneteasemusic 'config'
	option enable '1'
	option auto_update '1'
	option update_time '3'
	option enable_flac '1'
	option select_max_br '1'
	option replace_music_source 'lower_than_320kbps'
	option block_ads '1'
	option local_vip 'svip'

UnblockNeteaseMusic Node.js info:
Git HEAD version: e6303e0a93bcd8081c82e6fc6042d5674eeabb2b
Core version: 0.27.6
-rw-------    1 root     root      220.2K Apr 28 22:27 app.js
-rw-------    1 root     root      185.4K Apr 28 22:27 bridge.js
-rw-------    1 root     root         790 Apr 28 22:27 ca.crt
-rw-------    1 root     root         932 Apr 28 22:27 server.crt
-rw-------    1 root     root         359 Apr 28 22:27 server.key

Netease networking info:
< Location: http://m10.music.126.net/20240428230037/0e1511c1c1057611f475584cf497f8db/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["45.254.48.92","45.254.49.45","59.111.19.99","45.127.129.53","118.24.63.156","47.100.127.239","39.105.175.128","39.105.63.80","193.112.159.225","182.92.170.253"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      5790/node
tcp        0      0 :::5201                 :::*                    LISTEN      5790/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 5791,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 5790,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"BLOCK_ADS": "true",
					"ENABLE_FLAC": "true",
					"ENABLE_LOCAL_VIP": "svip",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"MIN_BR": "320000",
					"SELECT_MAX_BR": "true",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
/usr/share/unblockneteasemusic/debugging.sh: line 75: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 77: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 79: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 81: nft: not found

/usr/share/unblockneteasemusic/debugging.sh: line 83: nft: not found

dhcp-option=252,http://192.168.88.1:5200/proxy.pac
nftset=/.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null}],"code":200}

### 条款

- [ ] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
> 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
