### ISSUE TITLE
这是什么情况，什么都正常就是解锁不了。

### ISSUE THREAD

**Issue by zxymdaddy** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#304]
### 需求描述

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.9.0-rc7-aml-s812",
	"hostname": "OneCloud",
	"system": "ARMv7 Processor rev 1 (v7l)",
	"model": "BugScaner",
	"board_name": "BugScaner,OneCloud",
	"release": {
		"distribution": "ImmortalWrt",
		"version": "SNAPSHOT",
		"revision": "r0-3d804a9",
		"target": "meson/meson8b",
		"description": "ImmortalWrt SNAPSHOT r0-3d804a9",
		"description": "莫小小(2024.05.06)@lean "
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2024.04.19~e8780fa7-r1
Depends: libc, libuclient20201210
Provides: wget
Status: install ok installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1714981444

Package: libustream-openssl20201210
Version: 2024.04.19~524a76e5-r1
Depends: libc, libubox20240329, libopenssl3
Provides: libustream-openssl
Status: install ok installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1714981444

Package: wget-ssl
Version: 1.24.5-r1
Depends: libc, libpcre2, zlib, libopenssl3, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1715073082

--2024-05-08 14:52:34--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 20.205.243.168
Connecting to api.github.com|20.205.243.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... ..........  192K
    50K .......... .......... .......... .......... ..........  388K
   100K .......... .......... .......... ...                    501K=0.5s

2024-05-08 14:52:36 (293 KB/s) - written to stdout [136422]

d731b754d8c44756b8f5efe4f32da8bed6bc60c2

Node.js info:
Node.js is placed at /usr/bin/node
Node.js version: v20.12.2

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.2-3
Depends: libc, dnsmasq-full, firewall4, node115
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1715073200

-rw-r--r--    1 root     root         471 May  7 17:18 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Nov  1  2023 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K May  7 17:21 core
-rw-r--r--    1 root     root          41 May  7 17:21 core_local_ver
-rwxr-xr-x    1 root     root        4.7K Nov  1  2023 debugging.sh
-rwxr-xr-x    1 root     root         392 Nov  1  2023 log_check.sh
-rw-r--r--    1 root     root        1.7K Nov  1  2023 nftables.sh
-rwxr-xr-x    1 root     root        3.0K Nov  1  2023 update.sh

config unblockneteasemusic 'config'
	option enable '1'
	list music_source 'qq'
	list music_source 'youtube'
	list music_source 'pyncmd'
	list music_source 'bilibili'
	list music_source 'kugou'
	list music_source 'kuwo'
	option kuwo_cookie 'Hm=1691138545;Secret=bPFeJZjCYT264BNmzbG8N7A4F8KcSBe3'
	option qq_cookie 'set'
	option search_album '1'
	option replace_music_source 'dont_replace'
	option local_vip 'svip'

UnblockNeteaseMusic Node.js info:
Git HEAD version: d731b754d8c44756b8f5efe4f32da8bed6bc60c2
Core version: 0.27.6-patch.1
-rw-r--r--    1 root     root      220.5K May  7 17:21 app.js
-rw-r--r--    1 root     root      185.7K May  7 17:21 bridge.js
-rw-r--r--    1 root     root         790 May  7 17:21 ca.crt
-rw-r--r--    1 root     root         932 May  7 17:21 server.crt
-rw-r--r--    1 root     root         359 May  7 17:21 server.key

Netease networking info:
< Location: http://m10.music.126.net/20240508151737/6830f7c4f3a7a6f1217ad6d2d3baa9f6/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["115.238.119.69","183.136.182.20","59.111.19.99","45.127.129.53","39.105.63.80","182.92.170.253","39.105.175.128","193.112.159.225","118.24.63.156","47.100.127.239"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      7618/node
tcp        0      0 :::5201                 :::*                    LISTEN      7618/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 7619,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 7618,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-o",
					"qq",
					"youtube",
					"pyncmd",
					"bilibili",
					"kugou",
					"kuwo",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"ENABLE_LOCAL_VIP": "svip",
					"KUWO_COOKIE": "Hm=1691138545;Secret=bPFeJZjCYT264BNmzbG8N7A4F8KcSBe3",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"QQ_COOKIE": "set",
					"SEARCH_ALBUM": "true",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
Error: No such file or directory
list set inet fw4 acl_neteasemusic_http
                  ^^^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 acl_neteasemusic_https
                  ^^^^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 neteasemusic
                  ^^^^^^^^^^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music
                    ^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music_redir
                    ^^^^^^^^^^^^^^^^^^^^^^^^^

dhcp-option=252,http://192.168.1.111:5200/proxy.pac
nftset=/.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2x3LnN5Y2RuLmt1d28uY24vNTI0NmRiODRlYmE2MDQ3NzM4NWU1N2ZjOGE5NWIyNzMvNjYzYjIxMzgvcmVzb3VyY2UvMzAxMDYvdHJhY2ttZWRpYS9NNTAwMDA0VXN0RjEzdE1va1cubXAzP2JpdHJhdGU=/33190502.mp3","br":128000,"size":4203657,"md5":"553deb3b6e30ff6ca1dc2808546778f9","code":200,"expi":1200,"type":"mp3","gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null}],"code":200}
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://lw.sycdn.kuwo.cn/c4181f083881aed01fa05d6990c7cfa4/663af451/resource/30106/trackmedia/M500004UstF13tMokW.mp3?bitrate"
ERROR: (provider/match) Cannot read properties of null (reading '0')
    TypeError: Cannot read properties of null (reading '0')
        at /usr/share/unblockneteasemusic/core/app.js:3:37448
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async u.cache (/usr/share/unblockneteasemusic/core/app.js:2:1245)
        at async m (/usr/share/unblockneteasemusic/core/app.js:3:29354)
        at async Promise.any (index 1)
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://trackercdn.kugou.com/i/v2/?key=422ac28be2a0a1afbb479bc8deea913e&hash=4954e9d43c0b0e8a28a423580635c968&appid=1005&pid=2&cmd=25&behavior=play&album_id=8583526"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://m7.music.126.net/20240508120605/dc10aed690df585078eb7a0007b500b4/ymusic/e838/c45b/fee4/9aaded1cf5a4e3abead99373f9037972.mp3"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://youtube.com/s/player/edea0cc6/player_ias.vflset/zh_CN/base.js"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://u.y.qq.com/cgi-bin/musicu.fcg?data=%7B%22search%22%3A%7B%22method%22%3A%22DoSearchForQQMusicDesktop%22%2C%22module%22%3A%22music.search.SearchCgiService%22%2C%22param%22%3A%7B%22num_per_page%22%3A5%2C%22page_num%22%3A1%2C%22query%22%3A%22%E5%90%9B%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7%20-%20azusa%22%2C%22search_type%22%3A0%7D%7D%7D"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://api.bilibili.com/audio/music-service-c/s?search_type=music&page=1&pagesize=30&keyword=%E5%90%9B%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7%20-%20azusa"
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "https://m7.music.126.net/20240508120605/dc10aed690df585078eb7a0007b500b4/ymusic/e838/c45b/fee4/9aaded1cf5a4e3abead99373f9037972.mp3"
ERROR: (provider/match) aborted
    Error: aborted
        at TLSSocket.socketCloseListener (node:_http_client:460:19)
        at TLSSocket.emit (node:events:530:35)
        at node:net:338:12
        at TCP.done (node:_tls_wrap:657:7)
    code: ECONNRESET
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://lw.sycdn.kuwo.cn/5246db84eba60477385e57fc8a95b273/663b2138/resource/30106/trackmedia/M500004UstF13tMokW.mp3?bitrate"

**Comment by xuexue49** [comment]
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
同出现监听在ipv6上的情况，尝试切换2.14-3版本，在2.14-3版本下可正常运行
监听端口为
INFO: (app) HTTP Server running @ http://127.0.0.1:5200
INFO: (app) HTTPS Server running @ http://127.0.0.1:5201
可切换至2.14-3版本使用或自行修改代码编译

**Comment by zxymdaddy** [comment]
luci-app-unblockneteasemusic v2.14  怎么打印日志啊。。

**Comment by 1715173329** [comment]
不使用正确 issue 模板。
防火墙配置有问题，检查防火墙配置，升级本项目最新版本。
