### ISSUE TITLE
替换了说是要开通vip，音源失效

### ISSUE THREAD

**Issue by lingxiangliang** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#305]
### Bug 描述

替换成了一个六秒的音频，要冲vip才能听 

### 预期行为

正常使用

### 调试报告

DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/find"

DEBUG: (cache) 65766 did not hit. Storing the execution result...
    logKey: 65766
    cacheStorageId: "provider/find"
DEBUG: (request) Start requesting https://music.163.com/api/song/detail?ids=[65766]

DEBUG: (provider/match) Getting the audio...
    source: "kugou"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }

DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/kugou"

DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/kugou"

DEBUG: (request) Start requesting http://mobilecdn.kugou.com/api/v3/search/song?keyword=%E5%AF%8C%E5%A3%AB%E5%B1%B1%E4%B8%8B%20-%20%E9%99%88%E5%A5%95%E8%BF%85&page=1&pagesize=10

DEBUG: (provider/match) Getting the audio...
    source: "kuwo"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/kuwo"

DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/kuwo"

DEBUG: (request) Start requesting http://search.kuwo.cn/r.s?&correct=1&stype=comprehensive&encoding=utf8&rformat=json&mobi=1&show_copyright_off=1&searchapi=6&all=%E5%AF%8C%E5%A3%AB%E5%B1%B1%E4%B8%8B%20%E9%99%88%E5%A5%95%E8%BF%85

DEBUG: (provider/match) Getting the audio...
    source: "migu"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }
DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/migu"

DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/migu"

DEBUG: (request) Start requesting https://m.music.migu.cn/migu/remoting/scr_search_tag?keyword=%E5%AF%8C%E5%A3%AB%E5%B1%B1%E4%B8%8B%20-%20%E9%99%88%E5%A5%95%E8%BF%85&type=2&rows=20&pgc=1

DEBUG: (provider/match) Getting the audio...
    source: "bilibili"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }

DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "provider/bilibili"

DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "provider/bilibili"

DEBUG: (request) Start requesting https://api.bilibili.com/audio/music-service-c/s?search_type=music&page=1&pagesize=30&keyword=%E5%AF%8C%E5%A3%AB%E5%B1%B1%E4%B8%8B%20-%20%E9%99%88%E5%A5%95%E8%BF%85

DEBUG: (provider/match) Getting the audio...
    source: "ytdlp"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }

DEBUG: (cache) Cleaning up the expired caches...
    cacheStorageId: "yt-dlp"

DEBUG: (cache) Something did not hit. Storing the execution result...
    logKey: "Something"
    cacheStorageId: "yt-dlp"

ERROR (YtDlpNotInstalled): (provider/yt-dlp) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at p (C:\snapshot\server\precompiled\app.js)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async d (C:\snapshot\server\precompiled\app.js)
        at async u.cache (C:\snapshot\server\precompiled\app.js)
        at async m (C:\snapshot\server\precompiled\app.js)
        at async Promise.any (index 4)
        at async b (C:\snapshot\server\precompiled\app.js)
        at async Promise.all (index 0)

ERROR (YtDlpNotInstalled): (provider/match) You must install "yt-dlp" before using the "ytdlp" source.
    YtDlpNotInstalled: You must install "yt-dlp" before using the "ytdlp" source.
        at p (C:\snapshot\server\precompiled\app.js)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async d (C:\snapshot\server\precompiled\app.js)
        at async u.cache (C:\snapshot\server\precompiled\app.js)
        at async m (C:\snapshot\server\precompiled\app.js)
        at async Promise.any (index 4)
        at async b (C:\snapshot\server\precompiled\app.js)
        at async Promise.all (index 0)

DEBUG: (request) Start requesting http://trackercdn.kugou.com/i/v2/?key=2fe66d5049309ef83b5b495649dabad1&hash=4c2a1e8ab2fa1aa0a55b8c05cfbf7152&appid=1005&pid=2&cmd=25&behavior=play&album_id=976404

DEBUG: (request) Start requesting http://trackercdn.kugou.com/i/v2/?key=80212894f82d3727b953266086d335d1&hash=0433f1a94fa162b20fb8ae576a951d6b&appid=1005&pid=2&cmd=25&behavior=play&album_id=976404

DEBUG: (request) Start requesting http://mobi.kuwo.cn/mobi.s?f=kuwo&q=NI8S5evAnmHH4UXcuKKslDk4RFzONrTj1DNPSSYKrOLCiSrScep7CUOU9RpDmtLJ6VGbBO7Ii56Tz66kUMw34wBcRiVFLw+xbYzjB825gKLOgvASvMRCqmQncu/cbUXD986AWDAmhSg=

DEBUG: (request) Start requesting http://nf.sycdn.kuwo.cn/3469553c37352ef5744badfebd122c17/66518249/resource/n3/58/79/2272659253.mp3?bitrate

DEBUG: (provider/match) The matched song is:
    size: 108378
    br: 128000
    url: "http://nf.sycdn.kuwo.cn/3469553c37352ef5744badfebd122c17/66518249/resource/n3/58/79/2272659253.mp3?bitrate"
    md5: null

DEBUG: (provider/match) The audio matched!
    source: "kuwo"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }

DEBUG: (provider/match) The data to replace:
    audioInfo: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }
    audioData: {
      "size": 108378,
      "br": 128000,
      "url": "http://nf.sycdn.kuwo.cn/3469553c37352ef5744badfebd122c17/66518249/resource/n3/58/79/2272659253.mp3?bitrate",
      "md5": null,
      "source": "kuwo"
    }

INFO: (provider/match) Replaced: [65766] 富士山下
    audioId: 65766
    songName: "富士山下"
    url: "http://nf.sycdn.kuwo.cn/3469553c37352ef5744badfebd122c17/66518249/resource/n3/58/79/2272659253.mp3?bitrate"

DEBUG: (request) Start requesting https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.4?netType=01&resourceType=2&songId=1140198700&toneFlag=HQ

DEBUG: (request) Start requesting https://app.c.nf.migu.cn/MIGUM2.0/strategy/listen-url/v2.4?netType=01&resourceType=2&songId=1140198700&toneFlag=PQ

DEBUG: (request) Start requesting http://freetyst.nf.migu.cn/public/product8th/product38/2020/03/1000/2019%E5%B9%B412%E6%9C%8823%E6%97%A509%E7%82%B920%E5%88%86%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E6%AD%A3%E4%B8%9C20%E9%A6%96747171/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/6005662JGXK.mp3?channelid=02&msisdn=b5c5cfe4-8c9e-4201-a316-fa66a958f962&Tim=1716618102030&Key=9c1698cd6ccfe299

DEBUG: (provider/match) The matched song is:
    size: 4279109
    br: 128000
    url: "http://freetyst.nf.migu.cn/public/product8th/product38/2020/03/1000/2019%E5%B9%B412%E6%9C%8823%E6%97%A509%E7%82%B920%E5%88%86%E5%86%85%E5%AE%B9%E5%87%86%E5%85%A5%E6%AD%A3%E4%B8%9C20%E9%A6%96747171/%E6%A0%87%E6%B8%85%E9%AB%98%E6%B8%85/MP3_128_16_Stero/6005662JGXK.mp3?channelid=02&msisdn=b5c5cfe4-8c9e-4201-a316-fa66a958f962&Tim=1716618102030&Key=9c1698cd6ccfe299"
    md5: null

DEBUG: (provider/match) The audio matched!
    source: "migu"
    info: {
      "name": "富士山下",
      "id": 65766,
      "alias": [],
      "duration": 258902,
      "album": {
        "name": "What's Going On…?",
        "id": 6451
      },
      "artists": [
        {
          "name": "陈奕迅",
          "id": 2116
        }
      ],
      "keyword": "富士山下 - 陈奕迅"
    }

### 其他信息

第一次提交 有问题请见谅

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by hxfkof** [comment]
同样的问题，以前用得好好的，突然提示一段要开VIP的提示音频，好像是酷我源的问题

**Comment by ccrichard3** [comment]
估计是音源问题，很多歌都这样

**Comment by hemingchun** [comment]
同样的问题，啊啊啊啊啊

**Comment by meijie-jesse** [comment]
酷我接口导致的。在音源接口中选自定义 填入 kugou migu qq 保存重启即可。

**Comment by hemingchun** [comment]
> 酷我接口导致的。在音源接口中选自定义 填入 kugou migu qq 保存重启即可。

感谢，可以了
