### ISSUE TITLE
我应该怎么安装？我在软件包里上传安装了IPK文件，但是提示错误，过后软件包里有这个插件，但是服务里没有。依赖项也都安装了

### ISSUE THREAD

**Issue by Godwin9527** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#306]
### 需求描述

错误提示为
正在执行软件包管理器
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libstdcpp6 and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libpthread and libpthread) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (librt and librt) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libgcc1 and libgcc1) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (libatomic1 and libatomic1) providing same name marked HOLD or PREFER. Using latest.
Installing luci-app-unblockneteasemusic (3.2-3) to root...
Configuring luci-app-unblockneteasemusic.
错误
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-nf-ipt
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-ipt-core
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-ipt-ipset
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-ipt-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.4.143-1-fb881fbbae69f30da18e7c6eb01310c1) for kmod-nf-conntrack-netlink
 
 我问了gpt，他说是缺少依赖项。但是我完全不懂这些代码，想问一下有没有更详细的教程？是我哪里做错了，还是少做了？

**Comment by 1715173329** [comment]
不使用正确模板，系统依赖环境有问题。更换其他系统即可。
