### ISSUE TITLE
在mips版的openwrt上安装时报找不到luci-app-unblockneteasemusic的依赖节点

### ISSUE THREAD

**Issue by Moshang666** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#307]
### Bug 描述

在mips版的openwrt上安装时报
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency node for luci-app-unblockneteasemusic
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-unblockneteasemusic:
 * 	node
过后在里面的服务能找到该插件，但勾选启动后还是显示未运行

### 调试报告

没有

### 条款

- [x] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [x] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
更换设备即可。
