### ISSUE TITLE
旁路由上开启后没有效果

### ISSUE THREAD

**Issue by moyanstar** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#308]
### Bug 描述

设备是群晖虚拟出来的op旁路由，安卓手机上没有效果，其他设备没有测试

### 调试报告

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by HitterGo** [comment]
同，关注

**Comment by 1715173329** [comment]
不支持“旁路由”。
