### ISSUE TITLE
无法解锁

### ISSUE THREAD

**Issue by swefn** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#310]
### Bug 描述

op系统上开启程序，但是win11端程序没有反应（因为看到说win和安卓不需要证书我就没有下载安装）

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.10.221",
	"hostname": "iStoreOS",
	"system": "ARMv8 Processor rev 0",
	"model": "FriendlyElec NanoPi R5C",
	"board_name": "friendlyelec,nanopi-r5c",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "iStoreOS",
		"version": "22.03.7",
		"revision": "2024080210",
		"target": "rockchip/rk35xx",
		"description": "iStoreOS 22.03.7 2024080210"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_cortex-a53
Size: 8229
Filename: uclient-fetch_2023-04-13-007d9454-1_aarch64_cortex-a53.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1721975007

Package: libustream-wolfssl20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libwolfssl5.7.2.ee39414e
Provides: libustream-wolfssl
Conflicts: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5190
Filename: libustream-wolfssl20201210_2022-12-08-9217ab46-2_aarch64_cortex-a53.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5677
Filename: libustream-openssl20201210_2022-12-08-9217ab46-2_aarch64_cortex-a53.ipk
Description: ustream SSL Library (openssl)
Installed-Time: 1721975007

Package: libustream-mbedtls20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_cortex-a53
Size: 5492
Filename: libustream-mbedtls20201210_2022-12-08-9217ab46-2_aarch64_cortex-a53.ipk
Description: ustream SSL Library (mbedtls)

Package: wget-ssl
Version: 1.21.4-1
Depends: libc, libpcre2, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: unknown ok not-installed
Section: net
Architecture: aarch64_cortex-a53
Size: 217211
Filename: wget-ssl_1.21.4-1_aarch64_cortex-a53.ipk
Description: Wget is a network utility to retrieve files from the Web using http and ftp, the two most widely used Internet protocols. It works non-interactively, so it will work in the background, after having logged off. The program supports recursive retrieval of web-authoring pages as well as ftp sites -- you can use wget to make mirrors of archives and home pages or to travel the Web like a WWW robot. This package is built with SSL support.

Package: wget-ssl
Version: 1.21.4-2
Depends: libc, libpcre2, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: aarch64_cortex-a53
Installed-Time: 1721975007

--2024-08-17 20:44:42--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 140.82.116.6
Connecting to api.github.com|140.82.116.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... ..........  177K
    50K .......... .......... .......... .......... ..........  290K
   100K .......... .......... .......... ...                    347K=0.6s

2024-08-17 20:44:45 (242 KB/s) - written to stdout [136551]

0c50e8c6ba159efd586595b8a9d1308cde94d4cc

Node.js info:
Package: node
Version: v16.20.2-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Section: lang
Architecture: aarch64_cortex-a53
Size: 11542753
Filename: node_v16.20.2-1_aarch64_cortex-a53.ipk
Description: Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world. *** The following preparations must be made on the host side. *** 1. gcc 8.3 or higher is required. 2. To build a 32-bit target, gcc-multilib, g++-multilib are required. 3. Requires libatomic package. (If necessary, install the 32-bit library at the same time.) ex) sudo apt-get install gcc-multilib g++-multilib
Installed-Time: 1723897189

Node.js is placed at /usr/bin/node
Node.js version: v16.20.2

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.2-3
Depends: libc, dnsmasq-full, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1723897374

-rw-r--r--    1 root     root         674 Aug 17 20:37 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.9K Jul 22  2023 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwx------    2 root     root        4.0K Aug 17 20:23 core
-rw-------    1 root     root          41 Aug 17 20:23 core_local_ver
-rwxr-xr-x    1 root     root        5.3K Jul 22  2023 debugging.sh
-rwxr-xr-x    1 root     root         392 Jul 22  2023 log_check.sh
-rw-r--r--    1 root     root        1.6K Jul 22  2023 nftables.ut
-rwxr-xr-x    1 root     root        3.0K Jul 22  2023 update.sh

config unblockneteasemusic 'config'
	option disable_upgrade_check '1'
	option auto_update '1'
	option update_time '3'
	option enable_flac '1'
	option replace_music_source 'lower_than_192kbps'
	option local_vip 'svip'
	option advanced_mode '1'
	option log_level 'info'
	option http_port '5200'
	option https_port '5201'
	option endpoint_url 'https://music.163.com'
	option hijack_ways 'dont_hijack'
	option netease_server_ip '117.135.207.65'
	option self_issue_cert_crt '/usr/share/unblockneteasemusic/core/server.crt'
	option self_issue_cert_key '/usr/share/unblockneteasemusic/core/server.key'
	option follow_source_order '1'
	option enable '1'
	list music_source 'kuwo'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 0c50e8c6ba159efd586595b8a9d1308cde94d4cc
Core version: 0.27.7
-rw-------    1 root     root      221.1K Aug 17 20:23 app.js
-rw-------    1 root     root      186.8K Aug 17 20:23 bridge.js
-rw-------    1 root     root         790 Aug 17 20:23 ca.crt
-rw-------    1 root     root         932 Aug 17 20:23 server.crt
-rw-------    1 root     root         359 Aug 17 20:23 server.key

Netease networking info:
< Location: http://m10.music.126.net/20240817210947/1d74c789f171e06b5ca131f2660ded8c/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["117.135.207.65","1.95.21.33","182.92.170.253","47.100.127.239","39.105.63.80","118.24.63.156","39.105.175.128","193.112.159.225"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      11095/node
tcp        0      0 :::5201                 :::*                    LISTEN      11095/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 11097,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 11095,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-o",
					"kuwo",
					"-e",
					"https://music.163.com",
					"-f",
					"117.135.207.65"
				],
				"term_timeout": 5,
				"env": {
					"DISABLE_UPGRADE_CHECK": "true",
					"ENABLE_FLAC": "true",
					"ENABLE_LOCAL_VIP": "svip",
					"FOLLOW_SOURCE_ORDER": "true",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"MIN_BR": "192000",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
Chain "netease_cloud_music" not found.

Table "neteasemusic" not found.

Table "acl_neteasemusic_http" not found.

Table "acl_neteasemusic_https" not found.

cat: can't open '/tmp/dnsmasq.d/dnsmasq-unblockneteasemusic.conf': No such file or directory

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cDovL2x2LnN5Y2RuLmt1d28uY24vNjE1N2QxMzM4MDE4MjI1ODRlNzZiODRhYjFkOWEyNGIvNjZjMDliNDAvcmVzb3VyY2UvMzAxMDYvdHJhY2ttZWRpYS9NNTAwMDAzOFYxT0QxRjkyZlIubXAzP2JpdHJhdGU=/33190502.mp3","br":128000,"size":1700885,"md5":"09a74c459c55925ad1af3ba31a9d41cd","code":200,"expi":1200,"type":"mp3","gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null}],"code":200}
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "http://lv.sycdn.kuwo.cn/6157d133801822584e76b84ab1d9a24b/66c09b40/resource/30106/trackmedia/M5000038V1OD1F92fR.mp3?bitrate"

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [ ] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
> 我确认我已经在对应的客户端正确安装了 CA 证书。

并且关掉了 ipset 劫持，需要自行配置代理规则。
