### ISSUE TITLE
这是什么情况，使用的FW4防火墙，防火墙错误，找不到文件。

### ISSUE THREAD

**Issue by zxymdaddy** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#311]
### Bug 描述

Firewall info:

Error: No such file or directory
list set inet fw4 acl_neteasemusic_http
                  ^^^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 acl_neteasemusic_https
                  ^^^^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 neteasemusic
                  ^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 neteasemusic6
                  ^^^^^^^^^^^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music
                    ^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music_redir
                    ^^^^^^^^^^^^^^^^^^^^^^^^^

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.9.0-rc7-aml-s812",
	"hostname": "KWrt",
	"system": "ARMv7 Processor rev 1 (v7l)",
	"model": "BugScaner",
	"board_name": "BugScaner,OneCloud",
	"release": {
		"distribution": "1004",
		"version": "23.05-SNAPSHOT",
		"revision": "08.28.2024",
		"target": "amlogic/meson8b",
		"description": "KWrt 08.28.2024 by Kiddin'"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1724974616

Package: libustream-mbedtls20201210
Version: 2023-02-25-498f6e26-1
Depends: libc, libubox20230523, libmbedtls12
Provides: libustream-mbedtls
Conflicts: libustream-openssl, libustream-wolfssl
Status: install user installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1724974616

Package: wget-ssl
Version: 1.21.4-1
Depends: libc, libpcre2, zlib, libopenssl3, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1724974616

--2024-09-03 09:53:01--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 20.205.243.168
Connecting to api.github.com|20.205.243.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... .......... 50.8K
    50K .......... .......... .......... .......... ..........  270K
   100K .......... .......... .......... ....                   168K=1.4s

2024-09-03 09:53:04 (97.7 KB/s) - written to stdout [137221]

677e5448f9816444827b3b8f14ff04f9be6beef0

Node.js info:
Package: node
Version: v18.20.4-1
Depends: libc, libstdcpp6, libopenssl3, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Architecture: arm_cortex-a5_vfpv4
Installed-Time: 1725264376

Node.js is placed at /usr/bin/node
Node.js version: v18.20.4

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.3-1
Depends: libc, dnsmasq-full, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1725264376

-rw-r--r--    1 root     root         607 Sep  2 16:06 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.8K Aug 29 19:54 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxr-xr-x    2 root     root        4.0K Sep  2 16:42 core
-rw-r--r--    1 root     root          41 Sep  2 16:42 core_local_ver
-rwxr-xr-x    1 root     root        5.3K Aug 29 19:54 debugging.sh
-rwxr-xr-x    1 root     root         392 Aug 29 19:54 log_check.sh
-rw-r--r--    1 root     root        1.6K Sep  3 09:51 nftables.nft
-rw-r--r--    1 root     root        1.6K Aug 29 19:54 nftables.ut-opkg
-rwxr-xr-x    1 root     root        3.0K Aug 29 19:54 update.sh

config unblockneteasemusic 'config'
	option enable '1'
	option search_album '1'
	option replace_music_source 'dont_replace'
	option local_vip 'svip'
	option disable_upgrade_check '1'
	option qq_cookie 'set'
	list music_source 'kugou'
	list music_source 'pyncmd'
	list music_source 'bilibili'
	list music_source 'qq'
	list music_source 'migu'
	option migu_cookie 'set'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 677e5448f9816444827b3b8f14ff04f9be6beef0
Core version: 0.27.8-patch.1
-rw-r--r--    1 root     root      221.2K Sep  2 16:21 app.js
-rw-r--r--    1 root     root      185.9K Sep  2 16:42 bridge.js
-rw-r--r--    1 root     root         790 Sep  2 16:42 ca.crt
-rw-r--r--    1 root     root         932 Sep  2 16:42 server.crt
-rw-r--r--    1 root     root         359 Sep  2 16:42 server.key

Netease networking info:
< Location: http://m10.music.126.net/20240903101807/eb92e75022bdf06022839dc806e3d823/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["111.124.200.65","1.95.21.33","193.112.159.225","47.100.127.239","118.24.63.156","39.105.175.128","39.105.63.80","182.92.170.253"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      3182/node
tcp        0      0 :::5201                 :::*                    LISTEN      3182/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 3183,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 3182,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-o",
					"kugou",
					"pyncmd",
					"bilibili",
					"qq",
					"migu",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"DISABLE_UPGRADE_CHECK": "true",
					"ENABLE_LOCAL_VIP": "svip",
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"MIGU_COOKIE": "set",
					"QQ_COOKIE": "set",
					"SEARCH_ALBUM": "true",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:

Error: No such file or directory
list set inet fw4 acl_neteasemusic_http
                  ^^^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 acl_neteasemusic_https
                  ^^^^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 neteasemusic
                  ^^^^^^^^^^^^

Error: No such file or directory
list set inet fw4 neteasemusic6
                  ^^^^^^^^^^^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music
                    ^^^^^^^^^^^^^^^^^^^

Error: No such file or directory
list chain inet fw4 netease_cloud_music_redir
                    ^^^^^^^^^^^^^^^^^^^^^^^^^

dhcp-option=252,http://192.168.1.111:5200/proxy.pac
nftset=/.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/interface3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/apm3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6
nftset=/clientlog3.music.163.com/inet#fw4#neteasemusic,6#inet#fw4#neteasemusic6

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":4,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null}],"code":200}
{"data":[{"id":33190502,"url":"https://music.163.com/package/aHR0cHM6Ly9tNy5tdXNpYy4xMjYubmV0LzIwMjQwOTAzMTAxNjMwLzE1ZDllNDk3YzVhZGQyMzk5MzIwZmYwYzhhMWU3NGEwL3ltdXNpYy9lODM4L2M0NWIvZmVlNC85YWFkZWQxY2Y1YTRlM2FiZWFkOTkzNzNmOTAzNzk3Mi5tcDM=/33190502.mp3","br":320000,"size":10508582,"md5":"9aaded1cf5a4e3abead99373f9037972","code":200,"expi":1200,"type":"mp3","gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null}],"code":200}
INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "http://mobilecdn.kugou.com/api/v3/search/song?keyword=%E5%90%9B%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7%20-%20azusa&page=1&pagesize=10"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://m7.music.126.net/20240903101630/15d9e497c5add2399320ff0c8a1e74a0/ymusic/e838/c45b/fee4/9aaded1cf5a4e3abead99373f9037972.mp3"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://api.bilibili.com/audio/music-service-c/s?search_type=music&page=1&pagesize=30&keyword=%E5%90%9B%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7%20-%20azusa"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://u.y.qq.com/cgi-bin/musicu.fcg?data=%7B%22search%22%3A%7B%22method%22%3A%22DoSearchForQQMusicDesktop%22%2C%22module%22%3A%22music.search.SearchCgiService%22%2C%22param%22%3A%7B%22num_per_page%22%3A5%2C%22page_num%22%3A1%2C%22query%22%3A%22%E5%90%9B%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7%20-%20azusa%22%2C%22search_type%22%3A0%7D%7D%7D"
WARN: (request) The request timed out, or the requester didn't handle the response.
    url: "https://m.music.migu.cn/migu/remoting/scr_search_tag?keyword=%E5%90%9B%E3%81%AE%E3%81%BE%E3%81%BE%E3%81%A7%20-%20azusa&type=2&rows=20&pgc=1"
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
INFO: (provider/match) Replaced: [33190502] 君のままで
    audioId: 33190502
    songName: "君のままで"
    url: "https://m7.music.126.net/20240903101630/15d9e497c5add2399320ff0c8a1e74a0/ymusic/e838/c45b/fee4/9aaded1cf5a4e3abead99373f9037972.mp3"

Log is available at:
https://litter.catbox.moe/4ti9qb.txt

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
> -rw-r--r-- 1 root root 1.6K Sep 3 09:51 nftables.nft
> -rw-r--r-- 1 root root 1.6K Aug 29 19:54 nftables.ut-opkg

规则文件被破坏，应该重新干净安装。
