### ISSUE TITLE
关于在iStoreOS上的插件无法正常使用的问题

### ISSUE THREAD

**Issue by MeowLynxSea** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#313]
### Bug 描述

在iStoreOS上使用插件时，灰色歌曲无法解锁

![d6361242-b809-45b6-b8ef-6ae3d3056df9](https://github.com/user-attachments/assets/71c8ca67-2f09-4cdd-a646-661d121af99a)
![85ceebbf-ecca-40cd-9f03-cfac3724e311](https://github.com/user-attachments/assets/bf6d7d9a-6517-447d-8a0c-a1920ccdc4d5)

点击更新核心版本后，版本为：0.27.8-patch.1 (4af8718)(4af87189b3594dfa3a838d6ab33a386afea657e2)

网易云版本：PC 3.0.2(64位)(Build:203023) 

Windows版本：22631.4037

Patch:3f4c7a9

不知道是程序的问题还是插件适配的问题

### 调试报告

Launching luci-app-unblockneteasmusic Debugging Tool...

OpenWrt info:
{
	"kernel": "5.10.221",
	"hostname": "MeowRouter",
	"system": "ARMv8 Processor rev 4",
	"model": "Radxa E20C",
	"board_name": "radxa,e20c",
	"rootfs_type": "squashfs",
	"release": {
		"distribution": "iStoreOS",
		"version": "22.03.7",
		"revision": "2024080210",
		"target": "rockchip/rk35xx",
		"description": "iStoreOS 22.03.7 2024080210"
	}
}

uclient-fetch info:
Package: uclient-fetch
Version: 2023-04-13-007d9454-1
Depends: libc, libuclient20201210
Provides: wget
Status: install user installed
Architecture: aarch64_cortex-a53
Installed-Time: 1721975007

Package: libustream-openssl20201210
Version: 2022-12-08-9217ab46-2
Depends: libc, libubox20220515, libopenssl1.1
Provides: libustream-openssl
Status: install user installed
Architecture: aarch64_cortex-a53
Installed-Time: 1721975007

Package: wget-ssl
Version: 1.21.4-2
Depends: libc, libpcre2, zlib, libopenssl1.1, librt
Provides: gnu-wget, wget
Status: install user installed
Architecture: aarch64_cortex-a53
Installed-Time: 1721975007

--2024-09-09 00:19:46--  https://api.github.com/repos/UnblockNeteaseMusic/server/commits?sha=enhanced&path=precompiled
Resolving api.github.com... 20.205.243.168
Connecting to api.github.com|20.205.243.168|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'STDOUT'

     0K .......... .......... .......... .......... ..........  345K
    50K .......... .......... .......... .......... ..........  723K
   100K .......... .......... .......... ...                   11.4M=0.2s

2024-09-09 00:19:47 (615 KB/s) - written to stdout [136406]

4af87189b3594dfa3a838d6ab33a386afea657e2

Node.js info:
Package: node
Version: v16.20.2-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libcares, libatomic1
Status: install ok installed
Architecture: aarch64_cortex-a53
Installed-Time: 1725799855

Node.js is placed at /usr/bin/node
Node.js version: v16.20.2

luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 3.2
Depends: libc, dnsmasq-full, node
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic 0100db4c709a797fdb03ce6b172c860b860f6bea0e0614477d9dda9b1b574b94
Installed-Time: 1725799855

-rw-r--r--    1 root     root         148 Sep  9 00:07 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root       10.9K Jan  1  2024 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwx------    2 root     root        4.0K Sep  9 00:13 core
-rw-------    1 root     root          41 Sep  9 00:13 core_local_ver
-rwxr-xr-x    1 root     root        5.3K Jan  1  2024 debugging.sh
-rwxr-xr-x    1 root     root         392 Jan  1  2024 log_check.sh
-rw-r--r--    1 root     root        1.6K Jan  1  2024 nftables.ut
-rwxr-xr-x    1 root     root        3.0K Jan  1  2024 update.sh

config unblockneteasemusic 'config'
	option auto_update '1'
	option update_time '3'
	option replace_music_source 'replace_all'
	option enable '1'

UnblockNeteaseMusic Node.js info:
Git HEAD version: 4af87189b3594dfa3a838d6ab33a386afea657e2
Core version: 0.27.8-patch.1
-rw-------    1 root     root      221.0K Sep  9 00:13 app.js
-rw-------    1 root     root      185.6K Sep  9 00:13 bridge.js
-rw-------    1 root     root         790 Sep  9 00:13 ca.crt
-rw-------    1 root     root         932 Sep  9 00:13 server.crt
-rw-------    1 root     root         359 Sep  9 00:13 server.key

Netease networking info:
< Location: http://m10.music.126.net/20240909004448/53004415ba0cce2b0c5265b61b486d36/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3057940231/3d32/93a3/4db1/0757f3a378b41e09ca2767c1abd47afa.mp3
{"code":200,"data":{"music.163.com":{"ip":["1.95.21.33","118.24.63.156","193.112.159.225","39.105.175.128","182.92.170.253","39.105.63.80","47.100.127.239"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":600}}}

Port status:
tcp        0      0 :::5200                 :::*                    LISTEN      26158/node
tcp        0      0 :::5201                 :::*                    LISTEN      26158/node

PROCD running info:
{
	"unblockneteasemusic": {
		"instances": {
			"log-check": {
				"running": true,
				"pid": 26159,
				"command": [
					"/usr/share/unblockneteasemusic/log_check.sh"
				],
				"term_timeout": 5,
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			},
			"unblockneteasemusic": {
				"running": true,
				"pid": 26158,
				"command": [
					"node",
					"/usr/share/unblockneteasemusic/core/app.js",
					"-a",
					"::",
					"-p",
					"5200:5201",
					"-o",
					"kugou",
					"-e",
					"https://music.163.com"
				],
				"term_timeout": 5,
				"env": {
					"LOG_FILE": "/var/run/unblockneteasemusic/run.log",
					"LOG_LEVEL": "info",
					"MIN_BR": "9999999",
					"SIGN_CERT": "/usr/share/unblockneteasemusic/core/server.crt",
					"SIGN_KEY": "/usr/share/unblockneteasemusic/core/server.key"
				},
				"respawn": {
					"threshold": 3600,
					"timeout": 5,
					"retry": 5
				}
			}
		},
		"triggers": [
			[
				"config.change",
				[
					"if",
					[
						"eq",
						"package",
						"unblockneteasemusic"
					],
					[
						"run_script",
						"/etc/init.d/unblockneteasemusic",
						"reload"
					]
				],
				1000
			]
		]
	}
}

Firewall info:
Chain netease_cloud_music (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             0.0.0.0/8           
RETURN     all  --  anywhere             10.0.0.0/8          
RETURN     all  --  anywhere             127.0.0.0/8         
RETURN     all  --  anywhere             169.254.0.0/16      
RETURN     all  --  anywhere             172.16.0.0/12       
RETURN     all  --  anywhere             192.168.0.0/16      
RETURN     all  --  anywhere             base-address.mcast.net/4 
RETURN     all  --  anywhere             240.0.0.0/4         
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_http src tcp dpt:www redir ports 5200
REDIRECT   tcp  --  anywhere             anywhere             ! match-set acl_neteasemusic_https src tcp dpt:https redir ports 5201

Name: neteasemusic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 1080
References: 1
Number of entries: 18
Members:
111.124.200.67
1.95.21.33
61.184.11.127
113.219.164.134
118.24.63.156
39.105.63.80
59.111.19.33
111.124.200.68
39.105.175.128
59.111.19.97
59.111.160.195
182.92.170.253
47.100.127.239
111.124.200.65
193.112.159.225
116.162.51.98
1.95.21.34
1.95.21.35

Name: acl_neteasemusic_http
Type: hash:mac
Revision: 0
Header: hashsize 1024 maxelem 65536
Size in memory: 208
References: 1
Number of entries: 0
Members:

Name: acl_neteasemusic_https
Type: hash:mac
Revision: 0
Header: hashsize 1024 maxelem 65536
Size in memory: 208
References: 1
Number of entries: 0
Members:

dhcp-option=252,http://192.168.100.1:5200/proxy.pac
ipset=/.music.163.com/neteasemusic
ipset=/interface.music.163.com/neteasemusic
ipset=/interface3.music.163.com/neteasemusic
ipset=/apm.music.163.com/neteasemusic
ipset=/apm3.music.163.com/neteasemusic
ipset=/clientlog.music.163.com/neteasemusic
ipset=/clientlog3.music.163.com/neteasemusic

Testing source replacing...
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0.0,"peak":null,"fee":1,"uf":null,"payed":0,"flag":524292,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null}],"code":200}
{"data":[{"id":33190502,"url":null,"br":0,"size":0,"md5":null,"code":-110,"expi":1200,"type":null,"gain":0,"peak":null,"fee":0,"uf":null,"payed":1,"flag":0,"canExtend":false,"freeTrialInfo":null,"level":null,"encodeType":null,"channelLayout":null,"freeTrialPrivilege":{"resConsumable":true,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":0,"message":null,"levelConfuse":null}],"code":200}
Succeeded in updating core.
Current core version: 4af87189b3594dfa3a838d6ab33a386afea657e2.

INFO: (app) HTTP Server running @ http://:::5200
INFO: (app) HTTPS Server running @ http://:::5201
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected
ERROR: (hook) All promises were rejected
    AggregateError: All promises were rejected

Log is available at:

### 其他信息

Log最后一行没有链接（）

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
没有正确配置音源
基于 fw3 的系统不支持劫持 ipv6 请求，需要自行过滤或手动设置代理
