### ISSUE TITLE
openwrt安装插件后，PC导入证书可以解锁，但安卓导入证书报

### ISSUE THREAD

**Issue by finfunnel** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#315]
### Bug 描述

CA证书用您提供的，导入到安卓的信任列表，打开app，就开始提示网络异常，刷新歌单直接抛ssl的错误，刷不出来，新歌也无法播放
![Screenshot_20240927_135108_com netease cloudmusic](https://github.com/user-attachments/assets/9905b6f7-6ef3-4f7b-8522-445070e0f49b)

### 预期行为

手机和PC都应该支持

### 实际行为

CA证书用插件下载的，导入到安卓的信任列表，打开app，就开始提示网络异常

### 调试报告

"http://lw.sycdn.kuwo.cn/890b6433ac41f5e1d3dc34aa7ffb14a8/66f64752/resource/30106/trackmedia/F000002hWZNd1co0vx.flac?bitrate"

### 条款

- [X] 我确认我使用的插件是由 UnblockNeteaseMusic 项目或 ImmortalWrt 项目官方发行。
- [X] 我确认我已经升级到了最新的插件版本（包括核心和插件）。
- [X] 我确认我安装了正确版本的插件（基于 lua 语言的 LuCI 只能使用 2.x 版本）。
- [X] 我确认我没有混用 iptables 和 nftables 规则。
- [X] 我确认我已经在对应的客户端正确安装了 CA 证书。

**Comment by 1715173329** [comment]
Android 需要 root 导入证书，自行 Google 搜索。

**Comment by finfunnel** [comment]
确实是已经信任了的
![Uploading Screenshot_20240927_140111_com.android.settings.jpg…]()

**Comment by finfunnel** [comment]
![Screenshot_20240927_140111_com android settings](https://github.com/user-attachments/assets/06724888-263d-4ef6-bd47-dc99a063b010)
