### ISSUE TITLE
最新更新的第二个ipk是什么，需要安装吗

### ISSUE THREAD

**Issue by banjuzaijian** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#5]
![FireShot Capture 003 - Releases · project-openwrt_UnblockNeteaseMusic - github com](https://user-images.githubusercontent.com/46417352/62673905-bb68f780-b9d2-11e9-93db-4cd924ada3a9.png)

**Comment by 1715173329** [comment]
需要。
为整理代码结构，方便同步代码更新，将luci界面与核心程序分为两个软件包。
先安装第二个，再安装第一个。
