### ISSUE TITLE
装好了，显示没运行

### ISSUE THREAD

**Issue by CChuancey** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#7]
![image](https://user-images.githubusercontent.com/37216768/66630662-45357b00-ec37-11e9-8539-b901eba6483b.png)
已经重启过路由器。

路由是小米路由3G，openwrt最新系统。

**Comment by 1715173329** [comment]
本插件仅适配OpenWrt 18.06版本，不保证在其他分支上正常运作。
请保证所需组件已安装完毕。

首次启动需要从github下载文件以更新core，需要一点时间，请保证您的网络能正常地与github建立通讯。
如果启动失败，请尝试点击更新按钮手动更新，并检查日志选项卡里的内容。
如始终无法启动，请尝试手动运行init中的命令，并检查输出内容。

**Comment by MiChuancey** [comment]
感谢你的回复，我通过/etc/init.d/unblock* 启动了插件，命令没有任何提示，应该是启动成功了。但是luci界面还是显示未运行。luci的日志和系统日志如下。
![image](https://user-images.githubusercontent.com/37216768/66639518-89ca1200-ec49-11e9-9673-f0ae8cc6a9f9.png)
![image](https://user-images.githubusercontent.com/37216768/66639570-a36b5980-ec49-11e9-8119-2f7e7c0278c9.png)

**Comment by MiChuancey** [comment]
![image](https://user-images.githubusercontent.com/37216768/66639716-f5ac7a80-ec49-11e9-8b12-2a9f9349b842.png)
luci界面已经检查成功了

**Comment by 1715173329** [comment]
```bash
node /usr/share/unblockneteasemusic/core/app.js
```

**Comment by MiChuancey** [comment]
Illegal instruction

**Comment by 1715173329** [comment]
@MiChuancey 您的nodejs程序存在问题，请安装正确的版本。

**Comment by MiChuancey** [comment]
node版本是8.10.0，不对吗

**Comment by 1715173329** [comment]
@MiChuancey 与版本无关。
可能是架构问题

**Comment by 1715173329** [comment]
@1715173329 请从 https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0-1/newifid2.zip 中获取node安装包。

**Comment by MiChuancey** [comment]
谢谢你的耐心回复。刚刚我又安装了一下你发的node，更新成功。手动启动APP，仍然是illegal instruction



---原始邮件---
发件人: "CN_SZTL"<notifications@github.com&gt;
发送时间: 2019年10月11日(星期五) 晚上6:08
收件人: "project-openwrt/luci-app-unblockneteasemusic"<luci-app-unblockneteasemusic@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Chuancey"<1210043347@qq.com&gt;;
主题: Re: [project-openwrt/luci-app-unblockneteasemusic] 装好了，显示没运行 (#7)



@1715173329 请从 https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0-1/newifid2.zip 中获取node安装包。

**Comment by 1715173329** [comment]
@MiChuancey 请在openwrt编译选项中，勾选 内核fpu模拟

**Comment by MiChuancey** [comment]
也许是我的路由器不支持node吧。



---原始邮件---
发件人: "CN_SZTL"<notifications@github.com也许是我的&gt;
发送时间: 2019年10月11日(星期五) 晚上6:17
收件人: "project-openwrt/luci-app-unblockneteasemusic"<luci-app-unblockneteasemusic@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Chuancey"<1210043347@qq.com&gt;;
主题: Re: [project-openwrt/luci-app-unblockneteasemusic] 装好了，显示没运行 (#7)



@MiChuancey 请在openwrt编译选项中，勾选 内核fpu模拟

**Comment by 1715173329** [comment]
找找fpu仿真。。谷歌有教程🌚
