### ISSUE TITLE
安装了以后更新不了核心！！

### ISSUE THREAD

**Issue by joysboss** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#98]
UnblockNeteaseMusic 未在运行

Failed to check latest core version, please try again later.
Core Not Found, please download it before starting.

**Comment by 1715173329** [comment]
请在 ssh 中输入 `unm-debug` 以打印调试报告。

**Comment by joysboss** [comment]
Launching luci-app-unblockneteasmusic Debugging Tool...


OpenWrt info:
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07-SNAPSHOT'
DISTRIB_TARGET='armvirt/64'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_TAINTS='no-all'
DISTRIB_REVISION='19.07-SNAPSHOT'
DISTRIB_DESCRIPTION='OpenWrt '


uclient-fetch info:
Package: uclient-fetch
Version: 2020-06-17-51e16ebf-1
Depends: libc, libuclient20160123
Provides: wget
Status: install user installed
Section: net
Architecture: aarch64_generic
Size: 7692
Filename: uclient-fetch_2020-06-17-51e16ebf-1_aarch64_generic.ipk
Description: Tiny wget replacement using libuclient
Installed-Time: 1602697944

Package: libustream-wolfssl20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libwolfssl24
Provides: libustream-wolfssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 4210
Filename: libustream-wolfssl20150806_2020-03-13-40b563b1-1_aarch64_generic.ipk
Description: ustream SSL Library (wolfssl)

Package: libustream-openssl20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libopenssl1.1
Provides: libustream-openssl
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 4683
Filename: libustream-openssl20150806_2020-03-13-40b563b1-1_aarch64_generic.ipk
Description: ustream SSL Library (openssl)

Package: libustream-mbedtls20150806
Version: 2020-03-13-40b563b1-1
Depends: libc, libubox20191228, libmbedtls12
Provides: libustream-mbedtls
Status: unknown ok not-installed
Section: libs
Architecture: aarch64_generic
Size: 4412
Filename: libustream-mbedtls20150806_2020-03-13-40b563b1-1_aarch64_generic.ipk
Description: ustream SSL Library (mbedtls)

uclient-fetch: SSL support not available, please install one of the libustream-.*[ssl|tls] packages as well as the ca-bundle and ca-certificates packages.
Failed to parse json data: unexpected end of data
Failed to connect to GitHub with uclient-fetch.


Node.js info:
Package: node
Version: v8.16.1-1
Depends: libc, libstdcpp6, libopenssl1.1, zlib, libnghttp2-14, libuv1, libhttp-parser
Status: install user installed
Section: lang
Architecture: aarch64_generic
Size: 4691390
Filename: node_v8.16.1-1_aarch64_generic.ipk
Description: Node.js庐 is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.
Installed-Time: 1602697944

Node.js is placed at /usr/bin/node
Node.js version: v8.16.1


luci-app-unblockneteasmusic info:
Package: luci-app-unblockneteasemusic
Version: 2.12-1
Depends: libc, busybox, dnsmasq-full, ipset, jsonfilter, node, uclient-fetch
Status: install user installed
Architecture: all
Conffiles:
 /etc/config/unblockneteasemusic e9413f9ce065cfb7b875d1948c6d3258772ab8854b7ccf193df49c3c8b6cca20
Installed-Time: 1637758961

-rw-------    1 root     root         494 Nov 24 21:45 /etc/config/unblockneteasemusic
-rwxr-xr-x    1 root     root        8.5K Nov  4 17:50 /etc/init.d/unblockneteasemusic

/usr/share/unblockneteasemusic:
drwxrwxrwx    2 root     root        4.0K Nov 24 21:39 core
-rwxrwxrwx    1 root     root        4.4K Nov  4 17:50 debugging.sh
-rwxrwxrwx    1 root     root         348 Nov  4 17:50 log_check.sh
-rwxrwxrwx    1 root     root       38.6M Nov 24 20:41 unblockneteasemusic
-rwxrwxrwx    1 root     root        3.0K Nov  4 17:50 update.sh
drwxrwxrwx    2 root     root        4.0K Nov 24 21:40 update_core

config unblockneteasemusic 'config'
	option use_custom_cookie '0'
	option auto_update '1'
	option update_time '3'
	option advanced_mode '1'
	option http_port '5200'
	option https_port '5201'
	option endpoint_url 'https://music.163.com'
	option hijack_ways 'dont_hijack'
	option strict_mode '0'
	option replace_music_source 'replace_all'
	option local_vip '1'
	option enable_flac '1'
	option pub_access '1'
	option enable '1'
	option keep_core_when_upgrade '1'
	option music_source 'bilibili'



UnblockNeteaseMusic Node.js info:
Git HEAD version: Not Found
Core version: Not Found


Netease networking info:
< Location: http://music.163.com/404
{"code":200,"data":{"music.163.com":{"ip":["103.126.92.132","103.126.92.133","59.111.160.195","59.111.19.33"],"ipv4ScoreDelay":0,"prefer":"ipv4","score":false,"ttl":300}},"msg":"OK"}

Running info:
PROCD running status: Syntax: /etc/init.d/unblockneteasemusic [command]

Available commands:
	start	Start the service
	stop	Stop the service
	restart	Restart the service
	reload	Reload configuration files (or restart if service does not implement reload)
	enable	Enable service autostart
	disable	Disable service autostart




Log is available at:
https://litter.catbox.moe/456axv.txt
https://transfer.sh/YQzxzD/unm-debugging-output.txt

**Comment by joysboss** [comment]
我下载了你的核心，放到了/usr/share/unblockneteasemusic貌似也不行

**Comment by 1715173329** [comment]
1. 缺少 libustream-openssl/mbedtls/wolfssl 库（三选一）。
2. Node.js 版本过旧，仅支持 Node.js 12.x LTS 以上版本。
3. 本插件不支持预编译的二进制文件。
