### ISSUE TITLE
[help]和openclash一起运行的相关设置

### ISSUE THREAD

**Issue by JrantKing** [UnblockNeteaseMusic/luci-app-unblockneteasemusic#99]
尝试了各种设置，最终确认只有openclash的fake ip模式和本插件没冲突，redir-host模式和解锁网易云一起用就会两个插件都失效，请问需要怎么设置能让redir-host模式和解锁网易云一起用，fake ip模式下远程pc总有问题

**Comment by 1715173329** [comment]
和 OpenClash 作者沟通了下，表示没有这个问题。
redir-host 本身就不存在冲突问题，fake-ip 也已经单独设定加以规避。
不知道什么叫做“两个插件都失效”。

**Comment by JrantKing** [comment]
> 和 OpenClash 作者沟通了下，表示没有这个问题。 redir-host 本身就不存在冲突问题，fake-ip 也已经单独设定加以规避。 不知道什么叫做“两个插件都失效”。
开启插件之后openclash的本地DNS劫持就没效果了，单独从socks5端口连接还是没有问题的，本地设备的dns就没有被软路由劫持了，我也不太清楚是哪出现了问题
或者我需要提供什么日志吗

**Comment by 1715173329** [comment]
idk，luci 打印 openclash 调试报告，ssh 运行 `unm-debug` 打印调试报告，贴出来看看

**Comment by JrantKing** [comment]
[unm.txt](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/files/7613942/unm.txt)
[openclash.txt](https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic/files/7613943/openclash.txt)


> idk，luci 打印 openclash 调试报告，ssh 运行 `unm-debug` 打印调试报告，贴出来看看

**Comment by 1715173329** [comment]
请去掉 clash 中所有关于“网易音乐”的配置，并再次尝试。
此外，本插件不会影响任何 DNS 配置。

**Comment by JrantKing** [comment]
> 请去掉 clash 中所有关于“网易音乐”的配置，并再次尝试。 此外，本插件不会影响任何 DNS 配置。
已经解决，去openclash项目逛了一圈，原来使用的dns被污染了把openclash重置默认设置会出现新的几个dns配置
